---
title: Anti-representationalism is anti-authoritarianism
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)

> There is a useful analogy to be drawn between the pragmatists' criticism of the idea that truth is a matter of correspondence to the intrinsic nature of reality and the Enlightenment's criticism of the idea that morality is a matter of correspondence to the will of a Divine Being. The pragmatists' anti-representational account of belief is, among other things, a protest against the idea that human beings must humble themselves before something non-human, whether the Will of God or the Instrinsic Nature of Reality. Seeing [anti-representationalism](/docs/phil/Anti-representationalism.html) as a version of anti-authoritarianism permits one to appreciate an analogy which was central to [John Dewey](/docs/phil/people/John Dewey.html)'s thought: the analogy between ceasing to believe in Sin and ceasing to accept the distinction between Reality and Appearance.

— [Pragmatism as Anti-Authoritarianism](/docs/phil/works/Pragmatism as Anti-Authoritarianism.html)