---
title: Better off without Philosophy
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)

> "Intuition" is just the latest name for a device which will get us off the literary-historical- anthropological-political merry-go-round which such intellectuals ride, and onto something "progressive" and "scientific" -a device which will get us from philosophy to Philosophy. I remarked earlier that a third motive for the recent antipragmatist backlash is simply the hope of getting off this merry-go-round. This hope is a correlate of the fear that if there is nothing quasi-scientific for philosophy as an academic discipline to do, if ther eis no properly professional *Fach* which distinguishes the philosophy professor from the historian or the literary critic, then something will have been lost which has been central to Western intellectual life. This fear is, to be sure, justified. If Philosophy disappears, something will have been lost which was central to Western intellectual life-just as something central was lost when religious intuitions were weeded out from among the intellectually respectable candidates for Philosophical articulation. But the Enlightenment thought, rightly, that what would succeed religion would be *better*. The pragmatist is betting that what succeeds the "scientific," positivist culture which the Enlightenment produced will be *better*.

— [Consequences of Pragmatism](/docs/phil/works/Consequences of Pragmatism.html), Introduction