---
title: Describing and explaining
tags: 
 - quote

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/describing and explaining.yml
---

[Author](/docs/phil/people/Wilfrid Sellars.html)

> Although describing and explaining are distinguishable, they are also in an
important sense inseparable. The descripitive and explanatory resources of
language advance hand-in-hand. 

— [Counterfactuals, Dispositions, and the Causal Modalities](/docs/phil/works/Counterfactuals, Dispositions, and the Causal Modalities.html) §108

- These two kinds of discursive activity; one can be describing in a
  particular act and not explaining (and vice-versa).
- Globally, they're only intelligible in terms of their relation to
  each other. 
  - ([describing is placing in a space of implications](/docs/phil/quotes/Space of reasons.html),
     which is relevant for explanation.
- The claim that matters: you couldn't have an [language](/docs/phil/Autonomous discursive practice.html) in use that had one and not the other.
- The reason is at least that in order to describe something you have to place it in a space of implications (i.e. the above quote)
