---
title: Desirability of post-Philosophical culture
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)


> So the question of whether such a post-Philosophical culture is desirable can also be put as the question:... Can we see ourselves as never encountering reality except under a chosen description... the question of whether we can give up what Stanley Cavell calls the impossibility that one among endless true descriptions of me tells who I am."... In a post-Philosophical culture, some other hope would drive us to read through the libraries, and to add new volumes to the ones we found. Presumably it would be the hope of offering our decendants a way of describing the ways of describing we had come across - a description of the descriptions which the race has come up with so far. If one takes "our time" to be "our view of previous times," so that, in Hegelian fashion) each age of the world recapitulates all the earlier ones, then a post- Philosophical culture would agree with Hegel that philosophy is "its own time apprehended in thoughts." In a post-Philosophical culture it would be clear that that is all that philosophy can be. It cannot answer questions about the relation of the thought of our time - the descriptions it using, the vocabularies it employs - to something which is not just some alternative vocabulary. So it is a study of the comparative advantages and disadvantages of the various ways of talking which our race has invented.

— [Consequences of Pragmatism](/docs/phil/works/Consequences of Pragmatism.html), Introduction