---
title: Eclipse view of pragmatism
tags:
 - quote 

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/eclipse view of pragmatism.yml
---
[Author](/docs/phil/people/Cheryl Misak.html)

> A complaint has run through pragmatism for the last few decades. That complaint is that analytic philosophy has nearly killed off pragmatism. On this view, which Robert Talisse1 has called the ‘eclipse view’, when Richard Rorty brought his considerable talents to the pragmatist scene in the 1970s, there were very few pragmatists or students of American philosophy in top-tier American universities. Pragmatism was operating on the margins, driven from philosophy departments by the reigning analytic philosophy. Rorty resurrected it from its near-death, but in a resolutely anti-analytic version, a version despised by the ruling philosophical class. The idea is that pragmatism is set against analytic philosophy and has suffered from challenging this wrong-headed but domineering winner of the philosophical stakes. A sense of persecution has thus hung over certain quarters of American pragmatism.

— [Rorty, Pragmatism, and Analytic Philosophy](/docs/phil/works/Rorty, Pragmatism, and Analytic Philosophy.html)