
---
title: Epistemology is dead
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)

> In the previous chapter I said that the epistemological tradition [confused](/docs/phil/interaction/Reasons vs causes.html) the causal process of acquiring knowledge with questions concerning its justification. In this chapter I have presented Sellars's criticism of the [Myth of the Given](/docs/phil/Myth of the Given.html) and Quine's criticism of the notion of truth by virtue of meaning as two detailed developments of this more general criticism. If we accept these criticisms, and therefore drop the notion of [epistemology](/docs/phil/Epistemology.html) as the quest, initiated by Descartes, for those privileged items in the field of consciousness which are the touchstones of truth, we are in a position to ask whether there still remains something for epistemology to be. I want to urge that there does not.

 — [Philosophy and the Mirror of Nature](/docs/phil/works/Philosophy and the Mirror of Nature.html), Chapter 4