
---
title: Giving meaning to life
tags:
 - quote 
---

[Author](/docs/phil/people/Richard Rorty.html)


> There are two principal ways in which reflective human beings try, by placing their lives in a larger context, to give sense to those lives.  
>
> The first is by telling the story of their contribution to a community. This community may be the actual historical one in which they live, or another actual one, distant in time or place, or a quite imaginary one, consisting perhaps of a dozen heroes and heroines selected from history or fiction or both.
> 
> The second way is to describe themselves as standing in immediate relation to a nonhuman reality.
> 
> The tradition in Western culture that centers on the notion of the search for Truth, a tradition that runs from the Greek philosophers through the Enlightenment, is the clearest example of the attempt to find a sense in one's existence by turning away from solidarity to objectivity.

— [Solidarity or Objectivity](/docs/phil/works/Solidarity or Objectivity.html)
