---
title: Platonists vs empiricists
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)

> Within Philosophy, there has been a traditional difference of opinion about the Nature of Truth, a battle between (as Plato put it) the gods and the giants. On the one hand there have been Philosophers like Plato himself who were otherworldly, possessed of a larger hope. They urged that human beings were entitled to self-respect only because they had one foot beyond space and time... In the nineteenth century, this opposition crystallised into one between "the transcendental philosophy" and "the empirical philosophy," between the "Platonists" and the "positivists."... To be on the transcendental side was to think that natural science was not the last word -that there was more Truth to be found. To be on the empirical side was to think that natural science-facts about how spatio-temporal things worked-was all the Truth there was... It is important to realise that the empirical philosophers -the positivists-were still doing Philosophy...

— [Consequences of Pragmatism](/docs/phil/works/Consequences of Pragmatism.html), Introduction