
---
title: Pragmatist social hope
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)

> James and Dewey wrote, as Nietzsche and Heidegger did not, in a spirit of social hope. They asked us to liberate our new civilization by giving up the notion of "grounding" our culture, our moral lives, our politics, our religious beliefs, upon "philosophical bases." They asked us to give up the neurotic Cartesian quest for certainty which had been one result of Galileo's frightening new cosmology, the quest for "enduring spiritual values" which had been one reaction to Darwin, the aspiration of academic philosophy to form a tribunal of reason which had been the neo- Kantian response to Hegelian historicism. They asked us to think of the Kantian project of grounding thought or culture in a permanent ahistorical as reactionary. They viewed Kant's idealization of Newton, and Spencer's of Darwin, as just as silly as Plato's idealization of Pythagoras, and Aquinas' of Aristotle.

 — [Pragmatism, Relativism, and Irrationalism](/docs/phil/works/Pragmatism, Relativism, and Irrationalism.html)