
---
title: Rorty defending Sellars and Quine
tags:
 - quote
---

[Author](/docs/phil/people/Richard Rorty.html)

> In order to defend Sellars and Quine, I shall be arguing that their holism is a product of their commitment to the thesis that justification is not a matter of a special relation between ideas (or words) and objects, but of conversation, of social practice. Conversational justification, so to speak, is naturally holistic, whereas the notion of justification embedded in the epistemological tradition is reductive and atomistic. I shall try to show that Sellars and Quine invoke the same argument, one which bears equally against the given-versus-nongiven and the necessary-versus-contingent distinctions. The crucial premise of this argument is that we understand knowledge when we understand the social justification of belief, and thus have no need to view it as accuracy of representation.

 — [Philosophy and the Mirror of Nature](/docs/phil/works/Philosophy and the Mirror of Nature.html), Chapter 4