---
title: The Centrality of Sellars' Two-Ply Account of Observation
categories: ⚪
author: Robert Brandom
published: 2002
listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../../../../ejs/custom.ejs"
  contents:
    - ../../../../../../backlinks/docs/phil/people/brandom/works/two_ply/index.yml
---

[-@brandom2002centrality]

# Quotes 

> ... according to 
Sellars’s view,  the  distinction  between  theoretical  objects  and 
observable  objects  is  methodological, rather than ontological. That is, 
theoretical and observable objects are not different kinds of thing. They 
differ only in how we come to know  about  them.  Theoretical  objects  are 
ones  of  which  we  can  only  have  inferential knowledge, while observable 
objects can also be known noninferentially. Theoretical concepts are ones we 
can only be entitled to apply as the conclusions  of  inferences,  while 
concepts  of  observables  also  have  noninferential uses. But the line 
between things to which we have only inferential cognitive access and things to 
which we also have noninferential cognitive access can shift  with time, for 
instance as new instruments are developed. Thus when first postulated to explain 
perturbations in the orbit of Neptune, Pluto was a purely theoretical object; 
the only claims we could make about it were the conclusions of inferences. But 
the development of more powerful telescopes eventually made it accessible to 
observation, and so a subject of noninferential  reports.  Pluto  did  not  then 
undergo  an  ontological  change.  All that changed was its relation to us.