---
title: 02 - Rorty’s Critique of Enlightenment Representationalism and Analytic Philosophy
aliases: [rorty02]
tags:  
- lecture
- RED

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/02 - rorty’s critique of enlightenment representationalism and analytic philosophy.yml
---

[Author](/docs/phil/Robert Brandom.html) [Prev](/docs/phil/01 - The Concept of Representation.html) [Next](/docs/phil/03 - Rorty Finds His Pragmatist Voice.html)

A discussion of [Philosophy and the Mirror of Nature](/docs/phil/Philosophy and the Mirror of Nature.html). Brandom views the core argument to be chapter 4, which this lecture focuses on.

# Rorty's basic idea
## Neokantianism vs a socialized/historicized/naturalized alternative

- Rorty redescribes the history of philosophy as a struggle over the [Relation of philosophy to other disciplines](/docs/phil/Relation of philosophy to other disciplines.html). Fought by two camps in the 19th century and then re-enacted in the 20th century.
  - **[Neokantianism](/docs/phil/Neokantianism.html)** Philosophy has sovereign authority over the high culture.
    - Idea originates with [Plato](/docs/phil/Plato.html), but Descartes / Kant /  representationalism are modern versions.
  - **Neohegelianism**/pragmatism ([Hegel](/docs/phil/Georg Wilhelm Friedrich Hegel.html) socialized philosophy, [Marx](/docs/phil/Karl Marx.html) naturalized it). Philosophy brought 'down to Earth'. The American pragmatists continued in this path.
- [Bertrand Russell](/docs/phil/Bertrand Russell.html) and [Husserl](/docs/phil/Edmund Husserl.html) found things for philosophy to be apodictic about. Basis of Rorty's 'astonishing' claim that [analytic philosophy](/docs/phil/Analytic philosophy.html) is just a phase of neokantianism
  - Russell and those downstream don't think of themselves this way.
  - But they share the idea that philosophy of language is "first philosophy" and that linguistically-inflected philosophy of mind could advance our notions of epistemology and general theory of representation.
  - Shared emphasis on understanding language semantically, distinct from understanding knowledge epistemologically.
  - Husserl subject to Sellars' critique of the  [Myth of the Given](/docs/phil/Myth of the Given.html),  [Russell](/docs/phil/Bertrand Russell.html) subject to Quine's critique of the [Myth of the Museum](/docs/phil/Myth of the Museum.html).  ([Carnap](/docs/phil/Rudolf Carnap.html) is subject to both myths).
- Rorty regards the pragmatist/holist Quine+Sellars rebuttals as bringing us back to [Dewey](/docs/phil/John Dewey.html)'s socialized / historicized / naturalized philosophy.[^de]

[^de]: the 20th century was a big pointless detour, recapitulating the same dielectic, just now with fancier technical / logical machinery.

## Assimilation of two kinds of representations

Similarities of Sellars and Quine:  

- gave *holist* arguments, rejecting a kind of *atomism*. 
- mentored by [C. I. Lewis](/docs/phil/C. I. Lewis.html) and hugely influenced by Carnap.
- they did not take to heart each other's holist arguments 

| | Sellars | Quine |
|--|--|---|
| Myth | [Myth of the Given](/docs/phil/Myth of the Given.html) |  [Myth of the Museum](/docs/phil/Myth of the Museum.html)| 
| Relevant work | [Empiricism and the Philosophy of Mind](/docs/phil/Empiricism and the Philosophy of Mind.html) | [Two Dogmas of Empiricism](/docs/phil/Two Dogmas of Empiricism.html) | 
| Concept challenged | Sense-givenness | Meaning-givenness |
| Against atomism in | [Epistemology](/docs/phil/Epistemology.html) | [Semantics](/docs/phil/Semantics.html) | 
| Kantian representation | Sense impression | Meaning-relation | 
| Regress stopped | premises[^rp] | inferences[^ri] | 

Rorty was the first to see a common functional role to the above kinds of Kantian representation (and a common structure to Sellars' and Quine's critiques).

- They are *privileged* representations
- They serve as infinite regress stoppers, for premises and inferences.
  
[^rp]: [Agrippan trilemma](/docs/phil/Agrippan Trilemma.html): we need to stop the infinite regress of premises (unjustified justifiers). Pretty much everyone's candidate for these is the sensuous given.
[^ri]:  We need inferential transitions that have authority. These are not the same as premises, c.f. [What the Tortoise said to Achilles](/docs/phil/What the Tortoise said to Achilles.html).

What properties must these representations have to be "privileged"? 

- They must be authoritative and immediate
	- Authority not dependent on any collateral commitments
	- a kind of atomism is a consequence of their existence: the semantics of these privileged representations must be independent of their epistemology. 
		- for quine, this means that language must be independent of theory, meaning must be independent of collateral beliefs
		- for sellars, bits of the sensous given must be independent of other bits you have access to. Most importantly they have to be independent of your other beliefs.
  - Quine's and Sellars' critiques render such semantic privilege as practically unintelligible. 
  - The next section will describe how they cannot simultaneously be atomic while playing the role of regress stoppers.

Quine's argument:

 - the meaning has to at least define the inferential role. (they are being used as regress stoppers for inferential moves - they have to settle which of those are good or not)
 - However, the [Duhem-Quine thesis](/docs/phil/Duhem-Quine thesis.html) shows that inferential role cannot be atomistic.
 - So you can't fix your language in advance of saying which statements are true.

Sellars' argument:

- For a sensory experience to play an *evidential* role (to serve as the justification of some other claim), it has to be conceptually articulated.
- You can't just have this concept in isolation, because having the concept is understanding the concept's inferential relations. [^witt]

Holism at the level of semantics (the *meaning* of one of these privileged representations cannot be independent of other representations). And holism at the level of [semantics and epistemology](/docs/phil/Semantics and epistemology.html) (the *meaning* of one of these privileged representations cannot be independent of which ones we are committed to).

Both Sellars and Quine (pragmatically) ask "What do you have to be able to do?" in semantics and epistemology in order to argue for their holism.

[^witt]: [Agreement on meanings requires agreement of judgments](/docs/phil/Agreement on meanings requires agreement of judgments.html)


## Holism of Sellars and Quine

- Sellars in [EPM](/docs/phil/Empiricism and the Philosophy of Mind.html)
  - [Locke](/docs/phil/John Locke.html) got confused by conflating the causation of a belief from its justification. See [Reasons vs causes](/docs/phil/Reasons vs causes.html) distinction.
  - Sense data may be causally prerequisite to knowledge, but it cannot justify belief (it's not conceptually contentful, in the sense of standing in reason relations of implication/justification).
    - To stand in reason relations requires lots of other infrastructure, such that atomic sense data cannot do this on its own (this is a semantic holist argument)
    - How do we acquire knowledge in the semantic holist POV?
      - How to get into the game of giving and asking for reasons? "The light dawns slowly over the whole" We need to get good enough at making the 'right' moves (as judged by 'competent speakers' before counting as a 'competent speaker'.
- Quine in [Two Dogmas of Empiricism](/docs/phil/Two Dogmas of Empiricism.html)
  - Target: analytic truths, e.g. "cats are mammals" supposedly not depending on  any other commitments but rather immediately from the meanings of the words.
  - What is the practical difference between these truths and very general facts, such as "there have been black dogs."
  - [Duhem-Quine thesis](/docs/phil/Duhem-Quine thesis.html) 
    - What inferences we are allowed to make depends on the whole of collateral beliefs we have.
- The unit of meaning must be the web-of-belief rather than the concept or the sentence.
- [Fodor](/docs/phil/Jerry Fodor.html) argues against this, considers mixing epistemology and semantics to be a big philosophical mistake initiated by Quine.



## Who is Rorty opposing?

Is Rorty attacking a strawman? Rorty sees representationalism in semantics as bound up with [foundationalism in epistemology](/docs/phil/Foundationalism.html), but the two aren't actually tied together.[^knt] Empiricism / epistemological foundationalism are not popular now:

- "Default and challenge" structure a way of avoiding [Agrippan trilemma](/docs/phil/Agrippan Trilemma.html) without challenging the language-theory distinction.
- Bayesianism sees all justification as comparative (never have to justify one's prior commitments).
  - though the problem of semantics is still open, if it is to not be representationalist
- Naturalism + representationalism remains unchallenged.
  - picking an ontologically privileged base vocabulary
- So Rorty and [Price](/docs/phil/Huw Price.html) need to do one or both of:
  1. Argue independently for [pragmatism](/docs/phil/Pragmatism.html), then use that to attack representationalism without passing through foundationalism
  2. Argue independently against representationalism and propose pragmatism as the best alternative approach

[^knt]: Kant did not feel the need to address the Cartesian problematic / Agrippan trilemma. He felt that, once he resolved semantic skepticism and got clear of how it is possible for our thought to be object directed at all, that it was a trivial consequence that we need not worry about being radically out of touch with reality, as Descartes worried about. (His [Refutation of Idealism](https://plato.stanford.edu/entries/kant-transcendental/#RefIde) is quite short).