---
title: 05 - Rorty's Literary Turn
aliases: [rorty05]
tags:  
- lecture
- STUB

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/05 - rorty's literary turn.yml
---

[Author](/docs/phil/Robert Brandom.html) [Prev](/docs/phil/04 -  Cheryl Misak's Critique of Rorty's Pragmatism.html) [Next](/docs/phil/06 - Rorty's Political Turn.html)



Rorty's literary kehre lasted 10 years. But he realized he's an analytic philosopher and that literary theorists didn't know how to make distinctions and were not good to talk to. He then had a political kehre (had extended interactions with Habermas).


# Rorty's argument

Here are five claims or moves Rorty might be seen to be making:

1.  Rejecting two-stage talk of two activities, one of instituting meanings and the other of applying them to justify beliefs. [^tde]
2.  Rejecting the language/theory distinction entirely, in favor of the ‘vocabulary’ vocabulary. All we do is use vocabularies, and those practices both institute meanings and apply concepts to undertake commitments (endorse, take-true, some claimables).
3.  Rejecting the Kantian problematic of assigning responsibility for some features of our discourse (vocabulary-use) to what we are talking about (what is represented)—the authority of the objective—and responsibility for other features of our discourse to us— the authority of the subjective.
4.  Rejecting as ultimately unintelligible the idea that our thought is normatively constrained (as opposed to causally constrained) by an objective world via the representational semantic dependence of representings on representeds that consists in representeds providing normative standards of assessment of the correctness of representings (in a distinctive sense of “correctness.”). This is a kind of authority of representeds over representings.
5.  Social pragmatism about normativity: all normative statuses (responsibility, authority, being a standard of correctness) are social statuses.

[^tde]: The appeal here is to Quine’s pragmatist arguments in [Two Dogmas of Empiricism](/docs/phil/Two Dogmas of Empiricism.html).


# RR on Romanticism
Mediating between idealism and pragmatism.

Romanticism has idealist and pragmatist tendencies. Idealism corresponds to [weak textualism](/docs/phil/Strong and weak textualists.html), while pragmatism to strong. The weak ones haven't freed themselves from Philosophy.

Rorty gives a [redescription of Nietzsche](/docs/phil/Pragmatism and Nietzsche.html), an example of the kind of strong textualism which takes a text and beats it into a shape to suit the reader's purpose, imposing his own vocabulary on it.

Rorty [reconstructs](/docs/phil/Hegel literary genre.html) a progression from *idealism* to *romanticism* to *pragmatism*.

Rorty makes a number of claims:

1. [all problems, topics, and distinctions are language-relative](/docs/phil/Textualists and language relativity.html)
2. [criticizing any philosophical view that presupposes an objectively privileged vocabulary (simply in virtue of its relation to its subject matter)](/docs/phil/Strong and weak textualists.html)
3. [the vocabulary of science is merely one among others](/docs/phil/Romanticism as vocabulary over truth.html)
	- The privilege that science (controlling nature) has is not inherently privileged over other possible advantages other vocabularies have
4. Romanticism defined as "the one thing needful was to discover not which propositions are true but rather what vocabulary we should use."

What's important about being human is our ability to self-transform, redescribe.  Romanticism was important because of its focus on that capacity as the center of human aspiration, rather than getting things right representationally.

Rorty has a notion of a "presiding cultural discipline" - since the Enlightenment it has been science, but in the future it could be literature. Science was emancipatory at the start of the Enlightenment, but by the end of the 19th century it became constraining.

## Danger: backsliding into Carnappian pragmatism

Rorty says that what the romantics discovered that we are free to pick our vocabulary.

Treating vocabularies as if they are languages that we are free to chose from is dangersouly close to Carnappian pragmatism. This is a misuse of the vocabulary vocabulary because it violates Quine's anti-Carnap lesson.


# Criticism of "There is nothing outside of the text"[^mcd]

Rorty classifies this claim of [Derrida](/docs/phil/Jaques Derrida.html) as "weak textualism" and sees it as backsliding into representationalist philosophy.

{{< include "Textualism as misleading.qmd" >}}


[^mcd]: Note that McDowell centrally claims "The conceptual has no outer boundary" in [Mind and World](/docs/phil/Mind and World.html)

Some background for Derrida's claim:

He is working in a post-structuralist environment. Their principal tool is de Saussure's signifier/signified model.

This is a linguistic version of Berekle's "it's representings all the way down" idealism.

Derrida restricts it to just the signifier side. Brandom: "If we really understand structuralism (thinking of the functional roles of signifiers) we'll see that there is only the signifiers to worry about".

Brandom says this model is semantically inadequate as a model and not even a radical rejection of the signifier/signified model. He wants to file it away in a cabinet labeled "How not to be an antirepresentationalist".

Pierce said similar things about interpretants and interpreters. His principal admirer Charles Morris used this notion of the name-bearer relation to found semiotics, which is not a successful field.

This is not just [representationalism](/docs/phil/Representationalism.html), it is nominalistic representationalism (Taking tha name-bearer relationship as the semantic paradigm). It is all pre-kantian, preFregegian, preWittgensteinien.
- Kant: the judgment is the smallest unit of awareness/consciouness (and committment, the smallest thing we can be held responsible for). We can only understand names in terms of the roles they play in reasoning. 
- Frege: What's expressed by sentences is special/prior in order explanation to the semantic content of proper names. Because a declarative sentence is the smallest unit to which pragmatic force can attach.
- Early Wittgenstein: prioritized propositional signs (saw the world as facts, not things). 
- Later Wittgenstein: the smallest move in a language game.

Brandom calls it "the worst combination" to be declarativist, representationalist, and nominalist.

Tarskian model theory (and following it, possible worlds semantics) is *not* nominalistic: it starts with semantic relations understood nominalistically, but then it builds up representational readings of sentences as sets of models / possibles worlds (those are treated differently from the names)

There is a connection between this topic and the vocabularity-relativity / objectivity. One question we can ask: to what extent is the categorical-structure of the world a vocabulary-dependent phenomenon? 
- Ask how we are to address debate two ways of thinking of the objective world we are talking about: is it (as wittgenstein puts it) a world of facts or a world of things?
Rorty thinks, if you say it's a world of facts, you've conceded his antirepresentationalist point (because the notion of fact[^f] is a vocabulary-relative). 

[^f]: Frege says: a fact is a thought (i.e. thinkable) that is true.

You might try to avoid this by thinking of a world of objects, but objects are equally vocabulary-dependent. (you need *[sortals](/docs/phil/Sortals.html)* to distinguish objects).

# Two senses of vocabulary-dependence

The way in which the law-like / categorial structure of the world *depends* on us is dependence in the order of understanding, not the order of being.

"There is nothing outside the text" goes wrong because it seems like a claim of the order of *being*, not just explanation. It violates the lesson of [Lincoln's horse](/docs/phil/Lincoln's horse.html) example. This [confuses](/docs/phil/-ing vs -ed distinction.html) thinkings for thinkables.

[Sense dependence vs reference](/docs/phil/Sense dependence vs reference.html) is relevent: One is frightened of claims of vocabulary dependence because one is thinking of reference- dependence claims. What is arguable is sense-dependence.

- You can't understand the notion of a fact without understanding the notion of a declarative sentence
- You can't understand the notion of an object without understanding a singular term + sortal in a language
- You can't understand the concept of a law with understanding modally quantified conditionals.

There is a sense dependence[^ff] between concepts we use to articulate the categorial structure of the world and concepts we use to describe various features of vocabularies in use (grammatical categories).

To assert that sense dependence is *not* to assert a reference dependence.

[^ff]: ==This is functorial==

When someone makes a vocabulary-dependence claim
(e.g. the lawfulness of a relation between two properties is a feature of our cognitive faculties) it makes a big difference whether this is a sense or reference dependence claim.
- Without understanding what it is for you to follow a rule / to infer $B$ from $A$, you can't *understand* the lawfulness that you're taking the world to have.
- This does not entail a reference dependence.

We need to be careful when reading Rorty (who doesn't explicitly make this distinction) that we are not accepting his claims (as plausible because they are sense-dependence) and then letting him draw consequences from them (as if they were reference-dependence).

Brandom suggests that to understand the notion of a fact, one needs to understand the notion of a judgment (and vice-versa). Likewise, to understand the notion of an object and to understand the notion of a singular term in a language also must be understood together (two sides of one coin).

# Pragmatist conceptual progress

{{< include "Grenzbegriff.qmd" >}}

We can only tell progress (that one vocabulary is an improvement) *retrospectively*, from within our current vocabulary. There's nothing outside the dialogue.

But we can imagine institutions of science being taken over by religious fanatics. They'll be able to make a retrospective story too. Rorty has to say "We hope that this won't happen, but history is written by the victors."

Brandom challenges this and offers a pragmatist-sanitized notion of *pro*spective, technological progress.
- The new technology has to be able to do what we're already doing (better than we can).
- This is evaluated in *our* current vocabulary.
- This sorts future retrospective stories into good or bad from our perspective.

This is what persuaded the conquering Arabs to keep Greek learning - they *knew* Greek medicine could save people from battlefield wounds that were otherwise surely fatal. When the Greek doctors said that to understand how, you needed to think about how the microcosm and the macrocosm were related, the Arabs had little choice but to think that all that Greek literature and philosophy must be valuable and should be preserved. Aristotle would not be able to appreciate how accurately we can measure the mass of the electron. But he would be impressed by our medicine, by our ability to blow large holes in the ground, move things rapidly over great distances, build large, stable structures...and so on.  

The demand for technological conservation and progress, understood by prospective normative standards set by earlier practical attitudes and assessments puts a genuine constraint on what counts as theoretical progress, understood by retrospective normative standards set by later practical attitudes and assessments.

We could *define* technological progress as that which can be measured prospectively.[^tp] Then we can make it a criterion of adequacy for a good "retrospective story" that it must be technologically progressive (in domains of the empirical world). We might not care, e.g. for poetic traditions, that we preserve prospective progress. 

[^tp]: This would be what we call "technological progress" in our *current* vocabulary

Brandom ties this to Pierce's theory of progress. What is prospectively assessible is a constraint on what is retrospectively assessible. This is a way to not be mere carnappian progress but see real friction between vocabularies in use (without thinking in representationalist terms).


# Pragmatist version of Kantian problematic

Brandom suggests that we can accept the vocabulary vocabulary without drawing Rorty's conclusion that we need to move beyond the Kantian problematic.

Example of counting apples: each community which can do this has a different ordered set of expressions ("1,2,3...", "$\alpha,\beta,\gamma$...", etc). But each community says there is the same count of apples. It seems like it is up to us how to count the apples but the actual count is vocabulary independent.

It's through understanding relationships between the vocabularies that we can achieve something vocabulary independent (e.g. the isomorphism between "1,2,3..." and "$\alpha,\beta,\gamma$...").

You say "it weighs 1" and I say "no it ways 2.2" - what has to be true about our practice for someone outside us to say "they are both measuring *the (objective) weight* (with units lb and kg)". This requires ground-level pragmatism engineering to find out such-and-such properties need to preserved in the language mapping . 


==This is saying that a pragmatist strategy for making an objective/subjective distinction is via mappings between languages (characterizable via universal properties?)==
