---
title: 19. Epistemic vigilance
tags: 
 - podcast
 - RED
subtitle: Dan Sperber
published: January 12, 2011

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/19. epistemic vigilance.yml
---

[Elucidations](/docs/phil/Elucidations.html): [Prev](/docs/phil/18. Language and power.html) [Next](/docs/phil/20. Faith.html)

- Information given to us via testimony vs sense experience
  - There are many situations where we trust and others where we distrust
  - Need to be able to benefit from communication with others.
    - Reductionist: Must have a reason to trust.
    - Anti-reductionist: We can trust testimony unless we have reason to 
      distrust.
      - Counterpoint:
        - Our senses work to serve our interests. Others have their own 
          interests.
        - One communicates with another to have an effect on them. Maybe this is 
          benevolent, maybe it's hostile.
- Vigilance: on guard for interlocutors who don't have our best interest at 
  heart.
  - Analogy: we walk in a crowd without issue because everyone is vigiliant.
  - This would not be possible if we thought every stranger would completely 
    ignore us.
  - So we need trust, but we are not paralyzed by consciously 
    distrusting-by-default each stranger. The community vigilance is the 
    solution.
- How do we trust people without vigilance:
  - It's possible, after all children do it.
  - However, at some point it will be in someone's interest to deceive.
- Communication is valuable because others are vigilant
  - There exist social costs to miscommunication / deception / cheating.
- Descriptive questions too (not just normative)
  - What we do is close to the reductionist's norm
  - Experimental psychology experiments
    - People encounter a new face and instantly look for trustworthiness
      - there is the least variation in 'trustworthiness score' (among other 
        properties) when you vary the amount of time a subject has exposed to 
        the picture
    - Children as young as 3 will trust the information from a 'nice agent' over 
      a 'mean agent'
  - However maybe life would be better if everyone trusted a littlee more 
    (even if there were slight higher personal risks). Collective action 
    problem.
  - Multiple independent sources of some belief reinforce strength of that 
    belief.
  - Peer review system reflective of epistemic vigilance norms.
