---
title: 21. Political liberalism
tags: 
 - podcast
 - RED
subtitle: Raymond Geuss
published: March 7, 2011

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/21. political liberalism.yml
---

[Elucidations](/docs/phil/Elucidations.html): [Prev](/docs/phil/20. Faith.html) [Next](/docs/phil/22. Collective action.html)

- What does "liberalism" refer to?
  - Used in such a wide variety of senses that it means almost nothing at all 
    now.
    - Not useful to use the term to think about society or use as a normative 
      concept
  - A historical approach to the term is valuable
    - The result of a large tradition of different components fusing together
      - After many things have fused together (by convenience) it looks like 
        they come together by necessity
      - This makes the whole framework seem self-evident, which is convenient  
        for your political system to have
    - E.g. democracy and liberalism seem like they belong together
      - liberalism has toleration as a core principle
      - democracy has no such commitment - you could vote to ostracize someone 
        people don't like.
      - democracy doesn't like elections.
    - Another strand: voluntaryness better than force
    - Another strand: fear of concentrated power
    - Another strand: individual > group
    - Another strand: laissez faire capitalism
- Two components of liberalism Geuss is worried about
  - Neutrality
    - There is no notion of 'neutrality' that is both weak enough to be a 
      sensible notion as well as strong enough to do the normative job liberals 
      want it to do
    - Neutrality itself cannot be a generator of political value
  - Consensus
    - It's not that lack of consensus is good and it's good to push people 
      around
    - Rather, consensus must be treated as an empirical concept
      - As opposed to a 'necessary condition of society' - that's not true
        - Making it this weak would be vacuous; would allow one to say "members 
          of concentration camps were in a consensus with their guards, as they 
          formed a social system"
      - Moving to a more realistic/empirical notion, e.g. everyone checking off 
        the same box in the voting booth, this doesn't have any normative power
    - There's a feeling that every disagreement can be resolved to consensus.
      - It isn't proven that it's always possible, nor if it is possible that 
        it's good.
      - Kant argues that we have a natural tendency to overgeneralize from 
        experience
        - E.g. We see things in our life have causes, and then think everything 
          has a cause, which leads to the concept of God
        - Likewise, the belief that everything can be resolved by consensus fits 
          this pattern.
        - This is part of the plausibility of liberalism:
          - I like to be free, I don't like to be pushed around, I like us to be 
            in consensus (this is fine)
          - Now jump to saying this can be done for the whole world
            - This can't be taken for granted.
- Is the above an accusation that liberalism is hypocritical?
  - E.g. America was based on consensus while nonconsensually displacing Native 
    Americans.
  - Geuss:
    1. 'hypocrisy' is too strong of a term, which implies a conscious 
       duplicitousness
    2. Human beings are self-centered (we see ourselves as more central than we 
       actually are, want to see ourselves as good) which is at odds with 
       liberal ideal
- Should we make incremental adjustments vs revolution to fix liberalism?
  - Geuss: keen on preserving our abilities to imagine utopias.
  - We can transform some of those aspirations into practical action.
  - There is a gap betweeen action and imagination.
    - Pragmatists eliminate that gap, 'reduce' imagination just to action.
  - Nothing wrong with aspirations that are not immediately realized - they can 
    remain in the culture until they are realized.
  - So we can pursue both the immediate and more radical changes.
- What role is there for art to play in developing our political imagination?
  - Escaping from politics is a kind of politics, after all
    - Escape because politics at the moment is intolerable/unworkable.
  - Two ways:
    1. Political novels like Flaubert's Salembot
      - descriptions of radically different worlds
      - having an imaginative picture of a particular world makes us relate to 
        our own reality differently
    2. Norm-breaking poetry, like Paul Celan:
      - Language rules are oppressive, conformist
      - Use words in different ways to break stifling forms of everyday speech
