---
title: 34. Moral disagreement
tags: 
 - podcast
 - RED
subtitle: Kieran Setiya
published: April 9, 2012
---

[Elucidations](/docs/phil/Elucidations.html): Prev Next

- Moral realism - moral claims are objectively true or false
  - Morals are objects of belief (things out there)
    - E.g. courage is a virtue / justice is a virtue
  - Moral disagreement is possible between individuals and across cultures (no 
    moral relativism in that sense)
  - Question KS is interested:
    - what are the implications of moral reason
- But moral disagreement makes people think moral realism is false.
  - If it were true, then we'd converge on the truth like science.
    - But it's unclear why one would think moral facts would make people 
      converge on a solution.
      - Also historically, we had long periods of time where you'd look back and 
        not see convergence (e.g. whether world was flat or not). By analogy, 
        perhaps we are doing that with in morality.
    - It's rather about how we can be justified to believe moral truths that 
      would make you expect
  - But moral disagreements persist.
    - Even if we imagined knowing all the possible 'scientific facts'
    - Sidestep with two moves
      1. Shift from disagreements about morality to ethics (more broad: like 
        "how to live")
        - There are cases of philosophers who've held diametrically opposed 
          views for millennia
          - E.g. Selfishness vs altruism
        - "If your views are true and confront with others who views are false, 
          you should stick to your guns."
        - In discussions of disagreement, we have a view "the equal weight view"
          - You should give others' views equal weight to your own without a 
            prior reason to discount their beliefs
          - Leads to skepticism.
          - But it's not plausible because (argument of Tom Kelly)
            - It has you reason as if your only prior is how much you were 
              likely to be right.
            - Nonmoral example:
              - weather prediction example
          - Equal weight view IS reasonable for perceptual experiences (this is 
            where it gets its power from). The problem is philosophers who liken 
            moral intuitions to perceptual appearances.
          - What is the alternative in the non-perceptual cases
            - Problematic alternative:
              - Keep the belief that moral beliefs bottom out in perceptual 
                intuitions.
              - But relativize people's intuitions (break asymmetry by saying 
                opponent has bad intuitions or that morality's purpose is to 
                provide coherence of just your beliefs)
              - However, this is epistemic egoism.
            - Better alternative:
              - There is an asymmetry in the standard of justification of moral 
                beliefs: true beliefs have better evidence for them.
                - Coherentists/reflective equilibrium etc. want to find a 
                  standard of justification that is independent of taking a 
                  stance on particular moral beliefs.
      2. ???
  - Knowing all nonmoral facts doesn't help you resolve moral facts.