---
title: Analytic philosophy is neokantian
tags: 
 - quote
---

[Author](/docs/phil/Richard Rorty.html)

> The kind of philosophy which stems from Russell and Frege is, like classical Husserlian phenomenology, simply one more attempt to put philosophy in the position which Kant wished it to have - that of judging other areas of culture on the basis of its special knowledge of the "foundations" of these areas. "Analytic" philosophy is one more variatn of Kantian philosophy, a variant marked principally by thinking of representation as linguistic rather than mental, and of philosophy of language rather than "transcendental critique," or psychology, as the discipline which exhibits the "foundations of knowledge". This emphasis on language, I shall be arguing in chapters four and six, does not essentially change the Cartesian-Kantian problematic, and thus does not really give philosophy a new self-image. For analytic philosophy is still committed to the construction of a permanent, neutral framework for inquiry, and thus for all of culture.

— [Philosophy and the Mirror of Nature](/docs/phil/Philosophy and the Mirror of Nature.html),  Introduction