
---
title: Ed Witherspoon Argument
tags: 
  - philosophy 

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/ed witherspoon argument.yml
---
One can grant there is a *causal* dependence between brain activity and 
experience, but it is a leap to suggest that we can *identify* brain 
activity with experience. 

### Argument 1: Empirical thought experiment
The two come apart in the following thought experiment:

Suppose we found an incredible empirical correlation between brain 
activity and experience, such that a brain scanner technology exists which can 
determine one's experience from a brain state measurement. 

Now suppose one day we suddenly had a conflict (the brain 
scanner says that the subject *thinks* he's drinking coffee, but we see 
him eating ice cream and he assures us he thinks he is eating 
ice cream). In such a case, we would conclude the brain scanner is wrong, not 
the person. This demonstrates that, at least in cultures remotely similar to our 
own, conventional means of determining thoughts (e.g. first-person experiential 
reports, when subjects are not identified as hallucinating or having a reason 
to lie) have a *logically prior* status over any kind of scientific method.

### Argument 2: Conceptual analysis

What it *means* to be a thought is not the same thing as what it *means* to be a 
brain state.

- Brain states are connected by casual relationships. They, categorically, 
  cannot be 'correct' or 'incorrect', while thoughts can be.
- Mental states occupy the *space of reasons* - the meaning of certain 
  thought is identified by its relationships to other thoughts. Structured 
  by normative relationships (can be correct or incorrect).
- If a brain scanner with amazing correlation says that someone is telling a 
  lie by analyzing brain states, it may very well be that they are lying 100% of 
  the time that brain scanner says they're lying, but it is not the brain state 
  itself that makes them lying or not.