---
title: End of analytic philosophy
tags:
 - quote
---

[Author](/docs/phil/Richard Rorty.html)

> On the account of recent analytic philosophy which I offered in Philosophy and the Mirror of Nature, the history of that movement has been marked by a gradual "pragmaticisation" of the original tenets of logical positivism. I think that analytic philosophy culminates in Quine, the later Wittgenstein, Sellars, and Davidson-which is to say that it transcends and cancels itself. These thinkers successfully, and rightly, blur the positivist distinctions between the semantic and the pragmatic, the analytic and the synthetic, the linguistic and the empirical, theory and observation. Davidson's attack on the scheme/content distinction, in particular, summarises and synthesises Wittgenstein's mockery of his own Tractatus, Quine's criticisms of Carnap, and Sellars's attack on the empiricist "Myth of the Given." Davidson's holism and coherentism shows how language looks once we get rid of the central presupposition of Philosophy: that true sentences divide into an upper and lower division - the sentences which correspond to something and those which are "true" only by courtesy or convention.

— [Consequences of Pragmatism](/docs/phil/Consequences of Pragmatism.html), Introduction