---
title: Having a nature or a history
aliases: [Kant oder Hegel]
tags: 
  - distinction
  - STUB

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/having a nature or a history.yml
---

When introduced to a new concept, do you prefer to be given a definition for it 
in terms of other concepts, or do you prefer a story of how the word came to be 
used as it's used? Which kind of account is more enlightening? 

- "Electrons", "haploidism", and "sulfur" are popularly regarded to have a *nature*. These are the proper subject matter of the Naturwissenschaften.
- "Freedom", "skepticism", and "the right to vote" are popularly regarded to have a *history*. 
  These are the proper subject matter of the Geisteswissenshaften.

This can be applied to [philosophy itself](/docs/phil/Relation of philosophy to other disciplines.html) or major topics in philosophy (ethics,
philosophy the mind, epistemology, mereology). It is a meta-philosphical problem to establish what kind of account is satisfactory. This distinction underlies a fork in the road for new German graduate students in philosophy: Kant oder Hegel?

Put another way: Verstand (understanding) or Vernunft (reasoning)

[Rorty](/docs/phil/Richard Rorty.html)/[Hegel](/docs/phil/Georg Wilhelm Friedrich Hegel.html) can be thought of as making the meta-philosophical claim that the only (specifically) philosophical form of understanding is that of retrospective, reconstructive narratives.[^brand]

[^brand]: Brandom says one's sympathy to Rorty is directly proportional to the extent one does find stories over definitions satisfying.

