---
title: Life goals for a pragmatist
tags:
 - quote
---

[Author](/docs/phil/Richard Rorty.html)



> If you give up on the project of escaping from "human peculiarities and perspectives," then the important question will be about what sort of human being you want to become. If you accept the distinction between the public and the private realms which I draw in [Contingency, Irony, and Solidarity](/docs/phil/Contingency, Irony, and Solidarity.html), then this question will divide into two sub-questions. The first is: with what communities should you identify, of which should you think of yourself as a member? The second is (to adapt Whitehead's definition of religion): what should I do with my aloneness? The first is a question about your obligations to other human beings. The second is about your obligation to, in Nietzsche's words, become who you are.


— [Antirepresentationalism, Ethnocentrism, and Liberalism](/docs/phil/Antirepresentationalism, Ethnocentrism, and Liberalism.html)