---
title: Literature as successor subject to philosophy
tags:
 - quote 

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/literature as successor subject to philosophy.yml
---

[Author](/docs/phil/Richard Rorty.html)

> The principal legacy of metaphysical idealism is the ability of the literary culture to stand apart from science, to , to claim to embody what is most import for human beings. Kant's suggestion that using the vocabulary of Verstand, of science, was simply one of the good things human beings could do, was a first and absolutely crucial step in making a secular but non-scientific culture respectable. Hegel's inadvertent exemplification of what such a culture could offer—namely, the historical sense of the relativity of principles and vocabularies to a place and time, the romantic sense that everything can be changed by talking in new terms—was the second, no less necessary step. The romanticism which Hegel brought to philosophy reinforced the hope that literature might be the successor subject to philosophy—that what the philosophers had been seeking, the inmost secrets of the spirit, were to be discovered by the new literary genres which were emerging.

> There was, however, a third step in the process of establishing the autonomy and supremacy of . This was the step taken by Nietzsche and William James. Their contribution was to replace romanticism by pragmatism. Instead of saying that the discovery of vocabularies could bring hidden secrets to light, they said that new ways of speaking could help get us what we want. Instead of hinting that literature might succeed philosophy as discoverer of ultimate reality, they gave up the notion of truth as a correspondence to reality.... 
>  
> As Nietzsche said, they were the first generation not to believe that they had the truth. 


— [Nineteenth Century Idealism and Twentieth Century Textualism](/docs/phil/Nineteenth Century Idealism and Twentieth Century Textualism.html)