---
title: Maps
tags:
 - example

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/maps.yml
---

An example of [Leibniz's](/docs/phil/Gottfried Wilhelm Leibniz.html): consider a map of the United States. What is it that gives the map its [representational](/docs/phil/Representation.html) character? What makes it a map *of* something? This is related to the question of the difference between a [sign vs piece of wood](/docs/phil/Sign vs piece of wood.html).

Leibniz argues the representation comes from the fact that we can make inferences, based on map-facts, about facts about the world. (E.g. we can infer froma wavy-blue line between these dots means that one must cross a river to go from this city to that city).

We can use this to distinguish facts about the map and the genuine map-facts.

This example highlights the holistic character of representation: it is the homomorphism from the map (as a whole) onto the Earth's surface topology (as a whole) that gives meaning.

This example also highlights the lawfulness / subjunctive-robustness of representation: by taking it to be a map, we can say that, if the terrain *were* different, the map *would be* different.