---
title: Mind-body dualism
tags: 
 - concept
 - STUB

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/mind-body dualism.yml
---

A [dualism](/docs/phil/Dualisms.html).

[Descartes](/docs/phil/René Descartes.html) had invented [representation](/docs/phil/Representation.html) but came to think of things things in the world to be divided into representeds (things) and representings (ideas).

# Complaint about Cartesian dualism

- If you're committed to "mind stuff" being non-extended,
- and to the physical world being extended,
- (throw in some general claims about causation, e.g. it occurs in a place),
- then perception and agency become unintelligble. 
  - How is the mind affected by real stuff / how can the mind cause something?

# Cartesian minds as socially constructed
This is the thesis of *[Incorrigibility as the Mark of the Mental](/docs/phil/Incorrigibility as the mark of the mental.html)*. Cartesian minds
are something that we created because we started to treat each other a certain 
way.

The mind-body problem was a modern invention - the ancients did not struggle 
with it because they did not make Descartes' move of assimmilating "impressions"
and "thoughts" both as "ideas". 

# External resources
 - [SEP](https://plato.stanford.edu/entries/dualism/)