---
title: No independent test of accuracy of representation
tags:
 - quote
---

[Author](/docs/phil/Richard Rorty.html)


> Antirepresentationalists think this latter cluster dispensable because they see no way of formulating an *independent* test of accuracy of representation — of reference or correspondence to an "antecedently determinate" reality — no test distinct from the success which is supposedly explained by this accuracy. Representationalists offer us no way of deciding whether a certain linguistic item is usefully deployed because it stands in these relations, or whether its utility is due to some factors which have nothing to do with them — as the utility of a fulcrum or a thumb has nothing to do with its "representing" or "corresponding" to the weights lifted, or the objects manipulated, with its aid. So antirepresentationalists think "we use 'atom' as we do, and atomic physics works, because atoms are as they are" is no more enlightening than "opium puts people to sleep because of its dormitive power."

— [Antirepresentationalism, Ethnocentrism, and Liberalism](/docs/phil/Antirepresentationalism, Ethnocentrism, and Liberalism.html)