---
title: On community
tags:
 - quote

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/on community.yml
---

[Author](/docs/phil/Wilfrid Sellars.html)

> To say that a person desired to do A, thought it his duty to do B, but was 
forced to do C, is not to describe him as one might describe a scientific 
specimen. One does indeed describe him, but one does something more. And it's 
this 'something more' which is the irreducible core of the framework of persons. 

> In what does this 'something more' consist? To think of a featherless bird as a 
person is to think of it as a being with which  one is bound up in a network of 
duties. From this point of view, the irreducibility of the personal is the 
irreducibility of the *ought* or the *is*. But even more basic than this to 
think of a featherless biped as a person is to construe its behavior in terms of 
actual or potential membership in an embracing group, each member of which 
thinks of itself as a member of the group. Let's call such a group a *community*.

— [Philosophy and the Scientific Image of Man](/docs/phil/Philosophy and the Scientific Image of Man.html) Section VII

- Deep connection between the normative, the social, and the self-conscious.
