---
title: Pragmatism
tags:
 - school
 - STUB

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/pragmatism.yml
---

# Overview 
TODO 

# History

American pragmatism
- [Pierce](/docs/phil/people/Charles Sanders Pierce.html)
- [James](/docs/phil/people/William James.html)
- [Dewey](/docs/phil/people/John Dewey.html)

"Cambridge" pragmatism
- [Frank Ramsey](/docs/phil/people/Frank Ramsey.html)
- The later [Wittgenstein](/docs/phil/people/Ludwig Wittgenstein.html)

Neo-pragmatism
- [Rorty](/docs/phil/people/Richard Rorty.html)
- [Brandom](/docs/phil/people/Robert Brandom.html)
- [Price](/docs/phil/people/Huw Price.html)

## Graphical representation of influences

```{mermaid}
graph TD

H[G. W. F. Hegel] -.-> B[F. H. Bradley]

H -.-> P[C. S. Pierce]

H -.-> R[Josiah Royce]

H -.-> D[John Dewey]

  

B -.-> R

  

R -.-> D

R --> L{C. I. Lewis}

  

P -.-> J[William James]

P -.-> L

  

J --> L

  

L --> G[Nelson Goodman]

L --> Q[W. V. O. Quine]

L --> S{Wilfrid Sellars}

  

C{Rudolph Carnap} --> G

C --> Q

C -.-> S

  

Q --> DD[Donald Davidson]
```
Dotted lines are influence, solid lines are advisors, diamonds are neo-kantians.

# Semantics
What does it *mean* that "All $A$'s are necessarily $B$'s"? A pragmatist answer is that it is a license to infer statements like "$x$ is a $B$" from statements like "$x$ is an $A$".

## Truth 
- [Pierce](/docs/phil/people/Charles Sanders Pierce.html): [Truth as the limit of inquiry](/docs/phil/Truth as the limit of inquiry.html)
- James: Truth as what is good for belief[^bb]

[^bb]: [Blackburn](/docs/phil/people/Simon Blackburn.html): false beliefs can be useful, e.g. it may be useful to believe you are the most popular person in class but that does not make it true. Conversely, many things we think of as true are useless.


# External resources
- [SEP](https://plato.stanford.edu/entries/pragmatism/)