---
title: Representation regress
tags: 
 - regress
 - STUB

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/representation regress.yml
---

If any things are known [representationally](/docs/phil/Representation.html), then some things must be known nonrepresentationally (immediately, by being *had* or *grasped*).

- Otherwise we can't know about something via a representation $R$, because we'd 
  need another representation to know $R$.
- Representationalism gives rise to [choice](/docs/phil/Agrippan Trilemma.html) between [epistemological skepticism](/docs/phil/Epistemological skepticism.html) vs  foundationalism.


## Royce's argument from error
Brandom compares Descartes move to avoid this regress to Josiah Royce's 
argument which argues if even *mis*representation is to be possible, there 
must be some things we know immediately. See 
[SEP](https://plato.stanford.edu/entries/royce/#MetaEpisIdeaInte).

## Relation to semantic skepticism

What is the basis of our *knowledge* of the relation between representeds and 
representings? This is a question beyond knowing particular representeds.

We must have a representing $R$ (our concept of representation) 
of the relation of representings to representeds. 
But then we also need a representation $R^\prime$ of $R$, and so 
on.

This is something that the representational model itself couldn't address, and 
Descartes had to invoke God to address this. Kant clarified this as 
[semantic skepticism](/docs/phil/Semantic skepticism.html): skepticism about the intelligibility of the very notion of knowledge, the intelligibility of the notion of a representational relation between what's known and the 
knowing of it.