---
title: Representation
tags: 
 - concept 
 - STUB

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/representation.yml
---

Representation is a theory of the relation between appearance and reality. 

# A [successor concept](/docs/phil/Successor concept.html) to theories of resemblance
Premodern theories understood relation between appearance and reality in terms of **resemblance** (sharing properties).
  
- The paradigm example is that of a picture and what is pictured 
  - The appearance of the portrait is veridical to the extent that shape of the 
    ears, the color of the eyes, etc., match the person the portrait is of.
- The rise of science made this untenable:
    - Copernicus: reality behind stationary Earth and revolving Sun is a 
      revolving Earth and stationary Sun.
    - Galileo: effective strategies of understanding time as line lengths[^l] and 
      acceleration as triangles ... not easily understood in terms of shared 
      properties.

[^l]: It's hard for us to appreciate how radical this is given that the idea of 
      representation is so commonplace now. There is really nothing in terms of 
      directly-shared properties that would tie line lengths and time durations
      together. We think of Galileo as giving a mathematical *model* of what was 
      going on, but he thought of himself as using the language of geometry to 
      describe the underlying *reality* of the motion that we have appearances 
      of because he had no notion of representation. 

# Pioneered by Descartes 

[Descartes](/docs/phil/René Descartes.html) came up with the more abstract meta-concept (which Kant would dub representation, or *Vorstellung*) as a new way of thinking of the relation between appearance and reality.

[Spinoza](/docs/phil/Baruch Spinoza.html) saw Descartes' philosophy as being understood in terms of his innovations of relating algebra to geometry. How could strings of algebraic symbols be useful / veridical appearances of 
geometrical reality? 

- "[The order and connection of things is the same as the order and connection of ideas](/docs/phil/Order and connection of ideas.html)" 
    - A *global* homomorphism from the whole system of algebraic symbols and 
      the whole system of geometric figures.
    - The properties of what is representing or represented are irrelevant. 
      What's relevant is that there is the overall structure, the mapping 
      between the relations in each world.
 
# Empiricists and Rationalists

|       | [Empiricism](/docs/phil/Empiricism.html)  | [Rationalism](/docs/phil/Rationalism.html) |
| ----------------------------------- | -------------------------- |------------------------|
| Favored kind of representing[^dd]   | picture-like sensations    | sentence-like thoughts |
| The other kind of representation    | Fancy, abstract sensations | confused, indistinct thoughts | 
| Kant's terminology for the above    | impressions                | concepts     |
| Kind of representation[^prog]       | atomism                    | wholism[^whole]  |
| First, in order of explanation      | representational content   | inferential relations |
| Ontology problems[^sc]              | nothing-but-ism[^nb]       | ontological extravagance[^oe] |

[^dd]: Descartes did not make this distinction - his ontology simply had representings and representeds without finer structure. Empiricists tried to reduce thoughts to impressions and rationalists vice-versa.

[^whole]: Rationalist [Leibniz](/docs/phil/Gottfried Wilhelm Leibniz.html) would have us understand the content of the map (*as* a representation) to be the inferences that someone who treats it as a map could make about terrain facts (e.g. a river) from map-facts (wavy-blue line).

[^nb]: Empiricists start with narrow postulate about what representing is and exclude a lot of genuinely contentful thought due to not meeting this standard (e.g. ethics, modality)

[^sc]: Sellars identifies both camps as [descriptivists](/docs/phil/Descriptivism.html) (to be conceptually contentful is just to describe / represent how things are).

[^oe]: Rationalists take all our cognitively contentful expressions as describing the actual world, resulting in ontological extravagance (postulating objective values / universals / propositions / laws).

[^prog]: Empiricists did not take the wholist lesson of representation to heart, so they were reactionary / holding onto the atomistic aspect of the antiquated resemblence model.

Kant saw Descartes as having made an advance by assimilating impressions and  concepts as species under the genus of representation. But these categorically-different species play different roles in our capacity to know things (rather than being the same species but having a spectrum).

# External resources
- [SEP](https://plato.stanford.edu/entries/mental-representation/)