---
title: Representationalism and physics
tags:
 - quote
---

[Author](/docs/phil/Richard Rorty.html)

> Lewis thus builds representationalism into the "face value" of physics. '4 This is characteristic of representationalists who are realists rather than skeptics. For they see physics as the area of culture where nonhuman reality, as opposed to human social practices, most obviously gets its innings. The representationalist believes, in [Williams](/docs/phil/Bernard Williams.html)'s [words](/docs/phil/Absolute conception of the world.html), that "we can select among our beliefs and features of wourld picture some that we can reasonably claim to represent the world in a way to the maximum degree independent of our perspective and its peculiarities". By contrast, antirepresentationalists see no sense in which physics is more independent of our human peculiarities than astrology or literary criticism.

— [Antirepresentationalism, Ethnocentrism, and Liberalism](/docs/phil/Antirepresentationalism, Ethnocentrism, and Liberalism.html)