---
title: Rules are lived
tags:
 - quote

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/rules are lived.yml
---

[Author](/docs/phil/Wilfrid Sellars.html)

> A rule, properly speaking, isn't a rule unless it lives in behavior,
rule-regulated behavior. Even rule-violating behavior. Linguistically we always
operate within a framework of living rules. To talk *about* rules is to
move outside the talked about rules into another framework of living rules. The
snake which sheds its skin lives within another. In attempting to grasp rules as
rules from without, we are trying to have our cake and eat it. To describe rules
is to describe the skeletons of rules. The rule is lived, not described. 

— [Language, Rules and Behavior](/docs/phil/Language, Rules and Behavior.html)

- You can't be inside the rules and talking about the rules at the same time.
- The last two sentences are exemplified in the [What the Tortoise said to Achilles](/docs/phil/What the Tortoise said to Achilles.html) story.
- He is developing a notion of pragmatic metalanguages and trying to understand 
  their relationship to object languages.