---
title: Semantics
tags: 
 - concept 
 - STUB
description: the theory of the *meaning* or *content* of expressions

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/semantics.yml
---

## [Empiricism](/docs/phil/Empiricism.html)
An empiricist approach to semantics wants to give semantics of an expression 
in terms of its [sense dependence rather than its reference dependence](/docs/phil/interaction/Sense dependence vs reference.html).

## [Functionalism](/docs/phil/Functionalism.html)
The meaning of a word is the role it plays in inferential reason relations.

## [Descriptivism](/docs/phil/Descriptivism.html)
...

## Crude causal theory
See [Jerry Fodor](/docs/phil/people/Jerry Fodor.html).

## [Teleosemantics](/docs/phil/Teleosemantics.html)
...

## [Semantic Nominalism](/docs/phil/Semantic nominalism.html)
...

## Semantic nihilism

[Wittgenstein](/docs/phil/people/Ludwig Wittgenstein.html) is interpreted by [Dummett](/docs/phil/people/Michael Dummett.html) to be a semantic nihilist: i.e. he doesn't think there are actually meanings. The plasticity of language makes this impossible, as it is fundamentally at odds with codifying the properities of use (at best it could just give you a snapshot).

## Nominalistic representationalism
This is how Brandom characterizes de Saussure, Derrida, semiotics, textualists: they take the name-bearer relationship as the paradigm model of semantics. This is described as not taking into account the advances of Kant/Frege/Wittgenstein that show the primacy of sentences/judgments in the order of explanationl, prior to names.