---
title: Semantics and epistemology
tags:
 - concept

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/semantics and epistemology.yml
---

The relationship between [semantics](/docs/phil/Semantics.html) and [epistemology](/docs/phil/Epistemology.html) is a contentious issue.

[Fodor](/docs/phil/Jerry Fodor.html) argues they should be kept separate, while [Rorty](/docs/phil/Richard Rorty.html) argues in [PMN](/docs/phil/Philosophy and the Mirror of Nature.html) that [Sellars](/docs/phil/Wilfrid Sellars.html) and [Quine](/docs/phil/W.O. Quine.html) independently demonstrated their inseparabiliity. 

Labor cannot be divided between theory of content and theory of knowledge / understanding: both crucially depend on inferential relations.

This is tantamount to whether one's theory of meaning is independent of one's theory of understanding. For example, [Davidson](/docs/phil/Donald Davidson.html) argues that we can only understand meaning in terms of the process of interpreting (attributing meanings). For [Dummett](/docs/phil/Michael Dummett.html), meaning is what can be understood.

# Order of explanation
What is the proper order of explanation? [^1]
- Should reason-relations (material implication and exclusion) be determined by representational content?
- Should we understand content [functionally](/docs/phil/Functionalism.html), in terms of reason relations?

[^1]: There is a related order-of-explanation dilemma between [Semantics and pragmatics](/docs/phil/Semantics and pragmatics.html).



# Related topics
- [Breaking the analytic-synthetic distinction](/docs/phil/Analytic and synthetic facts.html#Breaking the distinction)