---
title: Sense dependence vs reference
tags: 
 - distinction
 - YELLOW

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/sense dependence vs reference.yml
---

Two meanings of "$X$ depends on $Y$" that are easily conflated.

| Kind of reference      | Sense | Reference |
| ----------- | ----------- |-----------|
| Meaning of $X$ depends on $Y$      | you can't *understand* $X$ unless you *understand* $Y$       | you can't have $X$ existing without $Y$ existing |
| Flavor of dependence   | Epistemological        | Ontological |

[Robert Brandom](/docs/phil/Robert Brandom.html) points out that we can have sense dependence without having reference dependence.

An example is a toy concept of beauty: "$X$ is beautiful if looking at it elicits pleasure in people."

 - This is asserting a *sense* dependence of beauty on people, but not a 
   *reference* dependence.
 - It is intelligible that there could exist beautiful sunsets before there ever 
   were people in the world, or if people never existed.

# Historical relevance

This is the difference between Berkeley's idealism and Kant's trancendental idealism. When someone claims the lawfulness of a relation between two properties is a feature of our cognitive faculties, it makes a big difference whether this is a sense or reference dependence claim.
- Without understanding what it is for you to follow a rule / to infer $B$ from $A$, you can't *understand* the lawfulness that you're taking the world to have.
- This does not entail a reference dependence.