---
title: Textualists and language relativity
tags:
 - quote 

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/textualists and language relativity.yml
---

[Author](/docs/phil/Richard Rorty.html)

> Idealists started off from Berkeley's claim that nothing can be like an idea except another idea. The textualists start off from the claim that all problems, topics, and distinctions are language-relative - the results of our having chosen to use a certain vocabulary, to play a certain [language game](/docs/phil/Language game.html).
> 
> In textualist terms, this becomes the claim that the vocabulary of science is merely one among others - merely the vocabulary which happens to be handy in predicting and controlling nature. It is not, as physicalism would have us think, Nature's Own Vocabulary.

— [Nineteenth Century Idealism and Twentieth Century Textualism](/docs/phil/Nineteenth Century Idealism and Twentieth Century Textualism.html)