---
title: Textualism as thorough-going pragmatism
tags:
 - quote 
---

[Author](/docs/phil/Richard Rorty.html)

> This [replacement](/docs/phil/Literature as successor subject to philosophy.html) of romanticism by pragmatism within philosophy was paralleled by a change in the literary culture's self-conception. The great of that culture in our century—the great "modernists," if you like—have tried to show what our lives might be like if we had no hope of what Nietzsche called "metaphysical comfort."  
> 
> The movement I am calling "textualism" stands to pragmatism and to this body of literature as the nineteenth-century attempt to make literature a discoverer of ultimate truth stood to metaphysical idealism and to Romantic poetry. I think we shall best understand the role of textualism within our culture if we see it as an attempt to think through a thorough-going pragmatism, a thorough-going abandonment of the notion of discovering the truth which is common to theology and to science.

— [Nineteenth Century Idealism and Twentieth Century Textualism](/docs/phil/Nineteenth Century Idealism and Twentieth Century Textualism.html)