---
title: The Frege-Geach problem
tags: 
 - concept
 - problem
 - RED

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/the frege-geach problem.yml
---

A problem for people who subscribe to [emotivism](/docs/phil/Emotivism.html). Sets a critirion of adequacy for them.

Also sometimes called the *embedding problem*.

Theories in the noncognitivist tradition share the view that the distinctive 
meaning of moral words does not concern what they are about, and it either does 
not require or is not exhausted by any answer to what makes moral sentences true. 
For example, according to A. J. Ayer, the word 'wrong' works more like 'dammit' 
than like 'common', so that 'stealing money is wrong' means something more like, 
'dammit, stealing money!' than like 'stealing money is common'. 

But standard ways of understanding the meanings of complex sentences, and of understanding 
the logical relationships between sentences, depend on an answer to what those 
sentences are about, or what would make them true. 


- Intuition: the question of truth can be raised for whatever is expressed by 
  declarative sentences.
-  E.g. "If X is good, then ..." a hallmark of 
  fact-stating (if we had "dammit!" or "praise god!", it wouldn't make 
  grammatical sense).
  - We can embed moral statements that 1st wave expressivists said were not 
    fact-stating.
  - QUESTION: are there any grammatically declarative sentences which cannot 
    be embedded? Would a counterexample have to be a non-truth-apt, 

So noncognitivists need a different, nonstandard, answer to how the meanings of simple sentences give rise to the meanings of complex sentences. The problem of how to do so, and of
whether it can even be done, has come to be known as the Frege-Geach problem.
