---
title: The scientific and the ethical
tags:
 - quote
---

[Author](/docs/phil/Bernard Williams.html)

> The basic idea behind the distinction between the scientific and the ethical, expressed in terms of convergence, is very simple. In a scientific inquiry there should ideally be convergence on an answer, where the best explanation of the convergence involves the idea that the answer represents how things are; in the area of the ethical, at least at a high level of generality, there is no such coherent hope. The distinction does not turn on any difference in whether convergence will actually occur, and it is important that this is not what the argument is about. The point of the contrast is that, even if this happens, it will not be correct to think it has come about because convergence has been guided by how things actually are, whereas convergence in the sciences might be explained in that way if it does happen.
> 

— [Ethics and the Limits of Philosophy](/docs/phil/Ethics and the Limits of Philosophy.html)
