---
title: Transposed language of norms
tags:
 - quote

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../ejs/custom.ejs"
  contents:
    - ../../backlinks/transposed language of norms.yml
---

[Author](/docs/phil/Wilfrid Sellars.html)

>	The language of modalities is … a “transposed” language of norms. ...
   Modal terms, normative terms and psychological terms are mutually irreducible.
   ... The “means” of semantical statements...is no more a psychological word
   than is the “ought” of ethical statements or the “must” of modal
   statements 
   
— [Inference and Meaning](/docs/phil/Inference and Meaning.html) Section 5

- Related to [this quote](/docs/phil/Describing without modality.html).
- What is the connection between the ([alethic](/docs/phil/Alethic modality.html)) modal sense of *must* and the normative sense of *must*?
- [Carnap](/docs/phil/Rudolf Carnap.html) uses 'transposed' to talk about an unquoted word used in a sentence as a
  transposed mode of speech (about use of a quoted-word).
  - Examples:
    - "Red is a quality." vs  "'Red' is a one-place predicate."
    - "All $A$'s are necessarily $B$'s". vs the license to infer $B$ statements 
      from $A$ statements.
