project:
  type: website
  output-dir: _site

website:
  title: "KB"
  site-url: https://www.krisb.org
  repo-url: https://github.com/kris-brown/kbquarto
  repo-branch: master
  repo-actions: []
  open-graph: true
  twitter-card: true
  page-navigation: true
  reader-mode: true

  navbar:
    background: light
    logo: images/home.png
    title: false
    collapse-below: lg
    left:
      - docs/research.qmd
      - docs/contact.qmd
      - docs/personal/index.qmd
      - docs/notes.qmd
      - docs/blog/index.qmd
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
            href: "https://github.com/kris-brown/kbquarto/issues"
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ksb_id
        aria-label: KSB Twitter
      - icon: github
        href: https://github.com/kris-brown
        aria-label: KSB GitHub
      - icon: file-earmark-person
        href: docs/research.qmd#cv
        aria-label: KSB CV

  sidebar:
    - id: phil
      title: "Philosophy notes"
      style: "floating"
      collapse-level: 1
      align: left
      contents: docs/phil

    - id: math
      title: "Math notes"
      style: "floating"
      collapse-level: 1
      align: left
      contents: docs/math

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: darkly
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/include-files.lua
  - filters/tikz-to-png.lua
  - quarto

freeze: auto

date: last-modified
date-format: short
title-block-published: "Updated"
title-block-categories: true
editor: visual

comments:
  utterances:
    repo: kris-brown/kbquarto

html-math-method:
  method: mathjax
  url: "es5/tex-mml-chtml.js"

resources:
  - es5
  