# About me {#sec-about}

## Contact

I can be reached via many emails:

- kristopher.brown (ufl.edu)
- ksb (stanford.edu)
- kristopher.stephen.brown (gmail.com)
- sirkris.brown (gmail.com)
  - (it's a palindrome)

Also on [Github](https://github.com/kris-brown/), [LinkedIn](https://www.linkedin.com/in/kristophersbrown/), [Youtube](https://www.youtube.com/channel/UCsS3Vyi48g-vOyG0emREmUg), or [Twitter](https://twitter.com/ksb_id).

## Research
### Current
I work with a [team](https://www.algebraicjulia.org/) developing applied category theory software in Julia. The primary application here is building tools that make scientific computing and scientific knowledge representation easier, more transparent, and more robust to updating one's model of the world. For an overview, see my talk [Combinatorial Representations of Scientific Knowledge](https://www.youtube.com/watch?v=vJRAw8USmYs).

#### Model enumeration
 [code](https://github.com/kris-brown/ModelEnumeration.jl)

#### C-set automorphisms
As described in this [blog post](https://www.algebraicjulia.org/blog/post/2022/01/cset-automorphisms/), this project concerns extending McKay's graph algorithm (implemented as [nauty](https://pallini.di.uniroma1.it/)) to C-sets, so that isomorphic instances can be immediately seen to be equal. ([code](https://github.com/AlgebraicJulia/CSetAutomorphisms.jl))

#### Model Exploration
- [Model exploration](https://github.com/kris-brown/ModelExploration.jl)

#### Model inference
- [Graph rewriting](https://arxiv.org/abs/2111.03784) ([demo](https://nbviewer.org/github/kris-brown/Computational-Category-Theoretic-Rewriting/blob/main/Computational_Category_Theoretic_Rewriting.ipynb))
  - Related application with [Sean Wu](https://slwu89.github.io/): [individual-based stochastic models for epidemiology](https://github.com/slwu89/IndividualRewrite)


- [Computation and theorem proving with string diagrams](https://github.com/AlgebraicJulia/GraphicalLinearAlgebra).


When we update our view of the world, it's important to be able to migrate our old data, algorithms, and analysis tools into the new framework. When these tools are expressed in the language of C-sets, this migration can be automated in a verifiable way: [Categorical data integration for computational science
](https://www.sciencedirect.com/science/article/pii/S0927025619302046) (furthermore, as stressed in the paper, these migration tools are of importance to scientists who wish to communicate and share data with lower risk of data misinterpretation).

### Past
#### Knowledge representation and data integration

##### Declarative specification of databases
Scientists modeling complicated phenomena don't use explicit (formally-specified) models. This is pragmatic, given current available open-source tools, but informal reasoning ulimately leads to serious challenges in communicating scientific results clearly and sharing data. A relational database backend is important for a scalable modeling tool, but a SQL-less interface is also crucial: the complexity of managing database implementation details quickly becomes unmanagable and unextensible as the model complexity increases. I developed a Python EDSL to help scientists generate relational databases from a natural declaration of scientific facts and to naturally query and publicly communicate their knowledge base. It is commercialized [here](https://www.modelyst.com/).

##### Heterogenous data integration, using Category Theory

There is little standardization in how data is to be represented and stored in many scientific fields. However, the varying schemas of different researchers contain significant overlap in information, and for data-driven fields it is especially beneficial to be able to freely switch from one frame of reference to another. Categorical Query Language, a tool developed by Conexus AI, allows for specification of data migration and integration in a declarative and clean process. I showed the utility of this approach in the field of computational chemistry in this [paper](https://arxiv.org/pdf/1903.10579.pdf), in collaboration with Ryan Wisnesky and David Spivak.


#### Development of functionals for Density Functional Theory

As described [here](http://www.slac.stanford.edu/~vossj/project/xc-functionals/),  the simulation of chemical reactions using first-principles techniques requires a theoretical framework that is able to describe a wide range of electronic interactions. Under the direction of Johannes Voss, I develop new meta exchange-correlation functionals with a semi-empirical approach, fitting the functional form against higher level of theory and experimental benchmark data. By using Bayesian statistics, we enable uncertainty estimation of the computed reaction energies.

## Personal
A non-exhaustive list of hobbies (past an present):

  - I sometimes write music. [Here](https://www.youtube.com/embed/EjZH9OW6eA0)'s an example.
  - I sometimes write puzzles. [Here](https://2021.huntinality.com/puzzle/wahshington_post.html)'s an example.
  - I do [fashion](https://dartmouthfashioncouncildotcom.wordpress.com/2014/05/06/street-style-ft-kris-brown-14/).
  - I like (some) books.
  - I like (some) board games.
  - I like (some) video games.
  - I like (most) cats.
