---
title: "03: Language as thought and different species of ought"
categories: 🔴
date: September 16, 2009
---

# Language as thought and communication

Sellars wants to give us a naturalistic account of intentionality.

Logical behaviorism / philosophical behaviorism

Def: the view that one can analyze without remainder intentional vocabulary / 
intentional concepts into purely behavior characterizations / dispositions to 
publicly observable behavior (specified in a non-intentional vocabulary).

Introduced in *Empiricism in the Philosophy of Mind* (9 years earlier), distinct 
from what he here calls logical behaviorism. *Logical behaviorism* refers to a 
view he attributes to Ryle. JB Watson and BF Skinner promoted this in psychology. 
Sellars never endorsed this because he saw this as being an application of 
[instrumentalism](instrumentalism.qmd) in the philosophy of science.

Observable things, at least we know they exist. Theoretical things, we've got to 
make risky inferences to get to them. But we can also make observational 
mistakes. Not just "I thought it was a fox but it was a dog", but categorical 
observational mistakes. We can give some concept an observational role (e.g. 
declare that we can observe X's) yet no X's exist, i.e. no thing has such no 
thing with such circumstances of application and consequences of application. 
E.g. we can have a theory of acids. "Anything that's sour is an acid. And 
anything that's an acid will turn litmus paper red." Well, then we have 
observational access to acids. If we eventually find something that tastes sour 
that turns litmus paper blue, then it turns out there are no acids, even though 
we could observe them (or: had every reason to believe we could). Likewise: 
being a witch was observable (even though there are no such things).

_The Plasticity of Mind_ is about bad theories incorporating observational 
practices, i.e. "What do you mean there are no K's. I can *see* K's, there's one 
right there!"

So again, this is a response to someone saying we can distinguish theoretical 
from observable entities by pointing to the fact that we can make mistakes about 
whole categories of theoretical entities. Furthermore, 
[Pluto](/docs/phil/situations/pluto.qmd) is a great counterexample for this 
distinction.


Just because our evidence for attributing mental states comes from behavior does 
not mean, unless you are an instrumentalist, that you have to be able to define 
intentional concepts in terms of behavior. (This doesn't mean that the intentional 
states are less real, just that we aren't in a position to observe anything but 
the behavior)

##  Digressions
1. *Semantics* is a field with instrumentalist vs theoretical realist views. 
[Michael Dummett](/docs/phil/people/dummett/index.qmd) is an instrumentalist 
by observing the fact that meaning something 
is only understood through verbal behavior and concluding that any theory of 
meaning must be definable in terms of behavior.
    - (A theoretical realist might postulate meanings as theoretical entities to 
      explain verbal behavior and say our access to meanings is inferential and, 
      if they are good theories, then verbal behavior gives us inferential 
      access to something (meanings) that exist.)
2. [MacDowell](/docs/phil/people/macdowell/index.qmd) and Sellars agree 
   (and disagree with almost all others) that what 
   you hear when someone talks to you is the words themselves, rather than 
   hearing noises and (by some inferential process) constructing the words. 
   You have to actually actively do some work to hear that mere noises. This is 
   evidenced by how difficult it was to tell computers how to recognize a smile 
   in a picture.
    - (Some say it's a contradiction to say that meanings are essentially 
      normative yet, on the other hand, we sometimes can directly perceive them. 
      But there's nothing in principle unobservable about normative states of 
      affairs - see Sellars' criteria of observation below)


(Controversial) Criteria for observation:
1. You have the capacity to reliably and differentially respond to some 
   normative state of affairs
2. You have to have the concept and which is a matter of inferential 
   articulation and practical mastery of inferential proprieties, involving it. 
   And then if you can hook the one up to the other, you've turned what was 
   beforehand a theoretical concept for you into into the concept of an 
   observable/

Sellars wants to make sense of the notion of "language as a rule-governed 
enterprise" (as essentially involving norms). Sellars believes that if your 
account language doesn't involven norms, you will be describing the vehicles by 
which we communicate, rather than what we're saying/meaning.

Reminder that, due to the [regress argument](/docs/phil/problems/ruleregress.qmd), 
that we need to broaden our notion of 'rule' from just explicit rules and need 
think of rules also as implicit in what we do. Sellars wants to better 
understand the relationship between implicit practical abilities and explicit
representations of rules.

The question of whether meaning is a normative concept was brought to 
philosophical attention by 
[Kripkenstein](/docs/phil/people/kripke/works/kripkenstein/index.qmd). In present 
literature, Hattiangadi and Katherin Glüer have pushed back upon the idea that 
it is a normative concept, advanced by Brandom and MacDowell. Brandom feels it 
is because they haven't learned lessons from Sellars, in particular thinking of
 norms purely in terms of explicit presecriptions and not making the distinction 
 between ought-to-be's and ought-to-do's.

> You can define *possibility* in terms of *not* and *necessity*. You can define 
*necessity* in terms of *not* and *possibility*. I think it's the beginning of 
wisdom to think of defining *not* in terms of the relationship between 
*possibility* and *necessity*, but I'm the only human being who thinks that.

[Grice](/docs/phil/people/grice/index.qmd) on non-natural meaning: reduces what 
a linguistic expression $P$ means in 
terms of the meanings of thoughts and beliefs of those uttering $P$. Sellars 
isn't satisfied with this: the puzzling phenomena of meaning are common to both 
thought and language.

Sellars says "ought-to-be's imply ought-to-do's" but is not exact about what 
quantifier: all or some? Brandom thinks 'some' makes more sense, since there 
could be an ought-to-be requiring a state of affairs to change without telling 
us who has to do what to fix it (you need auxillary hypotheses to turn it into 
an ought-to-do). E.g. "all clocks should be in sync".

With a trainer, someone with concepts/rules can condition language learners to 
shape their behavior (teach them ought-to-be's). It's important that it's 
possible for the language enterprise get off the ground (i.e. without trainers). 
It's possible for some sort of selection process to naturally reinforce
ought-to-be's (can be social but the conditioners need not be doing so intentionally).

We can deliberate making a distinction between ought-to-be's in the context of 
humans vs nonliving/nonsentient beings (e.g. "plants ought to get enough water").
[Ruth Millikan](/docs/phil/people/millikan/index.qmd)'s work relevant. 
Connects to the [Aristotelian](/docs/phil/people/aristotle/index.qmd) account.

Consider ought to be's in the context of training animals: These rats ought to 
be in state $\phi$ whenever $\psi$.

- Could be just for rats, qua rats
- they ought to be eating when they're hungry, or something like that
- this could be something we want the rats to do
  - when they come to a branch in a maze, the rats go to the side that's painted 
    blue and not to the side that's painted red.
  - That's a regularity that ought to be not because we can read it off of the 
    fundamental teleology of rats
  - The conformity of the rats in question to this rule does *not* require that 
    they have a *concept* $C$, e.g. of colors blue and red. We just require them 
    to respond properly certain to differences emanating from $C$. This doesn't 
    require even consciousness (photocells can respond differentially to colors).


"Recognitional capacity" gets systematically used in two fundamentally different 
senses (an 'accordion word')

- reliable, differential response
- applying a concept


Important for Sellars that following an ought-to-be requires only the former 
sense.

We should talk about learning a language as 'coming into the language' rather 
than 'learning a language'. It's more like the way one comes into a city. You 
come to be able to take part in an ongoing practice, as opposed to getting some 
intellectual insight.

Teaching the very young child to say 'purple' when showing her a purple lolipop 
is getting her to follow an ought-to-be just like the rat example. There is an 
ought-to-do for teachers of a language that they see to it that children produce 
the appropriate responses. This presupposes that the teachers do have a 
conceptual framework of 'purple' and of 'vocalize' and what it is for an action 
to be called by a circumstance. The learner is not required to have any of these 
concepts. The ought-to-be is explicit in the teacher's mind.


# [Instrumentalism](instrumentalism.qmd)
{{< include _instrumentalism.md >}}

# Ought to be and ought to do

See distinction [here](/docs/phil/distinctions/made/ought_to_be.qmd)

# Sense vs reference dependence

See distinction [here](/docs/phil/distinctions/made/sense_dependence_reference.qmd)

# Romantic views of language
People with romantic views of language: [Derrida](/docs/phil/people/derrida/index.qmd) 
and [Nietzsche](/docs/phil/people/nietzsche/index.qmd). These are compatible 
with Wittgenstein [believing language has no downtown](/docs/phil/people/wittgenstein/index.qmd#downtown).

Sellars disagrees: the language-language inferential transitions are of the 
first importance among those because what makes the entries and exits 
*language* entries and exits is the way they connect to the inferential moves. 
And so he would say to Derrida, "yes, we do all of these other wonderful things 
with the language, but that's all parasitic on the meanings that things are 
given because of the role they play in the space of reasons... now, once you've 
got that up and running, once you've got those meanings to work with, now you 
can start to do other playful things with it, e.g. use them metaphorically. All
sorts of things become possible. But that's in principle a superstructure on 
this structure."

# Transition
Sellars story of how 'the light dawns slowly over the whole'.

Both the infant and [Koko](https://en.wikipedia.org/wiki/Koko_(gorilla)) the 
gorilla can be trained into a language (in the form of conforming to 
ought-to-be's). At some point the human makes a jump - they have the concept and 
can be a trainer of others. What's the nature of that jump?

For Sellars, this is a change in *normative status*, not a lightbulb that went 
off in one's head. Like the change on your 21st birthday, when suddenly doing 
the very same thing, making the same pen scratches that you could have made the 
day before, would *not* be obliging yourself to pay the bank a certain amount of 
money every every month for the next 30 years. But after your 21st birthday, 
when you scratch your pen in exactly the same (physically descriptively, 
matter-of-factually) way, all of a sudden it has a hugely different normative
significance because now you will be held responsible. You'll be taken to have
undertaken commitment in a way in which you were not eligible to undertake that 
commitment by doing the very same thing descriptively, the day before.

When you get good enough at the language game moves, you do get acknowledged by 
the community. We don't characterize this physically-descriptively because we're 
not describing someone / some matter-of-factual boundary that has been crossed. 
We're not describing the child, we're placing the child in the space of reasons.

It's the difference between the one and a half year old, who toddles in to the 
living room. And as her first full sentence says, "Daddy, the house is on fire." 
Well, one doesn't think that she has claimed that the house is on fire. She's 
managed to put these words together, this is good. If the four year old comes 
into the living room and says "Daddy, the house was on fire", you hold her 
responsible, you say "How do you know? Did you smell smoke? And you know, what 
should we be doing? What follows if the house is on fire? What should we be 
doing?" You take her to have claimed this to have undertaken a commitment and 
you hold her responsible for it. The difference is not some light that's going 
on. It's a difference in normative status, ultimately a difference in 
[social status](/docs/phil/people/brandom/index.qmd#sapience).

This is the difference between just conforming to the pattern, and actually 
making claims. The radically anti-Cartesian aspect of Sellars is that this is 
also the the difference between conforming to the pattern and *having thoughts 
at all*.

However, as Dennett points out: you can treat any even inanimate object as an 
intentional system, e.g. this table as having the one desire that remain at the 
center of the universe. And the one belief that it is currently at the center 
of the universe, which is why it resists us moving it. (by extension, we treat 
our cats and dogs this way). So we should only treat things as thinking if we 
have to. Brandom takes an opposite view, that you should always treat something 
as talking if you can (note this is a 
[very high bar](/docs/phil/situations/novelsentence.qmd)).

The period prior to the child's mastery and social status as a language speaker 
has some peculiarities. His verbal behavior would express his thoughts but, to 
put it paradoxically, the child could not express them. The child isn't in a 
position to *intentionally* say that things are thus-and-so, even though it is 
in a position to say that things are thus-and-so. So there's a question: which 
comes first, speaker's meaning or semantic meaning?

Semantic meaning is a matter of what the words mean. No agent involved in that. 
In English, the word 'molybdenum' means the noble metal with 42 protons. 
Contrast with "When Humpty Dumpty says 'glory', he means *a nice knockdown, 
drag-out fight*". Grice says speaker meaning comes first. Sellars says that is a 
Cartesian way of thinking about things, that the primary meaning is what words 
mean in the language process.

If I claim the notebook is made out of copper, I have (whether I know it or 
not), committed it to melting at 1084 °C and that it conducts electricity. 
My words mean those things, whether or not I mean to.

The kid produces vocal (not yet verbal) noises until he is a member of the 
language community (his verbal noises conform to enough ought-to-be's).

As soon as he can say something, that's the expression of a thought. To take 
him to be saying is to be taking him to be thinking out loud. It's a further 
stage, when he can take expressing that thought as the object of an intention, 
and intentionally do as an action that say, before that, that's just an act, 
it's a performance, he can reliably produce appropriately, but not yet 
intentionally produce. An adult could be in this situation: 
[Auction example](/docs/phil/situations/auction.qmd). That's the sort of 
position that the kid (who's just crossed the line into being able to say 
something) is: she can produce a vocalization that will hold her responsible 
for, and which, accordingly, we take to express a thought. But she doesn't yet 
have the *concept*. So, she can have the concept of its being red or the house 
being on fire. But not yet, the concept of *endorsing something*, or of making 
a claim that he's saying can be a later development. And you need *that* concept 
in order to *intend* to be making a claim.

Important to make distinctions between different types of saying:

- mere utterance (position of 1 year old)
- saying that things are thus-and-so
    - having mastered the entries/exits/language-language moves, but no 
      metalinguistic concepts
    - Could be called "merely thinking out loud"
    - Can perform speech *acts*.
    - Can express that something is read or even a desire for something 
      ("I'm taking that")
- intentionally saying (*telling* someone) that things are thus-and-so
    - need concepts of asserting/believing as well as concepts of thus-and-so
    - Can perform speech *actions*.
    - Self consciousness.

We need to think of the child as being able to give evidence without the 
concept of evidence. This is important in the story of how the language game 
gets off the ground with the early hominids. But we have real experience with 
this: when teaching logic, it's helpful to teach students to have the practical
mastery of writing proofs (prior to them having the concept of a proof). They
first get familiar with the symbol pushing game. (proof is a strong form of 
evidence). This is very common in mathematics education.
