---
title: Can we build it?
listing:
  id: backlinks
  type: table
  filter-ui: true
  template: "../../../../ejs/custom.ejs"
  contents:
    - ../../../../backlinks/docs_math_sketches_4_1.yml
---

- A large project is broken down into subprojects, each of which can be broken down into further subprojects.
- Each subproject provides resources (or 'functionalities') but also requires resources.
- There are interdependencies; if subteam A needs more space in order to provide a resource for B, B may need to use less space, causing a ripple effect.
- Codesign diagrams have wires which represent a [preorder](../1/3.qmd#preorder) of resources.
        - Boxes correspond to feasibility relations, which match resource production with requirements
        - For every pair (p,r), where $P$ is the [preorder](../1/3.qmd#preorder) of resources to be produced and $R$ is the [preorder](../1/3.qmd#preorder) of resources to be required, the box says true or false for that pair.
        - I.e. "yes I can provide $p$ given $r$" or "No, I cannot provide $p$ given $r$"
        - I.e. Feasibility relations define a function $P \times  R \xrightarrow{\Phi}\mathbb{B}$ subject to some conditions
- A co-design problem, represented by a co-design diagram, asks us to find the composite of some feasibility relations.

<p align="center">
\begin{tikzpicture}
  \begin{pgfonlayer}{nodelayer}
    \node [style=0.75x1] (0) at (-2.75, 1) {Chassis};
    \node [style=0.75x1] (1) at (1.5, 1) {Motor};
    \node [style=0.75x1] (2) at (5.75, 1) {Battery};
    \node [style=0.75x1] (3) at (-6, 2.5) {$\Sigma$};
    \node [style=0.75x1] (4) at (8.25, -1) {$\Sigma$};
    \node [     ] (5) at (-5.5, 2.5) {};
    \node [     ] (6) at (10, -1) {};
    \node [     ] (7) at (7, 0.75) {};
    \node [     ] (8) at (7, 1.5) {};
    \node [     ] (9) at (2.5, 0.25) {};
    \node [     ] (10) at (2.5, 0.75) {};
    \node [     ] (11) at (2.5, 1.25) {};
    \node [     ] (12) at (2.5, 1.75) {};
    \node [     ] (13) at (-1.5, 0.25) {};
    \node [     ] (14) at (-1.5, 1) {};
    \node [     ] (15) at (-1.5, 1.75) {};
    \node [     ] (16) at (0.5, 1) {};
    \node [     ] (17) at (0.5, 1.75) {};
    \node [     ] (18) at (-4, 1.75) {};
    \node [     ] (19) at (-4, 0.75) {};
    \node [     ] (20) at (-6.5, 2.5) {};
    \node [     ] (21) at (-6.5, 3) {};
    \node [     ] (22) at (-6.5, 2.25) {};
    \node [     ] (23) at (-10, 2.25) {};
    \node [     ] (24) at (-10, 0.75) {};
    \node [     ] (25) at (7.75, -0.5) {};
    \node [     ] (26) at (7.75, -1) {};
    \node [     ] (27) at (7.75, -1.5) {};
    \node [     ] (28) at (8.75, -1) {};
    \node [     ] (29) at (4.5, 1.25) {};
    \node [     ] (30) at (4.5, 0.75) {};
    \node [     ] (31) at (-7.25, 4) {};
    \node [     ] (32) at (-7.25, 5.25) {};
    \node [     ] (33) at (2.5, 4) {};
    \node [     ] (34) at (6.75, 5.25) {};
    \node [style=10x5] (35) at (0, 3.25) {};
    \node [     ] (36) at (0, 7.5) {Robots};
    \node [     ] (37) at (4, 3) {\tiny{Weight}};
    \node [     ] (38) at (9, 3.25) {\tiny{Weight}};
    \node [     ] (39) at (7.5, 0.25) {\$};
    \node [     ] (40) at (9.25, -0.5) {\$};
    \node [     ] (41) at (-9, 2.5) {\tiny{Payload}};
    \node [     ] (42) at (-8.75, 1) {\tiny{Velocity}};
    \node [     ] (43) at (-0.5, 2) {\tiny{Torque}};
    \node [     ] (44) at (-0.5, 1.25) {\tiny{Speed}};
    \node [     ] (45) at (-0.75, 0.25) {\$};
    \node [     ] (46) at (3.5, 1.5) {\tiny{Voltage}};
    \node [     ] (47) at (3.5, 1) {\tiny{Current}};
    \node [     ] (49) at (-4.5, 2.5) {\tiny{Weight}};
  \end{pgfonlayer}\begin{pgfonlayer}{edgelayer}
    \draw [in=180, out=0] (14.center) to (16.center);
    \draw (15.center) to (17.center);
    \draw [bend right] (5.center) to (18.center);
    \draw [bend right] (7.center) to (25.center);
    \draw [bend right=15] (9.center) to (26.center);
    \draw [bend right=15] (13.center) to (27.center);
    \draw (10.center) to (30.center);
    \draw (11.center) to (29.center);
    \draw (24.center) to (19.center);
    \draw (23.center) to (22.center);
    \draw (28.center) to (6.center);
    \draw [bend left=60, looseness=1.25] (21.center) to (31.center);
    \draw [bend left=90] (20.center) to (32.center);
    \draw [bend right=45, looseness=1.25] (12.center) to (33.center);
    \draw [bend right=45, looseness=1.50] (8.center) to (34.center);
    \draw [bend right=15] (34.center) to (32.center);
    \draw [bend left=315, looseness=0.50] (33.center) to (31.center);
  \end{pgfonlayer}
\end{tikzpicture}

</p>