---
title: Categories of profunctors
---

## Composing profunctors


::: {.callout-tip icon=false collapse=false}
## The *composite* $\mathcal{X}\overset{\phi;\psi}\nrightarrow \mathcal{Z}$ of two $\mathcal{V}$ [profunctors](2.qmd#vprof), $\mathcal{X}\overset{\phi}\nrightarrow\mathcal{Y}$ and $\mathcal{Y}\overset{\psi}\nrightarrow\mathcal{Z}$

<div id="v-prof-compose"/></div>
$(\phi;\psi)(x,z) = \bigvee_Y(\phi(x,y)\otimes\psi(y,z))$

:::


::: {.callout-caution icon=false collapse=false}
## Composing **Bool** profunctors
<div id="bool-prof-compose"/></div>

- Need a formula for composing two [feasibility relations](2.qmd#feas) in series.
- Suppose $P,Q,R$ are cities (preorders) and there are bridges (hence, [feasibility matrices](2.qmd#4-12)).
- \begin{tikzcd} \pagecolor{white}
            & N \arrow[rrrrdd, blue, dotted, bend left]                      &                                             &                                             & e                                                       &   &   \\
            W \arrow[ru] \arrow[rrrd, blue,dotted] &                                                          & E \arrow[lu] \arrow[rru, blue, dotted, bend left] & d \arrow[ru] \arrow[rrr, red,dotted, bend left] &                                                         &   & x \arrow[d] \\
            & S \arrow[lu] \arrow[ru] \arrow[rrrd, blue, dotted, bend right] &                                             & b \arrow[u]                                 &                                                         & c & y \\
            &                                                          &                                             &                                             & a \arrow[ru] \arrow[lu] \arrow[rru, red, dotted, bend right] &   &
          \end{tikzcd}


- The [feasibility matrices](2.qmd#4-12) are:

| $\textcolor{blue}{\phi}$ | a | b | c | d | e |
|--|---|--|--|--|---|
| N                        | T | F | T | F | F |
| E                        | T | F | T | F | T |
| W                        | T | T | T | T | F |
| S                        | T | T | T | T | T |


| $\textcolor{red}{\psi}$ | x | y |
|----|--|--|
| a                       | F | T |
| b                       | T | T |
| c                       | F | T |
| d                       | T | T |
| e                       | F | F |

- Feasibility from $P$ to $R$ means there is a way-point in Q which is both reachable from $p \in P$ and can reach $r \in R$.
- Composition is a union $(\phi;\psi)(p,r):= \bigvee_Q \phi(p,q)\land \psi(q,r)$.
- But this is tantamount to [matrix multiplication](../2/5.qmd#v-matrix) which gives us the result matrix:


|$\phi;\psi$ | x |y |
|---|--|--|
|N           | F |T |
|E           | F |T |
|W           | T |T |
|S           | T |T |

:::



::: {.callout-important icon=false collapse=false}
## Exercise 4-22
<div id="4-22"/></div>

Consider the following **Cost** [profunctors](2.qmd#vprof) $\textcolor{blue}{\phi},\textcolor{red}{\psi}$ \[
      \begin{tikzcd}[ampersand replacement=\&] \pagecolor{white}
        A \arrow[d, "3"', bend right] \& B \arrow[l, "2"', bend right] \arrow[d, "5", bend left] \arrow[r, "11", blue, dotted, bend left] \& x \arrow[rr, "3", bend left] \arrow[rd, "4", bend left] \&                                                                      \& z \arrow[ld, "4", bend left] \arrow[r, "4", red,dotted, bend left] \arrow[rd, red, "4", dotted, bend right] \& p \arrow[r, "2", bend left] \& q \arrow[d, "2", bend left] \\
        C \arrow[ru, "3"]             \& D \arrow[l, "4", bend left] \arrow[rr, blue, "9", dotted, bend right]                            \&                                                         \& y \arrow[lu, "3", bend left] \arrow[rrr, red, "0", dotted, bend right=49] \&                                                                                                    \& d \arrow[u, "1", bend left] \& r \arrow[l, "1", bend left]
      \end{tikzcd}
    \]

Fill in the matrix for the [composite profunctor](#v-prof-compose).

::: {.callout-note collapse=true appearance="minimal"}
## Solution
| $\phi;\psi$ | p  | q  | r  | s  |
|---|--|--|--|--|
| A           | 23 | 25 | 21 | 22 |
| B           | 17 | 19 | 15 | 16 |
| C           | 20 | 22 | 18 | 19 |
| D           | 11 | 13 | 9  | 10 |

:::
:::




## The categories V-prof and Feas

::: {.callout-tip icon=false collapse=false}
## The [category](../3/2.qmd#cat) $\mathbf{Prof}_\mathcal{V}$, given a [skeletality](../1/3.qmd#skeletality) [quantale](../2/5.qmd#quantale) $\mathcal{V}$

<div id="v-prof-cat"/></div>
- Objects: $\mathcal{V}$ [categories](../2/3.qmd#v-cat)
- Morphisms: $\mathcal{V}$ [profunctors](2.qmd#vprof), composed according to [this definition](#v-prof-compose)
- Identities are [unit profunctors](#unit-prof)
:::



::: {.callout-caution icon=false collapse=false}
## The category **Feas**
<div id="feas-cat"/></div>
Instantiate a $\mathbf{Prof}_\mathcal{V}$ [category](#v-prof-cat) with $\mathcal{V}=\mathbf{Bool}$
:::


::: {.callout-tip icon=false collapse=false}
## A *unit profunctor* on a $\mathcal{V}$ [category](../2/3.qmd#v-cat).
<div id="unit-prof"/></div>
$U_\mathcal{X}(x,y):=\mathcal{X}(x,y)$
:::


::: {.callout-note icon=false collapse=false}
## Proposition

<div id="prof-unitality"/></div>

The [unit profunctor](#unit-prof) is unital, i.e. for any [profunctor](2.qmd#vprof) $P \overset{\phi}\nrightarrow Q$:  $U_P;\phi = \phi = \phi; U_Q$

::: {.callout-note collapse=true appearance="minimal"}
## Proof
- Due to skeletality, we need to show for all inputs that $\phi \leq U_P;\phi$ and $U_P;\phi \leq \phi$ (the second equality to show is done similarly).
- Forward direction
    - $\phi(p,q) = I \otimes \phi(p,q)$
        - due to unitality of $I$ in a [symmetric monoidal preorder](../2/2.qmd#smp).
    - $\leq P(p,p) \otimes \phi(p,q)$
        - This is because $\forall p \in P:$ $I \leq P(p,p)$ (a constraint of a $\mathcal{V}$ [category](../2/3.qmd#v-cat)), the reflexivity of $\leq$ for $\phi(p,q)$, and the [monotonicity](../2/2.qmd#smp) of $\otimes$.
    - $\leq \underset{p' \in P}\bigvee(P(p,p') \otimes \phi(p',q))$
        - The join is a least upper bound, and the LHS is an element of the set being joined over (the case where $p=p'$).
    - $= (U_P;\phi)(p,q)$
        - This is the [profunctor composition](#v-prof-compose) formula, subtituting in the [unit profunctor](#unit-prof) definition explicitly.
- Reverse direction
    - Need to show $\underset{p' \in P}\bigvee(P(p,p')\otimes \phi(p',q)) \leq \phi(p,q)$
    - Show that this property holds for each $p' \in P$ - given the join is a least upper bound, it will also be less than or equal to $\phi(p,q)$
    - $P(p,p')\otimes\phi(p',q) = P(p,p')\otimes\phi(p',q)\otimes I$
        - due to unitality of $I$ in a [symmetric monoidal preorder](../2/2.qmd#smp).
    - $\leq P(p,p')\otimes \phi(p',q)\otimes Q(q,q)$
        - $\forall p:$ $I \leq P(p,p)$ (a constraint of a $\mathcal{V}$ [category](../2/3.qmd#v-cat)) and the [monotonicity](../2/2.qmd#smp) of $\otimes$.
    - $\leq\phi(p,q)$
        - This was shown in [Exercise 4.9](1.qmd#4-9)





:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-26
<div id="4-26"/></div>

Choose a nontrivial **Cost**-[category](../2/3.qmd#v-cat) $\mathcal{X}$ and draw a bridge-style diagram of the [unit profunctor](#unit-prof) $\mathcal{X} \overset{U_\mathcal{X}}\nrightarrow \mathcal{X}$

::: {.callout-note collapse=true appearance="minimal"}
## Solution

\begin{tikzcd} \pagecolor{white}
  & A \arrow[ld, "3"', bend right] \arrow[rd, "2", bend left] \arrow[rrr, blue,"0", dotted] &                                       &                                     & A \arrow[ld, bend right] \arrow[rd, bend left] &   \\
  B \arrow[rd, "4", bend right] \arrow[rr, "1"] \arrow[rrr, "0"', blue, dotted, bend right] &                                                                                    & D \arrow[rrr, "0", dotted, blue,bend left] & B \arrow[rd, bend right] \arrow[rr] &                                                & D \\
  & C \arrow[ru, "1"', bend right] \arrow[rrr, "0", blue, dotted]                            &                                       &                                     & C \arrow[ru, bend right]                       &
\end{tikzcd}


:::
:::

::: {.callout-important icon=false collapse=false}
## Exercise 4-30
<div id="4-30"/></div>

1. Justify all steps the proof of the [unitality of unit profunctors](#prof-unitality).
2. In the case of $\mathcal{V}=\mathbf{Bool}$ show each step in the forward direction is actually an equality.

::: {.callout-note collapse=true appearance="minimal"}
## Solution
1. Done, see the [proof](#prof-unitality)
2.
- $\forall p: P(p,p)=true$ for a **Bool**-enriched category, because that is the only option for $I=true\leq P(p,p)$
    - $true \land x = x$
- If $\phi(p,q)$:
    - then at least one element of the set being joined over is true (where $p=p'$ such that $P(p,p')\land \phi(p',q) = true$), and the least upper bound of such a set is $true$
- Else:
    - Then every element of that set is $false$ such that the join is also $false$.
        - If $p\leq p'$, it fails because of the second conjunct (consider the constraint on profunctors: we are demanding equal or more resources than something we know fails)
        - If $p \not \leq p'$, it fails because of the first conjunct. In a **Bool**-category $P$, $P(a,b)$ iff $a \leq b$.

:::
:::

::: {.callout-important icon=false collapse=false}
## Exercise 4-31
<div id="4-31"/></div>

Prove that the serial [composition of profunctors](#v-prof-compose), $\mathcal{X}\overset{\phi}\nrightarrow\mathcal{Y}$ and $\mathcal{Y}\overset{\psi}\nrightarrow\mathcal{Z}$, is associative.

::: {.callout-note collapse=true appearance="minimal"}
## Solution
This is tantamount to the [quantale matrix multiplication](../2/5.qmd#v-matrix) being associative, which was shown in [Exercise 2.104](../2/5.qmd#2-104).
:::
:::

## Fun profunctor facts


::: {.callout-tip icon=false collapse=false}
## The *companion* and *conjoint* of a $\mathcal{V}$ [functor](../2/4.qmd#v-functor), $\mathcal{P}\xrightarrow{F}\mathcal{Q}$

<div id="companion"/></div>
-  Companion, denoted $\mathcal{P}\overset{\hat F}\nrightarrow \mathcal{Q}$, is defined $\hat{F}(p,q):=\mathcal{Q}(F(p),q)$
- Conjoint, denoted $\mathcal{Q}\overset{\check{F}}\nrightarrow\mathcal{P}$

:::


::: {.callout-tip icon=false collapse=false}
## A $\mathcal{V}$ *adjunction*.

<div id="v-adjunction"/></div>
A pair of $\mathcal{V}$ [functors](../2/4.qmd#v-functor), $\mathcal{P}\overset{F}{\underset{G}\rightleftarrows} \mathcal{Q}$ such that: $\forall p\in \mathcal{P}, q \in \mathcal{Q}: \mathcal{P}(p,G(q)) \cong \mathcal{Q}(F(p),q)$

:::


::: {.callout-tip icon=false collapse=false}
## The collage of a $\mathcal{V}$ [profunctor](2.qmd#vprof), $\mathcal{X}\overset{\phi}\nrightarrow \mathcal{Y}$

<div id="v-collage"/></div>
- A $\mathcal{V}$ [category](../2/3.qmd#v-cat), denoted $\mathbf{Col}(\phi)$
    - $Ob(\mathbf{Col}(\phi)):=$$Ob(\mathcal{X})\sqcup Ob(\mathcal{Y})$
    - $\mathbf{Col}(\phi)(a,b) :=$ $\begin{cases}\mathcal{X}(a,b) & a,b \in \mathcal{X} \\ \phi(a,b)& a \in \mathcal{X}, b \in \mathcal{Y} \\ \varnothing & a \in \mathcal{Y}, b \in \mathcal{X} \\ \mathcal{Y}(a,b) & a,b \in \mathcal{Y} \end{cases}$
- There are obvious functors $\mathcal{X}\xrightarrow{i_\mathcal{X}}\mathbf{Col}(\phi)$ and $\mathcal{Y}\xrightarrow{i_\mathcal{Y}}\mathbf{Col}(\phi)$ sending each object to "itself" called *collage inclusions*
:::


::: {.callout-caution icon=false collapse=false}
## Companion and conjoint of identity
<div id="companion-id"/></div>


- For any preorder $\mathcal{P}$, there is an identity functor $\mathcal{P}\xrightarrow{id}\mathcal{P}$
- Its [companion and conjoint](#companion) agree: $\hat{id}=\check{id}=\mathcal{P}\overset{U_\mathcal{P}}\nrightarrow \mathcal{P}$ equivalent to the [unit profunctor](#unit-prof).


:::



::: {.callout-caution icon=false collapse=false}
## Companion and conjoint of addition
<div id="companion-addition"/></div>


- Consider the addition function on real numbers.
- It is [monotonic](../1/4.qmd#monotone-map), since $(a,b,c)\leq(a',b',c')$ means $a+b+c\leq a'+b'+c'$
- Therefore it has a [companion and a conjoint](#companion)
    - The companion $\mathbb{R}\times\mathbb{R}\times\mathbb{R}\overset{\hat +}\nrightarrow \mathbb{R}$ sends $(a,b,c,d)$ to *true* iff $a+b+c\leq d$.




:::



::: {.callout-caution icon=false collapse=false}
## Ex 4-43
<div id="x-4-43"/></div>
[TODO]{style="color: red; background-color: yellow;"}
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-36
<div id="4-36"/></div>

Check that the [companion](#companion) $\hat{id}$ of the identity functor is actually the [unit profunctor](#unit-prof).

::: {.callout-note collapse=true appearance="minimal"}
## Solution
[TODO]{style="color: red; background-color: yellow;"}

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-38
<div id="4-38"/></div>

Considering the [addition example](#companion-addition), what is the [conjoint](#companion) of this addition function?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
[TODO]{style="color: red; background-color: yellow;"}

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-41
<div id="4-41"/></div>

Let $\mathcal{V}$ be a [skeletality](../1/3.qmd#skeletality) [quantale](../2/5.qmd#quantale) and $\mathcal{P}\overset{F}{\underset{G}\rightleftarrows} \mathcal{Q}$ be $\mathcal{V}$ [functors](../2/4.qmd#v-functor).
    Show that $F \dashv G$ iff the [companion](#companion) of the former equals the [conjoint](#companion) of the latter, i.e. $\hat F = \check G$

::: {.callout-note collapse=true appearance="minimal"}
## Solution
[TODO]{style="color: red; background-color: yellow;"}

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-44
<div id="4-44"/></div>

Draw a Hasse diagram for the [collage](#collage) of the [profunctor](2.qmd#vprof): (draw here)

::: {.callout-note collapse=true appearance="minimal"}
## Solution
[TODO]{style="color: red; background-color: yellow;"}

:::
:::
