---
title: Categorification
listing:
  id: backlinks
  type: table
  filter-ui: true
  template: "../../../../ejs/custom.ejs"
  contents:
    - ../../../../backlinks/docs_math_sketches_4_4.yml
---

## The basic idea


- General idea: take a thing we know and add structure to it such that things that were formerly *properties* become *structures*
- Do in such a way as to be able to recover the thing we categorified by forgetting the new structure.
- In categorified world, we have more structure available to talk about the relationships between objects.
- An example is how we treated preorders as categories.
- Ordinary categories are **Set**-categories




::: {.callout-caution icon=false collapse=false}
## Categorification of basic arithmetic
<div id="categorification-arithmetic"/></div>
- Categorification of arithmetic using the category **FinSet**
- Replace natural numbers with arbtirary sets of that cardinality.
- Replace $+$ with coproduct.
- This is good categorification because, with replacements, arithmatic truths are preserved: $\bar{5}\sqcup \bar{3} \cong \bar{8}$

:::


## A reflection on wiring diagrams
[To do]{style="color: red; background-color: yellow;"}

## Monoidal categories

- Just like [preorders](../1/3.qmd#preorder) are special kinds of [categories](../3/2.qmd#cat), [symmetric monoidal preorders](../2/2.qmd#smp) are special kinds of [monoidal categories](#smc).
- Just as we can consider $\mathcal{V}$ [categories](../2/3.qmd#v-cat) for a [symmetric monoidal preorder](../2/2.qmd#smp), we can consider $\mathcal{V}$ [categories](../2/3.qmd#v-cat) when $\mathcal{V}$ is a [monoidal category](#smc).
- One difference is that associativity is up to isomorphism: e.g. products in set $S \times (T \times U)$ vs $(S \times T) \times U$
- When the isomorphisms of a [symmetric monoidal category](#smc) are replaced with equalities, we call it *strict*
    - Due to "Mac Lane's coherence theorem" we can basically treat all as strict...something we implicitly do when writing wiring diagrams.





::: {.callout-tip icon=false collapse=false}
## A **rough** definition of a *symmetric monoidal structure* on a [category](../3/2.qmd#cat) $\mathcal{C}$

<div id="smc"/></div>
- Two additional constituents
    - An object $I \in Ob(\mathcal{C})$ called the *monoidal unit*
    - A functor $\mathcal{C}\times \mathcal{C}\xrightarrow{\otimes}\mathcal{C}$ called the *monoidal product*
- Subject to the **well-behaved**, natural isomorphisms
    - $I \otimes c \overset{\lambda_c}\cong c$
    - $c \otimes I \overset{\rho_c}\cong c$
    - $(c \otimes d)\otimes e \overset{\alpha_{c,d,e}}\cong c \otimes (d\otimes e)$
    - $c \otimes d \overset{\sigma_{c,d}}\cong d \otimes c$
- A category equipped with these is a *symmetric monoidal category*

:::

::: {.callout-caution icon=false collapse=false}
## **Set** as an SMC
<div id="set-smc"/></div>


- Monoidal structure on **Set**
- Let $I$ be any singleton, say $\{1\}$ and the monoidal product is the cartesian product.
- This means that $\times$ is a functor:
    - For any pair of sets in $(S,T) \in Ob(\mathbf{Set}\times\mathbf{Set})$, one obtains a set $S \times T \in Ob(\mathbf{Set})$.
    - For any pair of morphisms (functions) one obtains a function $(f\times g)$ which works pointwise: $(f\times g)(s,t):=(f(s),g(t))$ which preserves identities and composition.
- The bookkeeping isomorphisms are obvious in **Set**



:::
::: {.callout-important icon=false collapse=false}
## Exercise 4-48
<div id="4-48"/></div>

Check that monoidal categories generalize monoidal preorders: a monoidal preorder is a monoidal category $(P,I,\otimes)$ where $P(p,q)$ has at most one element.

::: {.callout-note collapse=true appearance="minimal"}
## Solution
[TODO]{style="color: red; background-color: yellow;"}
:::
:::
::: {.callout-important icon=false collapse=false}
## Exercise 4-50
<div id="4-50"/></div>



- Consider the monoidal category $(\mathbf{Set},1,\times)$ together with the following diagram (TO DO NEED TO COPY)
- $A=B=C=D=F=G=\mathbb{Z}$ and $E=\mathbb{B}$
- $f_C(a)=|a|$,
- $f_D(a)=a*5$,
- $g_E(d,b)=d\leq b$
- $g_F(d,b)=d-b$
- $h(c,e)=\text{if }e\text{ then }c\text{ else }1-c$
- Suppose the whole diagram defines a function $A \times B \xrightarrow{q} G \times F$
1. What are $g_E(5,3)$ and $g_F(5,3)$?
2. What are $g_E(3,5)$ and $g_F(3,5)$?
3. What is $h(5,true)$?
4. What is $h(-5,true)$?
5. What is $h(-5,false)$?
6. What are $q_G(-2,3)$ and $q_F(-2,3)$?
7. What are $q_G(2,3)$ and $q_F(2,3)$?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
1. $False,\ 2$
2. $True,\ -2$
3. $5$
4. $-5$
5. $6$
6. $(2,-13)$ ... $a\mapsto -2,\ b \mapsto 3,\ c\mapsto 2,\ d\mapsto -10,\ e\mapsto true,\ f\mapsto -13, g \mapsto 2$
7. $(-1,7)$ ... $a\mapsto 2,\ b \mapsto 3,\ c \mapsto 2,\ d\mapsto 10,\ e\mapsto false, f\mapsto 7, g\mapsto -1$
:::
:::


## Categories enriched in a SMC

- We said that ordinary categories were just **Set**-categories, but our definition of $\mathcal{V}$ categories required the $\mathcal{V}$ to be a preorder!
- We have to generalize (categorify) $\mathcal{V}$ categories.
- Symmetric monoidal preorders can be considered as symmetric monoidal categories, despite not providing the data for identities and composition (these are not needed because there is no choice).
    - Example of property becoming structure: $I \leq \mathcal{X}(x,x)$ is a property of $\mathcal{V}$ [categories as defined earlier](../2/3.qmd#v-cat) but become part of the structure in the [categorified version of the definition](#enrich-smc).


::: {.callout-tip icon=false collapse=false}
## A $\mathcal{V}$ *category* (a category enriched in $\mathcal{V}$) where $\mathcal{V}$ is a [symmetric monoidal category](#smc).

<div id="enrich-smc"/></div>
- Call the category $\mathcal{X}$. There are four constituents:
    - A collection of objects, $Ob(\mathcal{X})$
    - For every pair in $Ob(\mathcal{X})$ one specifies the *hom-object* $X(x,y) \in \mathcal{V}$.
    - For every object, specify a $I \xrightarrow{id_x}X(x,x) \in \mathcal{V}$ called the *identity element*
    - For every pair of compatible morphisms, a $\mathcal{X}(x,y)\otimes\mathcal{X}(y,z)\xrightarrow{;}\mathcal{X}(x,z)$ called the *composition morphism*.
- These satisfy the usual associative and unital laws.

:::

::: {.callout-important icon=false collapse=false}
## Exercise 4-52
<div id="4-52"/></div>

Recall the [example](#set-smc) with **Set** as a symmetric moniodal category. Apply the definition of a $\mathcal{V}$ [category](#enrich-smc) and see if this agrees with the definition of an ordinary [category](../3/2.qmd#cat). Is there a subtle difference?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
We've replaced the identity morphisms with maps from the monoidal unit, but that is functionally equivalent to 'just picking one' given that the initial object is a singleton.

:::
:::

::: {.callout-important icon=false collapse=false}
## Exercise 4-54
<div id="4-54"/></div>

What are identity elements in Lawvere metric spaces (**Cost**-categories)? How do we interpret this in terms of distances?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
$0$ was the monoidal unit - the distance from an object to itself.

:::
:::

