---
title: Profunctors form compact closed categories
---

## Compact closed categories

::: {.callout-tip icon=false collapse=false}
## The *dual* for an object $c \in Ob(\mathcal{C})$, which is part of a symmetric monoidal category $(\mathcal{C},I,\otimes)$.

<div id="dual"/></div>

Three consituents:
1. An object $c^* \in Ob(\mathcal{C})$ called the *dual of c*
2. A morphism $I\xrightarrow{\eta_c}c^* \otimes c$ called the *unit for c*
3. A morphism $c \otimes c^* \xrightarrow{\epsilon_c}I$ called the *counit for c*

These are required to satisfy two commutative diagram relations (*snake equations*)

\begin{tikzcd} \pagecolor{white}
    & c \arrow[ld, "\cong"'] &                                                              \\
    c\otimes I \arrow[d, "c \otimes \eta_c"']      &                        & I \otimes c \arrow[lu, "\cong"']                             \\
    c \otimes (c^* \otimes c) \arrow[rr, "\cong"'] &                        & (c \otimes c^*) \otimes c \arrow[u, "\epsilon_c \otimes c"']
  \end{tikzcd}


and


\begin{tikzcd} \pagecolor{white}
    & c \arrow[rd, "\cong"] & \\
    c^*\otimes I \arrow[ru, "\cong"] & & I \otimes c^* \arrow[d, "\eta_c \otimes c^*"]   \\
    c^* \otimes (c \otimes c^*) \arrow[u, "c^* \otimes \epsilon_c"] & & (c^* \otimes c) \otimes c^* \arrow[ll, "\cong"] \end{tikzcd}

:::


::: {.callout-tip icon=false collapse=false}
## A *compact closed* [symmetric monoidal category](4.qmd#smc)
<div id="ccsmc"/></div>

One for which every object there exists a [dual](#dual).  This allows us to use the following morphisms without reservation:

\begin{tikzpicture}
    \begin{pgfonlayer}{nodelayer}
      \node [] (0) at (0, 0.5) {};
      \node [label=below:c] (1) at (-1, 0.5) {};
      \node [label=above:c] (2) at (-1, 1.5) {};
      \node [] (3) at (0, 1.5) {};
      \node [] (4) at (-2.25, 1) {$\eta_c$};
    \end{pgfonlayer}
    \begin{pgfonlayer}{edgelayer}
      \draw [style=blue pointer] (0.center) to (1.center);
      \draw [style=blue pointer, in=180, out=180, looseness=2.7] (1.center) to (2.center);
      \draw [style=blue pointer, in=180, out=0] (2.center) to (3.center);
    \end{pgfonlayer}
  \end{tikzpicture}

and

\begin{tikzpicture}
    \begin{pgfonlayer}{nodelayer}
      \node [] (0) at (-2, 0.5) {};
      \node [label=below:c] (1) at (-1, 0.5) {};
      \node [label=above:c] (2) at (-1, 1.5) {};
      \node [] (3) at (-2, 1.5) {};
      \node [] (4) at (0.25, 1) {$\epsilon_c$};
    \end{pgfonlayer}
    \begin{pgfonlayer}{edgelayer}
      \draw [style=blue pointer] (0.center) to (1.center);
      \draw [style=blue pointer, in=360, out=360, looseness=2.7] (1.center) to (2.center);
      \draw [style=blue pointer, in=180, out=0] (2.center) to (3.center);
    \end{pgfonlayer}
  \end{tikzpicture}


This also allows us to use the following snake equations in wiring diagrams without reservation:


\begin{tikzpicture}
  \begin{pgfonlayer}{nodelayer}
    \node [] (0) at (0, 0) {};
    \node [] (1) at (0, 1) {};
    \node [] (2) at (0, 2) {};
    \node [label=above:c] (3) at (2, 2) {};
    \node [label=below:c] (4) at (-2, 0) {};
    \node [label=below:$c \otimes \eta_c\ |\ $] (5) at (-0.5, -0.25) {};
    \node [label=below:$\ |\ \epsilon_c \otimes c$] (6) at (0.5, -0.25) {};
  \end{pgfonlayer}
  \begin{pgfonlayer}{edgelayer}
    \draw [style=blue pointer] (4.center) to (0.center);
    \draw [style=blue pointer, bend right=90, looseness=2.50] (0.center) to (1.center);
    \draw [style=blue pointer, bend left=90, looseness=2.00] (1.center) to (2.center);
    \draw [style=blue pointer] (2.center) to (3.center);
  \end{pgfonlayer}
\end{tikzpicture}

and

\begin{tikzpicture}
    \begin{pgfonlayer}{nodelayer}
      \node [] (0) at (0, 0) {};
      \node [] (1) at (0, 1) {};
      \node [] (2) at (0, 2) {};
      \node [label=below:c] (3) at (-2, 2) {};
      \node [label=above:c] (4) at (2, 0) {};
      \node [label=below:$\eta_c \otimes c^*\ |\ $] (5) at (-0.5, -0.25) {};
      \node [label=below:$\ |\ c^* \otimes \epsilon_c$] (6) at (0.5, -0.25) {};
    \end{pgfonlayer}
    \begin{pgfonlayer}{edgelayer}
      \draw [style=blue pointer] (4.center) to (0.center);
      \draw [style=blue pointer, bend left=90, looseness=2.50] (0.center) to (1.center);
      \draw [style=blue pointer, bend right=90, looseness=2.00] (1.center) to (2.center);
      \draw [style=blue pointer] (2.center) to (3.center);
    \end{pgfonlayer}
\end{tikzpicture}
:::


::: {.callout-note icon=false collapse=false}
## Proposition

<div id="compact-closed-properties"/></div>

If $\mathcal{C}$ is a [compact closed category](#ccsmc), then:

- $\mathcal{C}$ is [monoidal closed](../2/5.qmd#closed)
- the [dual](#dual) of $c$ is unique up to isomorphism
- $c \cong (c^*)^*$


::: {.callout-note collapse=true appearance="minimal"}
## Proof
Not really proven, but: $c \multimap d$ is given by $c^* \otimes d$

The natural isomorphism $\mathcal{C}(b \otimes c, d)\cong \mathcal{C}(b,c \multimap d)$ is given by precomposing with $id_b \otimes \eta_c$
:::
:::


::: {.callout-caution icon=false collapse=false}
## **Correl** as compact closed category
<div id="correl-cc"/></div>


- The [compact closed category](#ccsmc): **Corel**
- A *correlation* $A \rightarrow B$ is an equivalence relation on $A \sqcup B$
- Correlations are composed by the following rule: two elements are equivalent in the composite if we may travel from one to the other while staying within the component equivalence classes of either
- There is a symmetric monoidal structure $(\varnothing, \sqcup)$. For any finite set $A$ there is an equivalence relation on $A \sqcup A$ that partitions elements in the first set from the second. The unit and counit are given by this partition:
    - $\varnothing \xrightarrow{\eta_A} A \sqcup A$
    - $A \sqcup A \xrightarrow{\epsilon_A} \varnothing$
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-62
<div id="4-62"/></div>


1. Draw a picture of the unit correlation $\varnothing \xrightarrow{\eta_{\bar 3}} \bar 3 \sqcup \bar 3$
2. Draw a picture of the counit correlation $\bar 3 \sqcup \bar 3 \xrightarrow{\epsilon_{\bar 3}} \varnothing$
3. Check that the [snake equations](#dual) hold. Since every object is its own dual, only one has to be checked.


::: {.callout-note collapse=true appearance="minimal"}
## Solution

1. $\boxed{\varnothing}\rightarrow \underset{\bar 3}{\boxed{\bullet\ \bullet\ \bullet}}\  \underset{\bar 3}{\boxed{\bullet\ \bullet\ \bullet}}$
2. $\boxed{\varnothing}\leftarrow \underset{\bar 3}{\boxed{\bullet\ \bullet\ \bullet}}\  \underset{\bar 3}{\boxed{\bullet\ \bullet\ \bullet}}$
3. TODO
:::
:::



## **Feas** as a compact closed category

::: {.callout-note icon=false collapse=false}
## Proposition

<div id="ccc-from-prof-cat"/></div>

Let $\mathcal{V}$ be a skeltal quantale. The category $\mathbf{Prof}_\mathcal{V}$ can be given the structure of a [compact closed category](#ccsmc), with the monoidal product given by the product of $\mathcal{V}$ categories.

::: {.callout-note collapse=true appearance="minimal"}
## Proof

- Monoidal product acts on objects:
    - $\mathcal{X} \times \mathcal{Y}((x,y),(x',y'))$ := $\mathcal{X}(x,x') \otimes \mathcal{Y}(y,y')$
- Monoidal product acts on morphisms:
    - $\phi \times \psi((x_1,y_1),(x_2,y_2))$ := $\phi(x_1,x_2)\otimes\psi(y_1,y_2)$
- Monoidal unit is the $\mathcal{V}$ category $1$
- Duals in $\mathbf{Prof}_\mathcal{V}$ are just [opposite categories](../2/3.qmd#2-73)
    - For every $\mathcal{V}$ category, $\mathcal{X}$, its dual is $\mathcal{X}^{op}$
    - The unit and counit look like identities
        - The unit is a $\mathcal{V}$ profunctor $1 \overset{\eta_\mathcal{X}}\nrightarrow \mathcal{X}^{op} \times \mathcal{X}$
        - Alternatively $1 \times \mathcal{X}^{op} \times \mathcal{X}\xrightarrow{\eta_\mathcal{X}}\mathcal{V}$
        - Defined by $\eta_\mathcal{X}(1,x,x'):=\mathcal{X}(x,x')$
        - Likewise for the co-unit: $\epsilon_\mathcal{X}(x,x',1):=\mathcal{X}(x,x')$

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-64
<div id="4-64"/></div>
TODO


::: {.callout-note collapse=true appearance="minimal"}
## Solution
TODO

:::
:::
::: {.callout-important icon=false collapse=false}
## Exercise 4-65
<div id="4-65"/></div>
TODO


::: {.callout-note collapse=true appearance="minimal"}
## Solution
TODO

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 4-66
<div id="4-66"/></div>

Check that the proposed unit and counits do obey the [snake equations](#dual).

::: {.callout-note collapse=true appearance="minimal"}
## Solution
TODO
:::
:::
