---
title: 03 - Rorty Finds His Pragmatist Voice
aliases: [rorty03]
tags:  
- lecture
- RED

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/03 - rorty finds his pragmatist voice.yml
---

[Author](/docs/phil/people/Robert Brandom.html) [Prev](/docs/phil/antirep2020/02 - Rorty’s Critique of Enlightenment Representationalism and Analytic Philosophy.html) [Next](/docs/phil/antirep2020/04 -  Cheryl Misak's Critique of Rorty's Pragmatism.html)

# Major lessons
1. From the discussion of [truth](/docs/phil/Truth.html) as “what is best in the way of belief” as 
   opposed to correspondence with reality:
   - How the combination of:
       - [declarativism](/docs/phil/Declarativism.html)
           - blurring out all distinctions of kind of claimable
       - [expressivism](/docs/phil/Expressivism.html)
           - a local expressivism about what one is doing in attributing truth —  namely not describing the claimable, but endorsing it
           - underwriting a global antirepresentationalism because of special properties of the vocabulary of truth
   - *together* underwrite a [Jamesean](/docs/phil/people/William James.html)  understanding of truth-talk.
   - This role for an [expressivist](/docs/phil/Expressivism.html)  move in a pragmatist argument forges an important link between the first and the second halves of this course.
2. From the discussion of representation:
   - What is really at stake in the battle between a representational model of the content of expressions and a pragmatist model is the best order of explanation (a way of thinking about conceptual priority) between representational relations and reason relations (of implication and incompatibility).
  - [Davidson](/docs/phil/people/Donald Davidson.html) teaches us that and how taking reason relations as primary (the pragmatists says, because giving and assessing reasons, implicitly and 
    practically appealing to justificatory reason relations, specifiable in a deontic normative vocabulary of “commitment” and “entitlement”) holistically 
    determines representational relations in top-down explanatory stories.
  - Representationalists are committed to atomistic objective usually causal relations (specifiable in an alethic modal vocabulary) determine reason 
    relations.

# Introduction to pragmatism
## Platonist / Pragmatist distinction
Rorty takes for granted a [distinction](/docs/phil/interaction/Pragmatism and platonism.html) of [Dewey](/docs/phil/people/John Dewey.html):

| platonism      | pragmatism |
| ----------- | ----------- |
| Principles      | Practices       |
| Theoria   | Phronesis        |
| Knowing that | Knowing how |
| Ending the conversation | Continuing the conversation |

- Platonists look for a principle or rule, something explicit or that could be 
  made explicit, behind every implicit propriety of practice.

- [Pragmatists](/docs/phil/Pragmatism.html) argue that explicit principles or theories float on a vast sea of 
  implicit practical skills.

What's at stake: the order of explanation / conceptual priority between *principles* and *practices*.

For example, a cobbler can make good shoes. The platonist looks for what form is behind his mastery, what principle / mental representation makes it possible that the cobbler does that? The pragmatist treats the skill as prior to the principle.

Rorty sees representationalism as the distinctly modern form of platonism as described above.

[Kant](/docs/phil/people/Immanuel Kant.html) is the avatar of this form of representationalism: representations and rules are two sides of the same coin. He puts principle over practice (opposed by Dewey, who was followed by early [Heidegger](/docs/phil/people/Martin Heidegger.html) and late [Wittgenstein](/docs/phil/people/Ludwig Wittgenstein.html) in this respect).

## The [vocabulary](/docs/phil/Vocabulary.html) vocabulary
This is Rorty's way of talking about  [language game](/docs/phil/Language game.html)s / paradigms.[^kuhn] Vocabularies are what we deploy in discursive practice.

[^kuhn]: In the [Kuhnian](/docs/phil/people/Thomas Kuhn.html) sense -  Kuhn was writing just down the hall from Rorty. Though Kuhn was talking about vocabularies that weren't autonomous discursive practices.

He thinks this is needed as a [successor notion](/docs/phil/Successor concept.html) to the idea of languages and theories, which was rightfully taken apart by Quine's [Two Dogmas of Empiricism](/docs/phil/works/Two Dogmas of Empiricism.html).

Examples:
- the vocabulary of 16th century theology
- also, the vocabulary of *modernity*
  - where that's presumably an [autonomous discursive practice](/docs/phil/Autonomous discursive practice.html)

Rorty doesn't draw a line between speaking in a vocabulary and changing your vocabulary (he thinks almost all speech acts change it due to the  [Duhem point](/docs/phil/Duhem-Quine thesis.html)).[^du]

[^du]:  each time we add a new belief we change the meanings in the rest of our vocabulary, since we have changed the inferential relations.  

In mature sciences, a lot of work is taken to allow for discourse to proceed as if the vocabulary were fixed

- The discursive equivalent of "clean rooms", maintained through heroic social disciplinary measures
- This is for *mature* sciencies: if you think of the history of temperature,  every single time a new way of measuring temperature was discovered, the 
      concept changes
- But it would be a serious mistake to take this extreme, artificial case to  be the paradigm on the basis of which we understand the use of language in 
      general.[^hei] 
      
[^hei]: Here we might think of  [Heidegger](/docs/phil/people/Martin Heidegger.html) on the effort it takes to precipitate Vorhandenheit out of Zuhandenheit.

*Sometimes* we want to prevent the vocabulary from changing, [but not always](/docs/phil/quotes/Criteria as regress stopping.html).

## [Redescription](/docs/phil/Redescription.html)
- The generation of new vocabularies.

- This is the essence of discursive practice, is to be committed to a view of 
  conversation as something to be continued.

- But one can do other things with vocabularies than use them to describe. So   “redescription,” though evocative, might be replaced by “recharacterization,” 
  or “reconceptualization.”

## Conversation
> Pragmatists follow [Plato](/docs/phil/people/Plato.html) in striving 
  for an escape from conversation to 
  something atemporal which lies in the background of all possible conversations

Conversation is about redescribing our vocabulary as much as using it. It is the 
process that produces redescriptions.

Quantifying over all possible vocabularies is a temptation and something you would only attempt to do if you are trying to end all conversation. This is a 
fundamental mistake.

- This is something the early Wittgenstein did in the  [Tractatus Logico-Philosophicus](/docs/phil/works/Tractatus Logico-Philosophicus.html)
- He then learned not to do this. It's related to his later view that language  is a motley.

[Dummett](/docs/phil/people/Michael Dummett.html)'s interpretation of Wittgenstein:

- Wittgenstein would think that if there were any use for a philosophical notion  of meaning, the point of having a notion of meaning would be to codify  proprieties of use.
- But there is no limit of things one can use language for, so we cannot systematically find all meanings of all expressions.
- Wittgenstein tool analogy:
   - you would think that you could describe the different ways of using things in terms of what you do with them in the way you could tools, so that you could think of hammer and nails, screw and screwdriver, glue and glue brush, all his ways of attaching things to one another. And that would be a sort of common function that they could perform.
   - Early W. thought 'Yes, representation is like that. That's what language is for.'
   - What about a wrench What about the pencil that the carpenter uses, or the level that the carpenter uses, or the tool belt or tool chest? Or the set  of plans that they're using?
      - All these are functioning differently, and there isn't going to be a systematic way of saying all the different kinds of tools that you could have
   - Classic Wittgensteinian anecdotes turn on the 
     [malleability of language](/docs/phil/Tooth pain.html).
      - The metaphysical puzzle comes from having a *static*, totalizing picture of language rather than accepting it as a motley that evolves whenever you use it.
      - We carefully design mature natural science and math to not have this  happen, but this should not be a model for how our language works.
   - This is why Wittgenstein is a [semantic nihilist](/docs/phil/Semantics.html#Semantic nihilism), he doesn't think there are actually meanings. The plasticisty of language makes this impossible.

## [Coping](/docs/phil/Coping.html)
Rorty has another term that is part of the constellation that starts with “vocabulary” and includes “redescription” and “conversation.” It is “coping.” 

It is his generic term for what we do with vocabularies, generally. It is in terms of success at coping that we are able sometimes to assess and compare vocabularies as better and worse. In that regard, it plays a role analogous to the notion of accuracy of representation, that Rorty wants to persuade us to discard as specifying the dimension along which arbitrary vocabularies can be 
assessed as better or worse.

It is crucial to this notion of coping that standards for it are rigorously internal to the vocabularies being assessed.


# Radical antibifurcationism

Rorty rejects the [distinction](/docs/phil/Objective and subjective facts.html) of objective and subjective facts.

{{< include "/docs/phil/quotes/pragmatism as denying some distinctions.qmd" >}}

{{< include "/docs/phil/quotes/disciplines sociologically different not epistemologically.qmd" >}}

Pragmatism undercuts a bunch of important (seemingly essential) distinctions:
 - saying how things are in the natural science
 - saying how things ought to be in moral theories
 
Rorty claims they must be seen as the same type of claim (they stand to what they're "about" in the same way - there's no need to worry about what makes them true - just think about the reason relations they stand in to other claims). 

Brandom accuses Rorty of blurring distinctions with the vocabulary vocabulary in the way that Rorty accused Dewey of using the notion of experience to blur every conceivable distinction. This is point that most people get off the Rorty train.[^c] This is no longer *meta*philosophically unpalatable (e.g. we should stop capital-P philosophy) but *philosophically* unpaletable.

[^c]: We should admire Rorty's philosophical courage. Where other people have switched from *modus ponens* to *modus tollens*, he's still extracting consequences.
# [Truth](/docs/phil/Truth.html)
Two broad conceptions

1. Truth as "correspondence with reality"
2. Truth as "what is best in the way of belief"


The former is a modern, representationalist rendering of [Aristotle](/docs/phil/people/Aristotle.html)'s "saying of what is, that it is, and of what is not, that it is not". The latter is associated with [James](/docs/phil/people/William James.html) and Rorty sees no conflict between the two (because the former is a platitude).


With a universal [declarativism](/docs/phil/Declarativism.html) about truth,[^dec] the latter has consequences that statements in all vocabularies are true *[in the very same sense](/docs/phil/Objective and subjective facts.html)* as OED statements can be. They are *no less true* than true scientific claims.

[^dec]: I.e. there are not different [kinds of truth](/docs/phil/quotes/Pragmatism denying different kinds of truths.html)

{{< include "/docs/phil/quotes/truth not interesting.qmd" >}}


Expressivism about [truth](/docs/phil/Truth.html) is to say one is not describing a statement when one says it is true - one is doing something else (endorsing  / taking a normative stance towards it). Combining this with universal [declarativism](/docs/phil/Declarativism.html) about truth leads to global [anti-representationalism](/docs/phil/Anti-representationalism.html) / [anti-bifurcationism](/docs/phil/Objective and subjective facts.html)

## Truth vs assertability

Rather than truth being a property of statements, it is better to think of the pragmatics of calling something truth as *you* taking a normative stance towards it - you are *doing* something (endorsing) that is not describing. This is [expressivism](/docs/phil/Expressivism.html) about truth. This is giving an expressivst reading to "best" in the second conception of truth.

However, we have an intuition that one *means* something different by saying that "$\phi$ is true" and "I endorse $\phi$". One is justified in asserting the first statement iff one is justified in asserting the second. Rorty encourages us to [get over this intuition](/docs/phil/quotes/Bad realist intuitions.html), but Brandom believes it can be salvaged while still adhering to pragmatist scruples.

- "Jones believes $\phi$"
	-  Pragmatically, we are attributing commitment: "Jones is committed to $\phi$, e.g. can be asked for justification $\phi$ and use it as a premise of other claims."
- "Jones is justified in believing $\phi$"
	- Pragmatically, we are attributing entitlement; "Jones can provide a justification when asked.""
- "Jones *knows* that $\phi$" (i.e. the above +"and $\phi$ is true")
	- Pragmatically, *we* (the speaker) are taking a commitment to $\phi$.

So in the *interpersonal* case it is more clear that there is a difference in $\phi$ being assertable and $\phi$ being true.

## A further objection

Expressivists who want to equate the semantics "$\phi$" and "It is true that $\phi$" are only considering free-standing uses of $\phi$.  The [Frege-Geach argument](/docs/phil/Frege-Geach argument.html) demands emotivists to also consider embedded uses of $\phi$,[^ex] thus disquotationalism / prosentential theories are required to show how embedded uses of $\phi$ derive their meaning from free-standing uses of it.[^md]

[^ex]: "Well if that's true, then you should publish it!"
[^md]: For more details see Brandom's *Explanatory vs. Expressive Deflationationism about Truth*.

# Representation

Rorty is careful about the metaphor of [Language as tool](/docs/phil/Language as tool.html). He avoids letting representationalism sneak into his coping talk.

Davidson's switcharoo of [meaning and truth](/docs/phil/Meaning and truth.html).

For Rorty, coping, conversation, and [redescription](/docs/phil/Redescription.html) are three ways of talking about the same thing. Coping is deploying reason-relations in a practice of giving and assessing reasons.