---
title: Analytic and synthetic facts
tags: 
  - distinction

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/analytic and synthetic facts.yml
---

# Making the distinction 

Historically in philosophy, one finds a distinction frequently made 
between *analytic* and *synthetic* statements. We want to put declarative 
statements into two boxes:

1. Analytic:
   - "Cats are mammals"
   - "Every bachelor is unmarried"
2. Synthetic:
   - "There has existed a black dog"
   - "There are three people in this room right now"

How would we characterize analytic statements? One common way is to say that the 
truth of analytic statements depends purely on what the constituent terms *mean*, 
whereas synthetic statements (additionally) depend on the state of the world.


# Breaking the distinction 

It is broken in Quine's [Two Dogmas of Empiricism](/docs/phil/works/Two Dogmas of Empiricism.html).
What is challenged is the very notion of analyticity, i.e. that the analytic-synthetic distinction can be made at all.

He argues that the type of information required to make us change our opinion of the truth of "cats are mammals" and any synthetic statement are actually not different in kind. (We might discover all things that which call 'cats' have 
actually been biological-looking robots - we'd likely change what category to put 'cats' in than to declare all of these things are no longer cats.)

Quine's conclusion: we should cease to make the following distinctions:

- the analytic-synthetic distinction
- the meaning-theory distinction 
- the language-theory distinction 
- the meaning-belief distinction
  
Because all there is is the use of our expressions, and the usage is what determines both the meanings and what we take to be true.

Quine's target is [Carnap](/docs/phil/people/Rudolf Carnap.html) (who is thinking of artificial languages: first you fix the language, and then you go into the world to see which are true in virtue of what they mean).

# External resources
- [SEP](https://plato.stanford.edu/entries/analytic-synthetic/)