---
title: Noumena and phenomena
tags: 
  - distinction
  - RED

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/noumena and phenomena.yml
---

In the eyes of Hegel/Sellars/Brandom, [Kant](/docs/phil/people/Immanuel Kant.html) is interpreted as having radicalized the distinction between:

- primary qualities (properties that are truly there)
- secondary qualities (properties that are due to us).

He challenges us to divide the labor:

- what features is the *world responsible for*?
- what features are *we responsible for*?
  - E.g. the fact our theories are expressed in German/English

This distinction lives in [Sellars](/docs/phil/people/Wilfrid Sellars.html) as the difference between:

-  the world *in the narrow sense*
-  the world *in the wider sense*
    - E.g. which includes norms that are only accessible from a 
      participant's perspective.

Hegel and Brandom think that, even if it was Kant's idea, that it is a *bad* idea (but it's one that Sellars took from Kant).
