---
title: Contextualism
subtitle: Jason Bridges
date: June 3, 2010
---

- *Contexualism* concerns the truth of an utterance of depending on factors 
  outside of the statement itself.
- There is a spectrum of statements one can acknowledge as contexual:
  - At one extreme, statements like "I am cold"
     - The truth is obviously contexually dependent on the speaker of the 
       utterance.

# Examples
## Intermediate example - Mary
- Mary wins $1 million in lottery
   - Deedee says that Mary is rich now
   - Naomi (who is wealthier) says "No, Mary is not rich."
- We want to say Deedee and Naomi are both speaking "truth" and need an account.
    - Relevant contextual parameter: the standard of wealth according to 
      the speaker.
    - Contextualist says: because the conversational standards for deploying 
      "rich" vary among Deedee's community and Naomi's community, the truth 
      conditions of their utterances should also vary.

## Riskier example - the bank
- The bank case:
    - On Friday, a man and his wife go to the bank and see a long line. The man 
      says "Oh well we can go tomorrow" and asked how he knows, he says "I was 
      here last Saturday and they were open."
    - Alternate scenario, it's really impt that they deposit their check. He is 
      asked "how do you really know? Maybe they changed their hours." and he 
      updates "You know, you're right, I don't know."
    - Contextualist wants to say "I know X" and "I don't know X" were both 
      truthful utterances with no change in world state (but rather, what 
      changed was the context-dependent truth conditions)
- Epistemological contextualists claim that the standard for knowing X is 
  dependent on what doubts have been raised in a conversation (the doubts become 
  'live').  Skepticism is addressed because we can hand the skeptic a victory in 
  their ivory tower (you are right that we don't know anything) while denying 
  the skeptic the right to challenge an ordinary person living their life 
  claiming to know many things.
    - Counterpoint: why were hyperbolic doubts even raised? Actually, the 
      skeptics were concerned with ordinary claims of knowing.
    - Contextualists could be said to be using some motivated reasoning to 
      insulate ordinary belief from what goes on in the phil seminar room.

## Radical Example - Pea
A more radical example is [Pia and the maple tree](/docs/phil/situations/piatree.qmd).

# More on spectrum

The spectrum could be said to correspond to a belief in a 'core/unchanging' 
content of a word/sentence (meaning that is purely based on the definitions of 
the words) and people arguing how big that core should be.
  - "The cat is on the mat" - which cat may change on context, etc. but there is 
    something unchanging; we cannot mean "The dog is in the air."
    - Those who disagree have to explain how do we understand each other at all.
  - Some radical contextualists don't say that for all X Y, X can mean Y. But 
    just that forall utterances X, there is an indefinite number of meanings 
    that are  consistent with that utterance (there are also an indefinite 
    number of meanings that are inconsistent.

# Context principle
- The principle: that there is a kind of content of an utterance which is tied 
  to the point of the utterance (which is tied to motivations/expectations of 
  conversational participants).
- This is an underlying assumption of many contextualist arguments.
  - The point of Naomi's utterance is different (to relate Mary's wealth to the 
    standards of wealth in her world).
  - Unfounded: context principle justifies tying the truth conditions to 
    points/interest/conversational standards.
    - Counterexample: wealthy people who say they themselves aren't wealthy - 
      it is in their interests to not seem wealthy (to avoid legislation, to 
      seem like a salt-of-earth person). Perhaps their use of the word is 
      serving those desires.
    - The truth conditions ought to float free of the 'local discourse' if the 
      argument actually concerns disputed territory. If Deedee/Naomi agree that 
      the rich ought pay a special tax, then it is crucial to have a notion of 
      'rich' that is dictated by a larger discourse which includes both 
      participants (the larger community agrees with Deedee in this case, so 
      Naomi's claim can be called false even if it matches her local community's 
      use of the word).
  - Contextualists acknowledge that interests/focus of attention vary among 
    people but do not pay special attention to what those interests are - harsh 
    charge but evidence by the fact that most contextualists are not 
    methadological contextualists
    - (Wittgenstein was a methodological contextualist).
  - The 'freighted terms' which philosophers are most often interested in seem 
    to more likely be the cases like 'wealth' where we do not want to let 
    people's biases dictate the correctness of their word usage.
