---
title: 14. Skepticism
tags: 
 - podcast
subtitle: Ed Witherspoon
published: August 2, 2010

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/14. skepticism.yml
---

[Elucidations](/docs/phil/elucidations/Elucidations.html): [Prev](/docs/phil/elucidations/13. Judgment aggregation.html) [Next](/docs/phil/elucidations/15. Religious toleration.html)

# What is radical skepticism advocating?
  - Example: I know there is a table in front of me.
    - (both sides agree that, *if* I know anything, I at least know that)
  - However, the skeptic rejects that I know there is a table in front of me 
    and therefore rejects that I know anything.
  - Many different skeptical arguments, often of the form "There exists a 
    scenario in which you are having the same phenomenological experience yet 
    there is no table, so how can you know whether you are in that scenario vs 
    the genuine experience scenario?"
    - Examples: dreaming, [evil genius](/docs/phil/people/René Descartes.html), 
      [brain in a vat](/docs/phil/Epistemological skepticism.html) (from [Putnam](/docs/phil/people/Hilary Putnam.html))

# Argument against brain in a vat skepticism
- These are not a general anti-skeptic arguments, but other skeptical tactics 
  might be addressable by similar reasoning.
- Thus, Edward is proposing *bottom up* anti-skepticism, rather than some 
  *top-down* "reason for knowing that the table is there"

## [No reason to believe brains in vats can think](/docs/phil/interaction/Brain states and experience.html) 

The power of the skeptic's thought experiment comes from us easily imagining the 
possibility of a brain being subjected to various brain states. One tactic 
involves denying the skeptic's implicit claim that these brain states are 
tantamount to experience.

{{< include "/docs/phil/ed witherspoon argument.qmd" >}}


## There are reasons to believe brains in vats cannot think
Drawing from thoughts of [John MacDowell](/docs/phil/people/John MacDowell.html)'s [Mind and World](/docs/phil/works/Mind and World.html):

- For a thought to be 'about' an object (world-directed, with empirical 
  content) - it's necessary that the correctness of the thought to be answerable 
  to how things are.
- For an intention to be an intention - it has to determine the correctness / 
  incorrectness of some subsequent action.
- A brain is not logically answerable to reality and is not overtly acting in 
  the world, so it's not fair to say it has thoughts or intentions.

# Why even bother thinking about skeptic challenges?
- [Stanley Cavell](/docs/phil/people/Stanley Cavell.html) has written well about  how skeptical lines of thought arise
  naturally (i.e. they are not purely the product of academic philosophy).
- Skepticism shows up in lots of fields/subfields of philosophy, and it's 
  important to prevent the confusion that arises here from spreading. (e.g. 
  brain scanner is relevant in legal topics)
