---
title: Language and power
categories: 🔴
subtitle: Mark Lance
published: December 6, 2010
---

- This concerns the pragmatics of language
- Social identities are skills, being a professor/parent is like dribbling a 
  basketball
- "Calls"
  - Say "Yo, Matt!" to someone in the street. Have recognized Matt as a social 
    partner but also demands Matt recognize me.
- "Performative" Difference between judge saying "the meeting is adjourned" vs 
  someone outside looking in who tells someone "the meeting is adjourned"
- "Order"
  - Unlike a call, it is an asymmetric speech action.
  - Responding acknowledges the power gradient.
  - Distinct from requests and treaties
  - If students respond to roll call, they are jointly bringing into being the 
    roles of "teacher" and "student"
- Gendered/Racial
  - We recognize demographics in certain ways.
    - Data shows people talk to male babies different from female babies
    - Data shows teachers let male students talk for longer before interrupting 
      (even filtering for female Womens' Studies profs)
- You can refuse the way someone engages you, but is a tricky negotiation.
  - There's no way to stay neutral - either have to be aggressive or passive 
    (accept the role you don't want to be placed in) .
- A call can be responded to appropriately or inapprorpiate - placing someone in 
  a role puts them in a normative role.
- Example: school system in DC
  - Nominally egalitarian, however:
    - Good schools are in rich neighborhoods (issues with transportation)
    - Complicated application / interview process
- Some identities seem chosen vs not
  - Not exactly a clear line (one chooses to work at a sweatshop, but the 
    alternative was starving)
  - Big normative implications for roles that are perceived as a choice
- The point of analyzing these social roles is to see where it's possible to 
  intervene
  - Certain problems are only addressible by social organizers
  - We can be more aware of how these roles affect our lives
  - A project of political liberation.
- What's a good reason to resist a social role?
  - No general answers - just good reasons for doing anything. E.g. freedom, 
    prevention of human fluorishing.
