---
title: 20. Faith
tags: 
 - podcast
 - RED
subtitle: Simon Critchley
published: February 8, 2011

listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/20. faith.yml
---

[Elucidations](/docs/phil/elucidations/Elucidations.html): [Prev](/docs/phil/elucidations/19. Epistemic vigilance.html) [Next](/docs/phil/elucidations/21. Political liberalism.html)

- Belief when you don't have overwhelming evidence.
  - Something distinct from knowledge.
  - E.g. Faith in the goodness of humanity. Faith in the resurrection.
- Two opinions: faith is a virtue, faith is intellectually irresponsible
- What is the structure of the faith?
  - Recent interest in Paul:
    - Had a conversion from a persecutor of Christians. He doesn't seek 
      historical evidence for it.
    - After his revelation, he doesn't go to Jerusalem, he goes into the desert.
    - He is not seeking prophetic evidence, yet it enables him to act in the 
      world.
    - The structure of Paul's faith is interesting. "Response to a call" as 
      opposed to some concrete belief.
    - The formation of a self in relation to a call/ethical demand.
      - That call is going to motivate a self to act.
      - Relevance: there is a motivational deficit in liberal democracy, how do 
        we remedy this?
    - The interesting part of religion is not whether their supernatural beliefs 
      are true, rather how the call believers to action.
    - What sort of thing is commitment?
      - Something that is also touched upon in Existentialist philosophy too.
- Moral athiests could deny that they take things on faith.
  - Critchley thinks 'evangelical athiests' (Dawkins/Hitchens).
  - Faith in reason, that science will work out the truths of the universe 
    without participating.
  - In Sermon on the Mount, Jesus says to love your enemy and to have infinite 
    forgiveness.
    - You can think Jesus was entitled to make these demands because he was God.
    - Alternatively he was just some crazy guy making extreme demands to prick 
      people's conscience.
- Passive nihilism comes out of people being distanced/austerity towards moral 
  commitment.
- Reason/rationality cannot be divorced from processes like bureaucracy of 
  modernity. Need faith / commitment to overcome sorts of bad rational 
  processes.
- How to choose the right commitment?
  - E.g. want to avoid becoming committed Nazis.
  - Commitment + generality/universality (Kantian)
    - Need practical moral philosophy to popularize something abstract like 
      Kantian morality.
- Friendship and Love
  - These require trust/faith (Othello example)
  - Friendship: [Aristotelian](/docs/phil/people/Aristotle.html) vs Christian views
- A liberal society based on reason would require a private/public separation
  - Anarchism has a variety of alternatives of new forms of order.
