---
title: Perception of music
subtitle: Christopher Peacoke
date: June 21, 2011
---


- Is hearing emotion in music a purely cultural convention?
  - Distinguish two questions
    1. Whether culture has impact on the perceptual states from hearing pieces 
       of music
    2. Whether on a particular occasion of hearing music, the perception depends 
       on cultural factors.
  - The perception being dependent on cultural factors doesn't mean it can't be 
    considered perceptual
    - E.g. language (clearly culture-dependent) where the words perceived have 
      meanings
      - E.g. you hear/perceive "snow" as meaning *snow* (the explanation why 
        that in particular is the case involves culture) but the perception 
        itself is not cultural.
      - With music, it's not interesting to trace the causal origins of the 
        perceptual state but the nature of the perceptual state itself / what it 
        is for it to have emotional content.
- Three fundamental different experiences
  - See something a certain way (see an apple as an apple)
  - See something as a representation of something else (picture of an apple)
  - "Metaphorical seen-as"
    - "Juliet is the sun" - linguistic metaphors are just a specific instance of 
      a general mental state of metaphorical thinking.
      - Others attempts to reduce this type of thinking to other kinds of mental 
        states unsatisfactory.
    - Music Examples:
      - Des Prex, Ave Maria: lyrics involve "universe filling up gladness", and 
        you hear the music as filling up space.
      - Debussy,L'Voiles or Le catedrale engloutie: can perceive the fluttering 
        sails and sinking cathedral.
    - Distinction between imagining X as Y and phenomonologically perceiving X
      as Y (example of Still life with pots (Zurbarán) that you really directly 
      see as people, vs forcing yourself to imagine four things on the table as 
      people).
    - Phenomologically distinct from actually thinking the pots are people or 
      even depictions of people.
  - Explanation of this
    - "isomorphism" (Kris: actually should just be (homo)morphism)
    - Basically an analogy.
      - Changes in pitch and speed map onto changes in speed of the wind.
    - There are tons of these that are possible, but not all are 
      "psychologically real"
      - Minor chord has negative affect due to its relation to major chord.
      - Why is it this emotion rather than some other is an empirical question
      - Mozart B minor adagio extremely moving ... why? that's an empirical 
        question (great composers have a good intuition for this).
      - Great music critics are able to pick out and articulate these - after 
        hearing this it changes how you perceive the music.
        - Example: end of Schubert piece "you can hear the body slipping into 
          the water"
  - How is this related to hearing a piece of music as a certain genre?
    - "Romantic music is very expressive"
      - Problems
        - Other music just 'describes' emotions rather than expresses them
        -  Yet much medieval music also is clearly expressive.
    - Positive account of how to characterize romantic music
      - There are expressive actions
        - Not described in the thought/belief model where we do actions towards 
          some end / for some benefit. E.g. jump for joy.
      - There are actions we perceive as expressive.
      - Romantic music is perceived as expressive, and breaking classical 
        conventions in order to express this emotion.
        - Allows one to not purely be defined as breaking conventions (otherwise 
          you'd include impressionism, etc.)
        - Impressionist music is not perceived as expressive action.
