---
title: Sexuality and Law
categories: 🔴
subtitle: Martha Nussbaum
date: October 1, 2009
---

There has been historical precedent to place legal restrictions on human 
behavior due to disgust reaction

# Disgust
- Rejection of something that is seen as a contaminant (useful in the context of 
  feces, etc.). These are called the primary objects of disgust
- In all societies, it gets extended in practice to groups of people seen as 
  'low'/'dirty'
    - extending the attributes of primary objects of disgust to these people, 
      e.g. separate drinking fountains for blacks

# Historical theoretical justification
- Lord Devlin: a society needs to be able to defend itself against 
  intrusion/defilement.
    - Justifies making things illegal even if they cause no harm to others
    - His rival: John Stuart Mill who said only harm to others should matter
- More contemporarily, Leon Cass: disgust is a legitimate emotion which can 
  sometimes guide us legitimately warn us of atrocity.
    - E.g. "torture" elicits disgust that rightly directs us away from it

# An unreliable guide
- When disgust is potent, we cannot rely on reasoning to give us respect.
- Gays/Lesbians depicted as weirdos/animals
- 'Torture' also elicits indignation, which is a more constructive feeling 
  towards righting the wrong of torture (concede that disgust happens to be 
  right on this one)
    - That is wrong and it better not happen again
    - But maybe indignation may be argued to already be 'getting too close' - 
      dignifying the abhorrent act with the status of "an act that is wrong" - 
      maybe rejecting uncritically is the proper treatment?
    - "We won't look at that at all" is evasion of moral confrontation.
    - Both have cognitive content and are falliable
    - Disgust's validity limited to primary objects - which actually do pose a 
      danger.
- Juries to whom a murder is described in a more gory way are more likely to be 
  harsher, even though this doesn't always track how bad the homicide was / 
  whether it was premeditated

# Empathy
- Need to imagine the other as fully human like ourselves
- Is this sufficient? Couldn't a homophobe fairly imagine this but still 
  conclude the other person is wrong?
    - Nussbaum: Certainly. Empathy is not sufficient for compassion.
    - perhaps not even necessary, e.g. compassion towards actual animals we 
      cannot empathize with.

# Application to marriage
  - Should government be involved in marriage?
    - Marriage has three aspects:
      1. Religious: state shouldn't be involved (obviously)
      2. Material: benefits given to certain relationships (civil unions 
         sufficient)
      3. Stuff in between: marriage is important because it signals some sort of 
         societal approval of the act
        - Nussbaum doubts that this is really as true as proponents claim:
          - We don't think of the state as supporting the N'th marriage of some 
            celebrity
          - Extremely low bar in most states for being able to officiate a 
            marriage
    - Civil unions analogous to transracial marriage:
      - People had to fight to not give this a different term since they truly 
        believe it is equal

# Application to privacy
- Three dimensions that get conflated:
    - Informational: the private is secret
    - Spatial: a private place, like the home
    - Decisional: what is private is yours to design
- Example: pornography is legal, but only in your home. Or a court ruling that 
  gay sex was legal unclear about whether it was merely because it was 
  demonstrated in private that the homosexuality should be condoned.
- Mill: self-regarding impact principle
    - What impact does this have on non-consenting strangers
    - Could recover our intuitions (the pornography has an impact on other 
      people, acts in sex clubs that you have to voluntarily enter).
- We should avoid the word 'privacy' because it's such a nest of confusions.

[Response at the time]: # (
    - W/r/t torture + disgust + indignation:
      - Agree that indignation comes off as more constructive than disgust, 
        though is disgust an essential / primary cause for the indignation? Who 
        is indigant about torture but not disgusted by it?
    - Agree disgust is valid when it directs us away from danger
      - Though Nussbaum's opponents are claiming homosexuality is a (societal) 
        danger (for which disgust is just one piece of 'evidence'), so it's 
        deflecting the main argument.
    - A couple examples of disgust getting it wrong not convincing.
      - Could come up with examples of indignation getting it wrong according to 
        Nussbaum herself.
      - Hypothetical: suppose Native Americans were disgusted by European 
        settlers and were motivated to unify and reject the invasion. Wouldn't 
        this have saved their society? Was a (counterfactual) stronger disgust 
        reaction the only plausible hope for this happening?
    - Is not eliciting disgust in nonconsenting strangers bad by Mill's 
      principle? Couldn't there exist a country whose population is so vicerally 
      disgusted by homosexuality that, in that country, it truly is wrong to 
      have gay marriage? (e.g. Islamic country)
)