---
title: Metaphor
subtitle: Ted Cohen
date: March 4, 2010
---

# Examples of Metaphor
- What are examples of metaphor?
  - Need to be careful to not use
    - 'dead metaphors'
    - idioms
      - "bit the dust" / "went west" / "bought the farm" -> die
  - Metaphors are devices for saying something and using something else

# Questions philosophers ask
- There are two lines of questions:
  - Technical ones in the philosophy of language (e.g. Joseph Stern)
  - Aesthetic questions (this is what Ted is interested in)
    - Metaphors are small-scale works of art
      - you need imaginative capacity to make/understand one
      - Art: the thing we do that we don't need to do
        - it's the place human's exhibit their freedom

# Differences between metaphor and irony
- Once you understand a statement as ironic, it's not hard to figure out what it means.
- Could recognize something as a not-literal metaphor but then be puzzled about what it means
    - Try reading Wallace Stevens poetry as an example
    - Song of Solomon in the bible actually about sex, though you could read it without realizing that.

# Can metaphor be translated to non-metaphor
Is it possible to say what a metaphor says literally? Is this committing the 'heresy of paraphrase'?

- The question was confused. Metaphors aren't reducible to similes which have a straightforward content. ("juliet is the sun" is not "juliet is like the sun")
    - The simile is not true, there's no relevant property shared by juliet and the sun that romeo means.
- Inverse: "My love is like a red, red rose" why not "My life is a red, red rose"?
- These questions are addressed by Joseph Stern, from analysis of the context.
- In using a metaphor you will do something you couldn't do otherwise, harder to say if you will say something you couldn't do otherwise
    - Poetry is often the desire to compress a language and squeeze out all you can get
- Can you translate poetry?
    - Of course.
    - Czech poet, Anschel, makes his name easier one day as Ansel, then much later writes under anagram "Selam". Has a poem "Death Fugue" which begins "Der Tod ist ein Meister aus Deustchland"
      - Should be translated "Death is a Meister from Germany" because no subtitutee would work for Meister.
- Romans made very few advances in mathematics, possibly because their notation was so bad.
    - Representation makes a big difference in our ability to imagine
    - This may be analogous to poetry which represents concepts in a way that prose may not be able to.

# Rousseau paradox of freedom
- We must be free, but if we're free then there's chaos and we end up not free, so the solution is a self-imposed constraint.
- Related vaguely.

# Connecting with other people
- Interpreting metaphors in the same way seen as a means of connecting with other people (meaningful because it is falliable)
  - Wittgenstein in PI: "Sometimes people we cannot find our feet with them"
    - If you tell a joke that someone laughs at, you find youself in that person. Gratifying.
    - If you tell a joke that someone doesn't laugh at, we react poorly, like something has gone wrong.

# Jokes

- Irony/metaphors/jokes. All ways we live within but break rules. They help us get in touch with our freedom.
- Are inappropriate/offensive jokes similar in how they work to normal jokes? Or has something gone wrong?
  - Cohen: they're the same. Learning to not say telling offensive jokes is akin to learning to not pinch a stranger or roughhouse with someone who doesn't want to.
    - Double infliction: they don't like it, then you say they don't have a sense of humor (it's their fault for not finding it funny)
    - They don't need a justification to not find it funny.
    - No moral theories could account for why it's not ok for a stranger to say "I don't like it when you cross your legs" but ok to say "Your music is too loud". It's something to be negotiated - you won't learn it studying moral philosophy. The layperson is equally or more qualified than the philosopher at these practical questions.
  - No bearing on the functioning of the joke among people who find it funny.
    - Would need some account of it being harmful, that it perpetuates or creates harmful stereotypes has not been convincingly shown
    - The fact that a stereotype isn't true is not a mark against the joke (a joke is always a small fiction)
  - "Not everything you don't like is immoral"