---
title: The analytic / synthetic distinction
categories: "🟢"
listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../../ejs/custom.ejs"
  contents:
    - ../../../../backlinks/docs/phil/distinctions/broken/analytic_synthetic.yml
---

This intuitive distinction is explained 
[here](/docs/phil/distinctions/made/analytic_synthetic.qmd) 
but is broken in [Quine](/docs/phil/people/quine)'s 
[Two Dogmas of Empiricism](/docs/phil/people/quine/works/two_dogmas).
What is challenged is the very notion of analyticity, 
i.e. that the analytic-synthetic distinction can be made at all.

He argues that the type of information required to make us change our opinion of 
the truth of "cats are mammals" and any synthetic statement are actually not 
different in kind. (We might discover all things that which call 'cats' have 
actually been biological-looking robots - we'd likely change what category to 
put 'cats' in than to declare all of these things are no longer cats.)

Quine's conclusion: we should cease to make the following distinctions:

- the analytic-synthetic distinction
- the meaning-theory distinction 
- the language-theory distinction 
- the meaning-belief distinction
  
Because all there is is the use of our expressions, and the usage is what 
determines both the meanings and what we take to be true.

Quine's target is [Carnap](/docs/phil/people/carnap) (who is thinking 
of artificial languages: first you fix 
the language, and then you go into the world to see which are true in virtue of 
what they mean).