---
title: Hesperus and Phosphorus
categories: "⚪"
---

From [Wikipedia](https://en.wikipedia.org/wiki/Frege%27s_puzzles)

These are puzzles posed by [Frege](/docs/phil/people/frege). They are addressed
by making a [distinction between *sense* and *reference*](/docs/phil/distinctions/made/sense_reference.qmd).

# First puzzle 

The brightest star in morning was called Hesperus, and the brightest star of 
evening was called Phosphorus. Science later discovered these to be same object,
namely, Venus. Consider the two sentences:

1. Hesperus is Hesperus.
2. Hesperus is Phosphorus.

The first is just a matter of *a priori* logic, whereas the second is a 
nontrivial empirical truth. However, given the existing semantics (attributed 
to [Mill](/docs/phil/people/mill)), names have no meaning beyond their 
reference, meaning the second sentence *means* "Venus is Venus".

# Second puzzle 

3. Alex believes Hesperus is visible in the evening.
4. Hesperus = Phosphorus.
5. Therefore, Alex believes Phosphorus is visible in the evening.

This is not valid, but by naive subsitution of identicals it would appear to be so.
