---
title: What the Tortoise said to Achilles
categories: 🔴
listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../ejs/custom.ejs"
  contents:
    - ../../../backlinks/docs/phil/problems/tortoise.yml
---

By Lewis Caroll in 1895. [-@carroll2021tortoise]

## Summary

- The Tortoise assumes a proposition $p$ and a 
  [material conditional](/docs/math/defs/material_conditional.qmd) $p \implies q$.
  - The exact $p$ and $q$ aren't important to the moral of the story, though 
    it's something like "If $A=B$ and $B=C$ ($p$), then $A=C$ ($q$)"
  - The Tortoise is playing a game: I'll do anything you tell me to do, 
    *so long as you make explicit* the rule you're asking me to follow.
- Achilles tries to convince the Tortoise to accept $q$.
  - He says that logic *obliges* you to acknowledge $q$ in this case.
- The Tortoise is willing to go along with this but demands that this rule be 
  made explicit:
  - Achilles adds an extra axiom: $p \land (p \implies q) \implies q$.
- Achilles says that, now, you *really* have to accept $q$, given that you're 
  committed to:
  - $p$
  - $p \implies q$
  - $p \land (p \implies q) \implies q$.

- But the Tortoise notes that, if taking those three propositions and 
  concluding $q$ is really something logic obliges one to do, then it bears 
  writing down:
  - $p \land (p \implies q) \land (p \land (p \implies q)) \implies q$

- This can go ad infinitum; the Tortoise wins.

## Brandom commentary

- The most influential pragmatist work in the philosophy of logic.
- The lesson:
    - in any *particular* case, you can substitute a rule (that tells you you 
      can go from this to that) with an axiom.
    - But there have got to be some moves you can make without having to 
      explicitly license them by a principle.
    - I.e. you've got to distinguish between
            1.) premises from which to reason
            2.) principles in accordance with which to reason.

- This teaches an un-get-over-able lesson about the necessity for an *implicit 
  practical background* of making some moves that are just okay. Things that 
  would be put in a logical system, not in the forms of axioms, but in the form 
  of rules.

(This is from one of his [Sellars lectures](/docs/phil/people/brandom/sellars09/index.qmd))
