---
title: Universals
---
:::{.callout-warning}
These notes were hastily made for personal use. In the future they'll be made more presentable.
:::


It seems there is no problem thinking about what triangles and white things are, but what of triangularity and whiteness?

## An answer

This seems to be an instance of the [tooth pain](/docs/phil/situations/toothpain.qmd) issue. Noun-ness was for ordinary objects (with obvious ontological status) in an earlier game, but our creativity with language led us to nounify many other words, leading to `objects' with unclear ontological status.

### Realism

Realism asserts that universals are real things, that *triangularity* does refer to something in the world, although perhaps some metaphysical realm.

Plato is an example.

### Nominalism

Berkeley rejected Locke's view of abstract ideas on empiricist grounds. For him *triangularity* is just a name that refers to all triangles, rather than referring to something in particular.

There are no abstract ideas, just particulars.

### Conceptual nominalism

One can accept that universals refer to things in the world but be clear that they are mental things (concepts). Locke is an example.