---
title: On skepticism
categories: phil
draft: true 
---

- Hypothetical / empirical: Logical priority of conventional methods of determining thoughts over 
  brain scanner
    - Is this related to the fact that the brain scanner is purely correlation, 
      rather than based on some fundamental theory?
      - If we had a more fundamental theory that the brain scanner's workings 
        fit in with (e.g. quantum mechanics), then we would be more likely to 
        embrace the absurd scenario of the subject being insane (and/or we 
        failed to identify his environment) rather than saying quantum 
        mechanics is wrong.
      - Surely there are historical examples where X is a ground for some 
        technique Y, but for various reasons eventually Y becomes ground for X?
      - Logically-prior = closer to the 'center' of the web-of-beliefs.
    - Furthermore, this example only works if it is possible that there is a 
      conflict (in the world where there is perfect correlation, then we can 
      identify brain activity with thoughts)
- Conceptual analysis: "To be a brain state is one kind of thing, to have a thought is a 
  different kind of thing"
    - This is a good point towards saying they are not 'literally' identical, 
      in the sense of "My dad's wife" and "My mom" being literally 'different' 
      (they have different truth conditions) but may be equivalent given some 
      state of affairs.
      - This is perhaps sufficient to say "no reason to think brains in vats can 
        think" ... but at least it's sufficient for "there is a reason to think 
        brains in vats cannot think".
    - What this argument does not show (which maybe Ed is advocating) is that it 
      is incoherent to identify brain states with mental states. If we can 
      identify them, then they both are both kinds of things and there are no
    - There may be an isomorphism between the "logical space of reasons" and the 
      space of brain states related by physical causality.
      - If brain states (and their relations) were in bijective corrspondance to 
        thoughts, then we can refer to a brain state by its thought and 
        vice-versa. Whether or not this is the case is precisely the debate at 
        hand, but bringing this point up does not advance the argument one way 
        or another.
    - How to decide whether to believe such an isomorphism likely exists is 
      complicated.
    - This feels like isomorphic sets of objects living in different categories
- 2:
    - The belief that there is a table in front of me (even in brain-in-vat 
      scenario) IS answerable to reality (and the the belief is false). Likewise 
      for intentions (the intention will be unfulfilled, unless one is desiring 
      to be a brain in a vat)
    - How does this bear on the legality of killing comatose people (they are in 
      an analogous situation)?


