---
title: Sense dependence vs reference
---
:::{.callout-warning}
These notes were hastily made for personal use. In the future they'll be made more presentable.
:::

Two meanings of "$X$ depends on $Y$" that are easily conflated.

| Kind of reference      | Sense | Reference |
| ----------- | ----------- |-----------|
| Meaning of $X$ depends on $Y$      | you can't *understand* $X$ unless you *understand* $Y$       | you can't have $X$ existing without $Y$ existing |
| Flavor of dependence   | Epistemological        | Ontological |

- To assert a *sense* dependence of $X$ on $Y$ is to say: ".
- To assert a *reference* dependence is to say: "."

Brandom points out that we can have sense dependence without having reference dependence.

An example is a toy concept of beauty: "$X$ is beautiful if looking at it elicits pleasure in people."
 - This is asserting a *sense* dependence of beauty on people, but not a *reference* dependence.
 - It is intelligible that there could exist beautiful sunsets before there ever were people in the world, or if people never existed.