---
title: Constructions on V-categories
---

## Changing the base of enrichment


::: {.callout-note icon=false collapse=false}
## Proposition

<div id="induced-vcat"/></div>
Let $\mathcal{V}\xrightarrow{f}\mathcal{W}$ be a [monoidal monotone map](2.qmd#monoidal-monotone). Given a $\mathcal{V}$ [category](3.qmd#v-cat), called $\mathcal{C}$, one can construct an associated $\mathcal{W}$ category, let's call it $\mathcal{C}_f$

::: {.callout-note collapse=true appearance="minimal"}
## Proof

- Take the same objects: $Ob(\mathcal{C}_f):=Ob(\mathcal{C})$
- $\mathcal{C}_f(a,b) := f(\mathcal{C}(a,b))$
- Check this obeys the definition of an enriched category:
    - Condition on the monoidal unit:
        - $I_W \leq f(I_V)$ --- from the first condition of a monoidal monotone map}.
        - $\forall c \in Ob(\mathcal{C}): I_V \leq \mathcal{C}(c,c)$ --- first condition of an enriched category, which $\mathcal{C}$ is
        - $\forall c \in Ob(\mathcal{C}):f(I_V) \leq f(\mathcal{C}(c,c))$ --- monotone map property
        - $\forall c \in Ob(\mathcal{C}):f(I_V) \leq \mathcal{C}_f(c,c)$ --- definition of $\mathcal{C}_f$
        - $\forall c \in Ob(C_f): I_W \leq C_f(c,c)$ --- transitivity, using 1 and 4, noting $Ob(\mathcal{C})=Ob(\mathcal{C}_f)$
    - Condition on monoidal product:
        - $\mathcal{C}_f(c,d) \otimes_W \mathcal{C}_f(d,e) = f(\mathcal{C}(c,d)) \otimes_W f(\mathcal{C}(d,e))$ --- definition of $\mathcal{C}_f$
        - $f(\mathcal{C}(c,d)) \otimes_W f(\mathcal{C}(d,e)) \leq f(\mathcal{C}(c,d) \otimes_V \mathcal{C}(d,e))$  --- second condition of a monoidal monotone map
        - $\mathcal{C}(c,d) \otimes_V \mathcal{C}(d,e) \leq \mathcal{C}(c,e)$ --- Second condition of an enriched category
        - $f(\mathcal{C}(c,d) \otimes_V \mathcal{C}(d,e)) \leq f(\mathcal{C}(c,e)$ --- monotone map property
        - $f(\mathcal{C}(c,d) \otimes_V \mathcal{C}(d,e)) \leq \mathcal{C}_f(c,e)$ --- definition of $\mathcal{C}_f$
        - $\mathcal{C}_f(c,d) \otimes_W \mathcal{C}_f(d,e) \leq \mathcal{C}_f(c,e)$ --- transitivity, 1,2 and 5
:::
:::


::: {.callout-caution icon=false collapse=false}
## Metric space to preorder
<div id="metric-to-preorder"/></div>
- Consider the function $[0,\infty] \xrightarrow{f} \mathbb{B}$ which maps 0 to $true$ and otherwise to $false$.
- Can check that $f$ is monotonic and preserves the monoidal product+unit, so it is a [monoidal monotone](2.qmd#monoidal-monotone). (this was shown in [Exercise 2.44](3.qmd#2-44))
- Thus we have a tool to convert metric spaces into preorders.
:::


::: {.callout-important icon=false collapse=false}
## Exercise 2-67
<div id="2-67"/></div>

Recall the [regions of the world](#2-52) Hausdorff metric space we learned that a metric space can be converted into a preorder by a [particular](#metric-to-preorder) [monoidal monotone map](2.qmd#monoidal-monotone). How would you interpret the resulting preorder?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
The edges in the preorder represent the $\subseteq$ relation. For Boston, US, and Spain, it would look like this (with implicit self-edges): \begin{tikzcd}US& Spain \\Boston \arrow[u] &\end{tikzcd}
:::
:::



::: {.callout-important icon=false collapse=false}
## Exercise 2-68
<div id="2-68"/></div>

Find a different [monoidal monotone map](2.qmd#monoidal-monotone) $\mathbf{Cost}\xrightarrow{g}\mathbf{Bool}$ from the one in [Example 2.65](3.qmd#2-65).  Using the construction from [Proposition 2.64](3.qmd#induced-vcat), convert a [Lawvere metric space](3.qmd#lawvere-space) into two different preorders. Find a metric space for which this happens.

::: {.callout-note collapse=true appearance="minimal"}
## Solution
- Take the two monoidal monotone maps from [Exercise 2.44](2.qmd#2-44)
- $f$ yields a discrete preorder whereas $g$ does not.
- \begin{tikzcd}A \arrow[r, "1"] & B \\A \arrow[r, "\not\leq_f", dotted] & B \\A \arrow[r, "\leq_g"]             & B\end{tikzcd}

:::
:::


## Enriched functors

::: {.callout-tip icon=false collapse=false}
## A $\mathcal{V}$ *functor* $\mathcal{X}\xrightarrow{F}\mathcal{Y}$ between two $\mathcal{V}$ [categories](3.qmd#v-cat)

<div id="v-functor"/></div>
A function $Ob(\mathcal{X})\xrightarrow{F}Ob(\mathcal{Y})$ subject to the constraint:

- $\forall x_1,x_2 \in Ob(\mathcal{X}): \mathcal{X}(x_1,x_2) \leq \mathcal{Y}(F(x_1),F(x_2))$

:::


::: {.callout-caution icon=false collapse=false}
## $\mathbb{B}$-functors
<div id="bool-functors"/></div>
-  Monotone maps, considering the source and target preorders as $\mathbb{B}$-[categories](3.qmd#v-cat), are in fact $\mathbb{B}$-functors.
- The [monotone map](../1/4.qmd#monotone-map) constraint, that $x_1\ \leq_X\ x_2 \implies F(x_1)\leq_Y F(x_2)$, translates to the enriched category functor constraint, that $\mathcal{X}(x_1,x_2) \leq \mathcal{Y}(F(x_1),F(x_2))$.

:::

::: {.callout-caution icon=false collapse=false}
## **Cost**-functors
<div id="?"/></div>
- A **Cost**-functor is also known as a Lipschitz function.
- Therefore a Lipschitz function is one under which the distance between any pair of points does not increase.

:::


::: {.callout-important icon=false collapse=false}
## Exercise 2-73
<div id="2-73"/></div>
-  The concepts of opposite/dagger/skeleton extend from preorders to $\mathcal{V}$ categories.
    - An opposite $\mathcal{V}$ category $\mathcal{X}$ has the same objects and $\mathcal{X}^{op}(x,y):=\mathcal{X}(y,x)$
    - A *dagger* category is identical to its opposite.
    - A skeletal $\mathcal{V}$ category is one in which $I \leq \mathcal{X}(x,y) \land I \leq \mathcal{X}(y,x)$ implies $x = y$
- Recall an [extended metric space](3.qmd#metric) $(X,d)$ is a [Lawvere metric space](3.qmd#lawvere-space) with two extra properties.
- Show that a [skeletal](../1/3.qmd#skeletality) dagger **Cost**-category is an extended metric space.


::: {.callout-note collapse=true appearance="minimal"}
## Solution

- The [skeletal](../1/3.qmd#skeletality) dagger **Cost** category has a set of objects, $Ob(\mathcal{X})$ which we can call points.
- For any pair of points, we assign a hom-object in $[0,\infty]$ (we can call this a distance function).
- Skeletal property enforces the constraint $d(x,y)=0 \iff x=y$.
- The second enriched category property enforces the triangle inequality.
- Because we have a dagger category, our distance function is forced to be symmetric.
- Just like the information of a preorder is discarded (to yield a set) when we only consider skeletal dagger preorders, information must be discarded from **Cost**-categories to yield a Lawvere metric space.

:::
:::


## Product $\mathcal{V}$-categories



::: {.callout-tip icon=false collapse=false}
## The $\mathcal{V}$ product of two $\mathcal{V}$ categories, $\mathcal{X} \times \mathcal{Y}$

<div id="v-product"/></div>
This is also a $\mathcal{V}$ category with:

- $Ob(\mathcal{X}\times\mathcal{Y}) := Ob(\mathcal{X})\times Ob(\mathcal{Y})$
- $(\mathcal{X} \times \mathcal{Y})((x,y),(x',y')) := \mathcal{X}(x,x') \otimes \mathcal{Y}(y,y')$

:::


::: {.callout-caution icon=false collapse=false}
## **Cost** category product
<div id="cost-product"/></div>
- Let $\mathcal{X}$ and $\mathcal{Y}$ be the [Lawvere metric spaces](3.qmd#lawvere-space) (i.e. **Cost** categories) defined by the following weighted graphs.
- \begin{tikzcd}\mathcal{X}:= & A \arrow[r, "2"]            & B \arrow[r, "3"]            & C \\\mathcal{Y}:= & P \arrow[r, "5", bend left] & Q \arrow[l, "8", bend left] &  \end{tikzcd}
- The product can be represented by the following graph: \begin{tikzcd}{(A,P)} \arrow[r, "2"] \arrow[d, "5"', bend right]  & {(B,P)} \arrow[r, "3"] \arrow[d, "5"', bend right]  & {(C,p)} \arrow[d, "5"', bend right] \\{(A,Q)} \arrow[r, "2"'] \arrow[u, "8"', bend right] & {(B,Q)} \arrow[r, "3"'] \arrow[u, "8"', bend right] & {(C,Q)} \arrow[u, "8"', bend right]\end{tikzcd}
- The distance between any two points $(x,y),(x',y')$ is given by the sum $d_X(x,x)+d_Y(y,y)$.

- We can also consider the **Cost**-categories as matrices

| $\mathcal{X}$ | A        | B        | C |
|---|---|--|--|
| **A**             | 0        | 2        | 5 |
| **B**             | $\infty$ | 0        | 3 |
| **C**             | $\infty$ | $\infty$ | 0 |


|$\mathcal{Y}$ | P | Q |
|----|---|
|**P**             | 0 | 5 |
|**Q**             | 8 | 0 |

|$\mathcal{X}\times\mathcal{Y}$ | (A,P)    | (B,P)    | (C,P) | (A,Q)    | (B,Q)    | (C,Q) |
| -----|---|---|---|---|---|---|
|**(A,P)**                          | 0        | 2        | 5     | 5        | 7        | 10    |
|**(B,P)**                          | $\infty$ | 0        | 3     | $\infty$ | 5        | 8     |
|**(C,P)**                          | $\infty$ | $\infty$ | 0     | $\infty$ | $\infty$ | 5     |
|**(A,Q)**                          | 8        | 10       | 13    | 0        | 2        | 5     |
|**(B,Q)**                          | $\infty$ | 8        | 11    | $\infty$ | 0        | 3     |
|**(C,Q)**                          | $\infty$ | $\infty$ | 8     | $\infty$ | $\infty$ | 0     |

- Can view this as a 2x2 grid of 3x3 blocks: each is a $\mathcal{X}$ matrix shifted by $\mathcal{Y}$.
:::




::: {.callout-important icon=false collapse=false}
## Exercise 2-75
<div id="2-75"/></div>

Let $\mathcal{X} \times \mathcal{Y}$ be the $\mathcal{V}$-product of two $\mathcal{V}$ [categories](3.qmd#v-cat).

1. Check that for every object we have $I \leq (\mathcal{X} \times \mathcal{Y})((x,y),(x,y))$
2. Check that for every three objects we have:
    - $(\mathcal{X} \times \mathcal{Y})((x_1,y_1),(x_2,y_2)) \otimes (\mathcal{X} \times \mathcal{Y})((x_2,y_2),(x_3,y_3)) \leq (\mathcal{X} \times \mathcal{Y})((x_1,y_1),(x_3,y_3))$

::: {.callout-note collapse=true appearance="minimal"}
## Solution
1.
    - By axioms of $\mathcal{V}$ categories: $I \leq \mathcal{X}(x,x')=xx$ and $I \leq \mathcal{Y}(y,y')=yy$
    - By monotonicity: $I \leq xx \land I \leq yy$ implies $I = I \otimes I \leq xx \otimes yy$.
    - By the definition of a product category this last term can be written as $(\mathcal{X} \times \mathcal{Y})((x,y),(x,y))$

2.
    - By axioms of $\mathcal{V}$ categories: $\mathcal{X}(x_1,x_2) \otimes \mathcal{X}(x_2,x_3) \leq \mathcal{X}(x_1,x_3)$ and $\mathcal{Y}(y_1,y_2) \otimes \mathcal{Y}(y_2,y_3) \leq \mathcal{Y}(y_1,y_3)$
    - Therefore, by monotonicity, we have $(\mathcal{X}(x_1,x_2) \otimes \mathcal{X}(x_2,x_3)) \otimes (\mathcal{Y}(y_1,y_2) \otimes \mathcal{Y}(y_2,y_3)) \leq \mathcal{X}(x_1,x_3) \otimes  \mathcal{Y}(y_1,y_3)$
    - Desugaring the definiton of the hom-object in $\mathcal{X}\times\mathcal{Y}$, the property we need to show is that $(\mathcal{X}(x_1,x_2) \otimes\mathcal{Y}(y_1,y_2)) \otimes (\mathcal{X}(x_2,x_3) \otimes\mathcal{Y}(y_2,y_3)) \leq (\mathcal{X}(x_1,x_3) \otimes\mathcal{Y}(y_1,y_3))$
    - Given the \textbf{associativity} and \textbf{commutitivity} of the $\otimes$ operator, we can rearange the order and ignore parentheses for the four terms on the LHS. Do this to yield the desired expression.
:::
:::




::: {.callout-important icon=false collapse=false}
## Exercise 2-78
<div id="2-78"/></div>

-  Consider $\mathbb{R}$ as a [Lawvere metric space](3.qmd#lawvere-space), i.e. as a **Cost**-category.
- Form the **Cost**-product $\mathbb{R}\times\mathbb{R}$.
- What is the distance from $(5,6)$ to $(-1,4)$?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
The distance is the Manhattan/$L_1$ distance: $|5-(-1)| + |6-4| = 8$

:::
:::

