---
title: Categories
---

## Free Categories


::: {.callout-tip icon=false collapse=false}
## A *category*, $\mathcal{C}$
<div id="cat"/></div>


- Need to specify a collection of objects, $Ob(\mathcal{C})$
- For every two objects $c$ and $d$, one specifies a set $\mathcal{C}(c,d)$ called *morphisms} from $c$ to $d$
  - This set is called the *hom-set} and *morphism* is a shorthand for *homomorphism*
- For every object $c$ one specifies a morphism $id_c \in \mathcal{C}(c,c)$ called the *identity morphism*
- For every pair of morphisms $c \xrightarrow{f} d$ and $d \xrightarrow{g} e$, one specifies a morphism $c \xrightarrow{f;g}e$ called the *composite* of $f$ and $g$
- Furthermore, these must satisfy two conditions:
    1. unitality: composing with identities does not change anything
    2. associativity: $(f;g);h = f;(g;h)$
:::


::: {.callout-tip icon=false collapse=false}
## The category $\mathbf{Free}(G)$, given a [graph](../1/3.qmd#graph) $G=(V,A,s,t)$

<div id="freecat"/></div>


-  A category whose objects are vertices and morphisms are paths.
- The identity morphism is the trivial path at any vertex.
- Composition is path concatenation (this obeys unitality and associativity)
:::


::: {.callout-caution icon=false collapse=false}
## Natural numbers as a category
<div id="natcat"/></div>


- The natural numbers as a [free category](#freecat): $\boxed{\overset{\bullet}{z}\circlearrowleft s}$
- There are infinitely many paths, in bijection with the natural numbers.
- This is a category with one object, also called a *monoid*.
- The composition operation corresponds to the addition operation.
- Unitality and associativity give us the usual constraints on a monoid.
:::


::: {.callout-important icon=false collapse=false}
## Exercise 3-10
<div id="3-10"/></div>

The free category $3 := \mathbf{Free}(\boxed{\overset{v_1}\bullet \xrightarrow{f_1}\overset{v_2}{\bullet}\xrightarrow{f_2}\overset{v_3}{\bullet}})$ has three objects and six morphisms. Give the morphisms names and write out the composition operation in a 6x6 matrix. Which are the identities?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
Identities are 1,2,3

| $\circ$ | 1 | 2  | 3   | f1 | f2  | f12 |
|---------|---|----|-----|----|-----|------|
| 1       | 1 |    |     | f1 |     | f12 |
| 2       |   | 2  |     |    | f2  |     |
| 3       |   |    | 3   |    |     |     |
| f1      |   | f1 |     |    | f12 |     |
| f2      |   |    | f2  |    |     |     |
| f12     |   |    | f12 |    |     |     |

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 3-12
<div id="3-12"/></div>


1. What is the category **1**?
2. What is the category **0**?
3. What is the formula for the number of morphisms in **n**?



::: {.callout-note collapse=true appearance="minimal"}
## Solution

1. It has one object and one (identity) morphism.
2. It has zero objects and zero morphisms.
3. $1+2+...+n$, i.e. $\frac{n(n+1)}{2}$
:::
:::

## Categories via path equations
We can add constraints to a [free category](#freecat) which states that two paths are equal


::: {.callout-important icon=false collapse=false}
## Exercise 3-17
<div id="3-17"/></div>


Write down all the morphisms in the [free category](#freecat) presented by the following diagram:


\begin{tikzcd}[ampersand replacement=\&] \pagecolor{white}
  A \arrow[d, "g"'] \arrow[rr, "f"] \arrow[rrd, "j"] \& {} \& B \arrow[d, "h"] \\C \arrow[rr, "i"']\& {} \& D \&f;h=j=g;i \& {}
\end{tikzcd}

::: {.callout-note collapse=true appearance="minimal"}
## Solution
$id_A,id_B,id_C,id_D,f,h,g,i,j$

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 3-19
<div id="3-19"/></div>

What are the morphisms in the following [category](#cat): $\boxed{\overset{\bullet}{z}\circlearrowleft s\ \ \boxed{s;s;s;s = s;s}}$

::: {.callout-note collapse=true appearance="minimal"}
## Solution
z,s,ss,sss

:::
:::

## Preorders and free categories

- Takeaway: A preorder is a category where every two parallel arrows are the same.
- Any preorder can be considered a category, and any category can be crushed down into a preorder (called *preorder reflection*).
  - The objects are the elements of the set, and there is a single morphism between $a$ and $b$ iff $a \leq b$
- Considering a preorder as a category is right adjoint to turning a category into a preorder by preorder reflection.
- Every category presentation lies somewhere between the free category and the preorder reflection.



::: {.callout-important icon=false collapse=false}
## Exercise 3-21
<div id="3-21"/></div>


What equations are needed to add to the following graphs in order to present the associated preorders?

\begin{tikzcd}[ampersand replacement=\&] \pagecolor{white} 1 \& \bullet \arrow[r, "f", bend left] \arrow[r, "g"',bend right] \& \bullet                \\2 \& \bullet \circlearrowleft f\&\\3 \& \bullet \arrow[r, "f"] \arrow[d, "g"']\& \bullet \arrow[d, "h"] \\  \& \bullet \arrow[r, "i"]\& \bullet\\4 \& \bullet \arrow[d, "g"] \arrow[r, "f"]\& \bullet \arrow[d, "h"] \\  \& \bullet\& \bullet\end{tikzcd}

::: {.callout-note collapse=true appearance="minimal"}
## Solution
1. f=g
2. f;f=f
3. f;h=g;i
4. none are needed
:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 3-22
<div id="3-22"/></div>

What is the preorder reflection of the category $\mathbb{N}$ from [this example](#natcat)

::: {.callout-note collapse=true appearance="minimal"}
## Solution
The trivial preorder of one object.
:::
:::


## Important categories in mathematics
- What are commonly called categories are actually **Set}-categories, in the terminology of $\mathcal{V}$ categories.
- There are many important categories:
    - **Top** - topological spaces (neighborhood)
    - **Grph** - graphs (connection)
    - **Meas** - measure spaces (amount)
    - **Mon** - monoids (action)
    - **Grp** - groups (reversible action, symmetry)
    - **Cat** - categories (action in context, structure)



::: {.callout-tip icon=false collapse=false}
## The *category of sets*, denoted **Set**
<div id="set"/></div>
- Objects are the collection of all sets.
- Morphisms are set-functions
- Composition is function composition (satsifies associativity), identities are the identity functions (satisfies identity constraints).
- Closely related is the subcategory **FinSet** of finite sets with morphisms being set-functions.
:::


::: {.callout-caution icon=false collapse=false}
## Opposite category
<div id="op"/></div>
Any category $\mathcal{C}$ induces another category, $\mathcal{C}^{op}$ defined as the same objects but all arrows reversed.
:::


## Isomorphisms in a category
Isomorphisms formalize the notion of 'interchangibility', e.g. in a preorder the fact that $a \cong b$ tells us that it doesn't matter whether someone tells us $c \leq a$ versus $c \leq b$.

::: {.callout-tip icon=false collapse=false}
## An *isomorphism} in a category

<div id="iso"/></div>
- A morphism $A \xrightarrow{f}B$ such that there exists a morphism $B \xrightarrow{g}A$ satisfying $f;g=id_A$ and $g;f=id_B$
- We call *f} and *g} inverses and can write $g=f^{-1}$
- We say A,B are isomorphic objects in this case.
:::


::: {.callout-caution icon=false collapse=false}
## Isomoprhisms in **Set**
<div id="isoset"/></div>

The set $\{a,b,c\}$ and $\bar{3}$ are [isomorphic](#iso) (we have $3!$ bijections to choose from). The isomorphisms in **Set** are the bijections.
:::

::: {.callout-caution icon=false collapse=false}
## Retractions are not isomorphisms
<div id="?"/></div>

- It is possible for $f;g=id$ but $g;f \ne id$
- \begin{tikzcd} \pagecolor{white} 1 \arrow[r, "f"] & A \arrow[r, "g"] & 1 \\& B \arrow[ru]     &   \\2 \arrow[r]      & C \arrow[r]      & 2\end{tikzcd}
- This is called a *retraction* rather than an *isomorphism*.
:::

::: {.callout-important icon=false collapse=false}
## Exercise 3-31
<div id="3-31"/></div>

Show that the identity arrow on any given object is an [isomorphism](#iso).

::: {.callout-note collapse=true appearance="minimal"}
## Solution
The inverse to $id_c$ exists; it is itself: $id_c ; id_c = id_c$ (from the identity property)
:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 3-32
<div id="3-32"/></div>

A monoid in which every morphism is an [isomorphism](#iso) is known as a *group*
1. Is the [natural numbers monoid](#natcat) a group?
2.  Is the monoid with the added constraint $s;s=z$  a group?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
\begin{}
1. No, $s$ has no inverse (no natural number can be added to 1 to get 0)
2. Yes, this is the cyclic group with two elements.
:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 3-33
<div id="3-33"/></div>

Someone says that the only [isomorphisms](#iso) in $\mathbf{Free}(G)$ for some graph $G$ are the identity morphisms. Are they correct?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
They are correct. If we could compose $f;g$ to get a morphisms from $c$ to $c$, a free category would pick a new morphism rather than re-use the identity (which could be forced with a constraint).
:::
:::
