---
title: Monotone maps
---

::: {.callout-tip icon=false collapse=false}
## A monotone map between preorders $(A, \leq_A)$ and $(B, \leq_B)$
<div id="monotone-map"/></div> A function $A \xrightarrow{f} B$ such that $\forall x,y \in A: x \leq_A y \implies f(x) \leq_B f(y)$
:::

::: {.callout-tip icon=false collapse=false}
## A dagger preorder
<div id="dagger-preorder"/></div>
$q \leq p \iff p \leq q$

- this is tantamount to an equivalence relation.
:::

::: {.callout-tip icon=false collapse=false}
## A preorder isomorphism
<div id="preorder-iso"/></div>
A \monotone map for which there exists an inverse monotone map such that $f;g=id$ and $g;f = id$

- If this exists, we say the preorders involved are *isomorphic*.
:::

::: {.callout-tip icon=false collapse=false}
## A pullback along a monotone map $P \xrightarrow{f} Q$
<div id="pullback-along-monotone"/></div>

- We take the preimage of $f$, but not for a single element of $Q$ but rather an [upper set](3.qmd#upper-set) of $Q$.
- \begin{tikzcd} {(P, \leq_P)} \arrow[d, "f^*(u) \in U(P)"', dashed] \arrow[r, "f"] & {(Q, \leq_Q)} \arrow[ld, "u \in U(Q)"] \\ \mathbb{B}ool& \end{tikzcd}
- Noting that [upper sets are monotone maps to $\mathbb{B}$](#monotones_to_bool), it follows that the result of a pullback is an upper set in $P$ follows from the fact that composition preserves monotonicity.
- Therefore the type of the pullback is $U(Q) \xrightarrow{f^*} U(P)$
:::


::: {.callout-important icon=false collapse=false}
## Exercise 1-66

<div id="1-66"/></div>
Let $(P, \leq)$ be a [preorder](3.qmd#preorder) and recall the [opposite preorder](3.qmd#opposite-preorder).

1. Show that the set $\uparrow(p) := \{p' \in P\ |\ p \leq p'\}$ is an [upper set](3.qmd#upper-set) for any $p \in P$
2. Show that this construction defines a monotone map $(P, \leq^{op}) \xrightarrow{\uparrow} U(P)$
3. Show that $p \leq p' \iff \uparrow(p') \subseteq \uparrow(p)$
4. Draw a picture of the map $\uparrow$ in the case where $P$ is the preorder $(b\geq a \leq c)$.

::: {.callout-note collapse=true appearance="minimal"}
## Solution
This is the *Yoneda lemma for preorders* (i.e. up to equivalence, to know an element is the same as knowing its [upper set](3.qmd#upper-set)).

1. This is basically the definition an upper set starting at some element.
2. Interpreting the meaning of the preorder in the domain and codomain of $\uparrow$, this boils down to showing $p \leq p'$ implies $\uparrow(p') \subseteq \uparrow(p)$
          - This is shown by noting that $p' \in \uparrow(p)$ and anything `above' $p'$ (i.e. $\uparrow(p')$) will therefore be in $\uparrow(p)$.
3. Forward direction has been shown above
    - The other direction is shown just by noting that $p\prime$ must be an element of $\uparrow(p\prime)$ and by the subset relation also in $\uparrow(p')$, therefore $p \leq p'$.
4.  \begin{tikzcd}
      B & & C &  & \{B\} & & \{C\} \\
      & A \arrow[lu] \arrow[ru] & {} \arrow[rr, "\uparrow", dotted, bend left] &  & {}    & \{A, B, C\} \arrow[ru] \arrow[lu] &
    \end{tikzcd}
:::
:::



::: {.callout-important icon=false collapse=false}
## Exercise 1-67

<div id="1-67"/></div>
Show that when $P$ is a discrete preorder, then every function $P \rightarrow Q$ is a monotone map, regardless of the order $\leq_Q$.

::: {.callout-note collapse=true appearance="minimal"}
## Solution
The only time the monotonicity criterion is deployed is when two elements of $P$ are related, and for a discrete category this means we only have to check whether $f(a) \leq_Q f(a)$, which is true because preorders are reflexive.
:::
:::




::: {.callout-note icon=false collapse=false}
## Proposition

<div id="id-monotone"/></div>

- For any [preorder](3.qmd#preorder), the identity function is a monotone map.
- The composition of two monotone maps ($P \xrightarrow{f} Q \xrightarrow{g} R$) is also monotone.

::: {.callout-note collapse=true appearance="minimal"}
## Proof
-  Monotonicity translates to $a \leq b \implies a \leq b$ and is trivially true.
- Need to show: $a \leq_P b \implies g(f(a)) \leq_R g(f(b))$
    - The monotonicity of $f$ gives us $f(a) \leq_Q f(b)$ and the monotonicity of $g$ gives us the result we need.

:::
:::

::: {.callout-note icon=false collapse=false}
## Proposition
<div id="monotones-to-bool"/></div>
Let $P$ be a preorder. Monotone maps $P \rightarrow \mathbb{B}$ are in one-to-one correspondance with [upper sets](3.qmd#upper-set) of $P$.

::: {.callout-note collapse=true appearance="minimal"}
## Proof
-  Let $P \xrightarrow{f} \mathbb{B}$ be a monotone map. The subset $f^{-1}(true)$ is [upper set](3.qmd#upper-set).
    - Suppose $p \in f^{-1}(true)$ and $p \leq q$.
    - Then $true = f(p) \leq f(q)$ because $f$ is monotonic.
    - But there is nothing strictly greater than $true$ in $\mathbb{B}$, so $f(q) = true$ and therefore $q \in f^{-1}(true)$ too.
- Suppose $U \in U(P)$, and define $P\xrightarrow{f_U}\mathbb{B}$ such that $f_U=true \iff p \in U$
    - Given there are only two values in $B$ and an arbitrary $p\leq q$, the only way for this to *not* be monotone is for $f_U(p) \land \neg f_U(q)$ but this defies the definition of an upper set.
- The two constructions are mutually inverse.

:::
:::


::: {.callout-important icon=false collapse=false}
## Exercise 1-73

<div id="1-73"/></div>
Recall [skeletal](3.qmd#skeletality) preorders and dagger preorders.

Show that a skeletal dagger preorder is just a discrete preorder (and hence can be identified with a set).

::: {.callout-note collapse=true appearance="minimal"}
## Solution
-  Because preorders are reflexive, we just have to show $a \ne b \implies a \not\leq b$, or its contrapositive: $a \leq b \implies a = b$.
- $a \leq b \overset{dagger}{\implies} b \leq a \overset{skeletal}{\implies} a = b$
:::
:::