---
title: Meets and joins
---

## Definitions and basic examples

::: {.callout-tip icon=false collapse=false}
## the *meet* of $A \subseteq P$ for a preorder $(P, \leq)$
<div id="meet"/></div>
The meet $\wedge A$ is an element such that

- $\forall a \in A: \wedge A \leq a$
- $\forall q \in P: (\forall a \in A: q \leq a) \implies q \leq \wedge A$
- Think of as a GREATEST LOWER BOUND
:::

::: {.callout-tip icon=false collapse=false}
## The *join* of $A \subseteq P$ for a preorder $(P, \leq)$
<div id="join"/></div>
The join $\vee A$ is an element such that:

- $\forall a \in A: a \leq \vee A$
- $\forall q \in P: (\forall a \in A: a \leq q) \implies \vee A \leq q$
- Think of as a LEAST UPPER BOUND
:::

- There could be multiple meets/joins, but the definition forces them to be isomorphic.
- An arbitrary preorder need not have a meet nor join:
    - E.g a two element discrete preorder has no overall meet/join, because the meet must be less/greater than or equal to both elements in the set.

::: {.callout-caution icon=false collapse=false}
## Meets and joins of $\mathbb{B}$
<div id="meetjoin-bool"/></div>
In the booleans, the meet of any two elements is given by $AND$ and the join of any two elements is given by $OR$.
:::

::: {.callout-caution icon=false collapse=false}
## Meet and joins of a powerset
<div id="meetjoin-pset"/></div>

In a power set, the meet of a collection of subsets is their intersection, while the join is their union.
:::

::: {.callout-caution icon=false collapse=false}
## Meets and joins of a total order
<div id="meetjoin-total-order"/></div>
In a total order, the meet of a set is its infimum, while the join is the supremum.

- Note that $\mathbb{B}$ is a total order, to generalize the meets and joins of $\mathbb{B}$ given above.
:::

::: {.callout-note icon=false collapse=false}
## Proposition
<div id="meet-join-subset"/></div>
Suppose $(P,\leq)$ is a [preorder](3.qmd#preorder) and $A \subseteq B \subseteq P$ are subsets that have meets. Then $\bigwedge B \leq \bigwedge A$.

::: {.callout-note collapse=true appearance="minimal"}
## Proof
-  Let $m = \bigwedge A$ and $n = \bigwedge B$.
- For any $a \in A$ we also have $a \in B$, so $n \leq A$ because $n$ is a lower bound for $B$.
- Thus $n$ is also a lower bound for $A$ and hence $n \leq m$ because $m$ is $A$'s greatest lower bound.
:::
:::

::: {.callout-important icon=false collapse=false}
## Exercise 1-85

<div id="1-85"/></div>
Let $p \in P$ be an element in a [preorder](3.qmd#preorder). Consider $A = \{p\}$

1. Show that $\wedge A \cong p$
2. Show that if $P$ is a partial order, then $\wedge A = p$
3. Are the analogous facts true when $\wedge$ is replaced by $\vee$?

::: {.callout-note collapse=true appearance="minimal"}
## Solution
1.
    - The first condition of the meet gives us that $\wedge A \leq p$.
    - The second condition is that $\forall q \in P: q \leq p \implies q \leq \wedge A$.
        - Substituting $p$ in for $q$, the antecedent holds such that we get $p \leq \wedge A$.
    - Therefore $p \cong \wedge A$
2. The difference between a partial order and a preorder is that congruent elements are equal, so we directly get that $p = \wedge A$
3. Yes, the argument is perfectly symmetric.
:::
:::

## Back to observations and generative effects
-  We are comparing the observation of a combined system or the combination of observations.
- The other direction, restricting an observation of a system to a subsystem, does not have problems for [monotone maps](4.qmd#monotone-map) (which preserve meets, not joins).


::: {.callout-tip icon=false collapse=false}
## A monotone map $P \xrightarrow{f} Q$ that *preserves meets*

<div id="mono-preserve-meet"/></div>
-  $f(a \land_P b) \cong f(a) \land_Q f(b)$
- Likewise, to *preserve joins* is for $f(a \lor_P b) \cong f(a) \lor_Q f(b)$
:::


::: {.callout-tip icon=false collapse=false}
## A monotone map $P \xrightarrow{f} Q$ has a \emph{generative effect}

<div id="generative-effect"/></div>
$\exists a,b \in P: f(a) \lor f(b) \not\cong f(a \lor v)$
:::


::: {.callout-important icon=false collapse=false}
## Exercise 1-94

<div id="1-94"/></div>
Prove that for any [monotone map](4.qmd#monotone-map) $P \xrightarrow{f} Q$:

- if there exist $a \lor b \in P$ and $f(a) \lor f(b) \in Q$:
- $f(a) \lor_Q f(b) \leq f(a \lor_P b)$

::: {.callout-note collapse=true appearance="minimal"}
## Solution

-  Let's abbreviate $f(a\ \lor_P\ b)$ as $JF$ (join-first) and $f(b)\ \lor_Q\  f(a)$ as $JL$ (join-last)
    - This exercise is to show that $JL \leq JF$
- The property of joins gives us, in $P$, that $a\ \leq\ (a \lor b)$ and $b\ \leq\ (a \lor b)$
    - Monotonicity then gives us, in $Q$, that $f(a) \leq JF$ and $f(b) \leq JF$
- We also know from the property of joins, in $Q$, that $f(a) \leq JL$ and $f(b) \leq JL$
- The only way that $JF$ could be strictly smaller than $JL$, given that both are $\geq f(a)$ and $\geq f(b)$ is for $f(a) \leq JF < JL$ and  $f(b) \leq JF < JL$
- But, $JL \in Q$ is the smallest thing (or equal to it) that is greater than $f(a)$ and $f(b)$, so this situation is not possible.

:::
:::

