---
title: Mind-body dualism
categories: ⚪
listing:
  id: backlinks
  type: table
  page-size: 100000
  filter-ui: true
  template: "../../../../../ejs/custom.ejs"
  contents:
    - ../../../../../backlinks/docs/phil/distinctions/made/dualisms/mind_body.yml
---

[Descartes](/docs/phil/people/descartes) had invented 
[representation](/docs/phil/definitions/representation.qmd) but came to think 
of things things in the
world to be divided into representeds (things) and representings (ideas).

# Complaint about Cartesian dualism

- If you're committed to "mind stuff" being non-extended,
- and to the physical world being extended,
- [throw in some general claims about causation (e.g. it occurs in a place)],
- then perception and agency become unintelligble. 
  - How is the mind affected by real stuff / how can the mind cause something?

# Cartesian minds as socially constructed
This is the thesis of *Incorribility as the Mark of the Mental*. Cartesian minds
are something that we created because we started to treat each other a certain 
way.

The mind-body problem was a modern invention - the ancients did not struggle 
with it because they did not make Descartes' move of assimmilating "impressions"
and "thoughts" both as "ideas". 
